// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// AmbListEventsParams filters the list_events read.
type AmbListEventsParams struct {
	// Keep only events of this exact type (for example `amb.sent` or `amb.send_failed`). Omit for the full timeline.
	Type AMBMessageEventType
}

func (p AmbListEventsParams) toWire() *oapi.ListAMBMessageEventsParams {
	return &oapi.ListAMBMessageEventsParams{
		Type: optZero(p.Type),
	}
}

// AmbListParams filters the list. Zero-value fields are omitted.
type AmbListParams struct {
	// Filter to messages belonging to this conversation.
	ConversationID string
	// Filter to messages belonging to this business.
	BusinessAccountID string
	// Filter to received (`inbound`) or sent (`outbound`) messages.
	Direction AMBMessageDirection
	// Filter to messages with this status.
	Status AMBMessageStatus
	// Filter to messages whose content is this shape.
	Kind AMBContentKind
	// Filter to outbound messages sent with this category, exact match.
	Category string
	// Filter by tag. Accepts `name` to match any record carrying that tag name, or `name:value` to match a specific tag pair (for example `category:welcome`). Repeat the parameter to add more tags. A record must match every tag listed to be returned.
	Tag []string
	// Limits the response to resources created at or after this timestamp. Combine it with `created_before` to select a time window. Use an RFC 3339 timestamp with a timezone offset.
	CreatedAfter time.Time
	// Limits the response to resources created before this timestamp. Combine it with `created_after` to select a time window. Use an RFC 3339 timestamp with a timezone offset.
	CreatedBefore time.Time
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p AmbListParams) toWire(startingAfter string) *oapi.ListAMBMessagesParams {
	return &oapi.ListAMBMessagesParams{
		ConversationId:    optZero(p.ConversationID),
		BusinessAccountId: optZero(p.BusinessAccountID),
		Direction:         optZero(p.Direction),
		Status:            optZero(p.Status),
		Kind:              optZero(p.Kind),
		Category:          optStr(p.Category),
		Tag:               optSlice(p.Tag),
		CreatedAfter:      optTime(p.CreatedAfter),
		CreatedBefore:     optTime(p.CreatedBefore),
		Limit:             optInt(p.Limit),
		EndingBefore:      optStr(p.EndingBefore),
		StartingAfter:     optStr(startingAfter),
	}
}

// ListEvents Reads the processing events for a message in your workspace. Use the events to inspect rejections and gateway failures before deciding whether to submit another message.
func (s *AmbService) ListEvents(ctx context.Context, messageId string, params AmbListEventsParams, opts ...option.RequestOption) (*AMBMessageEventList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListAMBMessageEvents(ctx, oapi.AMBMessageID(messageId), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBMessageEventList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get Reads a message in your workspace, including its native content and processing state. Sent records Apple gateway acceptance; a send failure does not rule out an earlier attempt reaching Apple.
func (s *AmbService) Get(ctx context.Context, messageId string, opts ...option.RequestOption) (*AMBMessage, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetAMBMessage(ctx, oapi.AMBMessageID(messageId), &oapi.GetAMBMessageParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBMessage
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *AmbService) ListPage(ctx context.Context, params AmbListParams, startingAfter string, opts ...option.RequestOption) (*AMBMessageList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListAMBMessages(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBMessageList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List Lists your workspace's incoming and outgoing Apple messages with cursor pagination. Filter by business or conversation to inspect one exchange; sent records Apple gateway acceptance.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *AmbService) List(ctx context.Context, params AmbListParams, opts ...option.RequestOption) iter.Seq2[*AMBMessage, error] {
	return paginate(func(cursor string) ([]AMBMessage, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}
