// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// AmbBusinessAccountsSubmissionsListParams filters the list. Zero-value fields are omitted.
type AmbBusinessAccountsSubmissionsListParams struct {
	// Field to sort by. Possible values: `created_at`. Defaults to `created_at`.
	Sort AMBBusinessAccountSubmissionSort
	// Sort direction. Defaults to `desc`, which sorts from newest to oldest or largest to smallest, depending on the selected sort field.
	Order SortOrder
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
	// When true, the response includes a `total` field with the total number of items matching the request's filters across all pages.
	IncludeTotal bool
}

func (p AmbBusinessAccountsSubmissionsListParams) toWire(startingAfter string) *oapi.ListAMBBusinessAccountSubmissionsParams {
	return &oapi.ListAMBBusinessAccountSubmissionsParams{
		Sort:          optZero(p.Sort),
		Order:         optZero(p.Order),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		IncludeTotal:  optBool(p.IncludeTotal),
		StartingAfter: optStr(startingAfter),
	}
}

// AmbBusinessAccountsSubmissionsCreateParams is the request body for create.
type AmbBusinessAccountsSubmissionsCreateParams struct {
	// Uploaded PDF attachment containing the business readiness assessment.
	ReadinessAttachmentID string
	// Uploaded PDF attachment describing the proposed customer use cases.
	UseCasesAttachmentID string
	// Uploaded MP4 attachment demonstrating the customer experience.
	VideoAttachmentID string
}

func (p AmbBusinessAccountsSubmissionsCreateParams) toWire() oapi.AMBBusinessAccountSubmissionCreate {
	body := oapi.AMBBusinessAccountSubmissionCreate{}
	body.ReadinessAttachmentId = p.ReadinessAttachmentID
	body.UseCasesAttachmentId = p.UseCasesAttachmentID
	body.VideoAttachmentId = p.VideoAttachmentID
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *AmbBusinessAccountsSubmissionsService) ListPage(ctx context.Context, businessAccountId string, params AmbBusinessAccountsSubmissionsListParams, startingAfter string, opts ...option.RequestOption) (*AMBBusinessAccountSubmissionList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListAMBBusinessAccountSubmissions(ctx, oapi.AMBBusinessID(businessAccountId), params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBBusinessAccountSubmissionList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List Lists the review attempts for a business in your workspace. Each attempt retains the business identity and evidence selected at submission.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *AmbBusinessAccountsSubmissionsService) List(ctx context.Context, businessAccountId string, params AmbBusinessAccountsSubmissionsListParams, opts ...option.RequestOption) iter.Seq2[*AMBBusinessAccountSubmission, error] {
	return paginate(func(cursor string) ([]AMBBusinessAccountSubmission, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, businessAccountId, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Create Submits an account for review, making its name, Apple UUID and three uploaded evidence attachments available to Bird staff. This does not approve the account.
func (s *AmbBusinessAccountsSubmissionsService) Create(ctx context.Context, businessAccountId string, params AmbBusinessAccountsSubmissionsCreateParams, opts ...option.RequestOption) (*AMBBusinessAccountSubmission, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateAMBBusinessAccountSubmissionParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateAMBBusinessAccountSubmission(ctx, oapi.AMBBusinessID(businessAccountId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBBusinessAccountSubmission
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
