// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// AmbBusinessAccountsEventsListParams filters the list. Zero-value fields are omitted.
type AmbBusinessAccountsEventsListParams struct {
	// Field to sort by. Possible values: `created_at`. Defaults to `created_at`.
	Sort AMBBusinessAccountEventSort
	// Sort direction. Defaults to `desc`, which sorts from newest to oldest or largest to smallest, depending on the selected sort field.
	Order SortOrder
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
	// When true, the response includes a `total` field with the total number of items matching the request's filters across all pages.
	IncludeTotal bool
}

func (p AmbBusinessAccountsEventsListParams) toWire(startingAfter string) *oapi.ListAMBBusinessAccountEventsParams {
	return &oapi.ListAMBBusinessAccountEventsParams{
		Sort:          optZero(p.Sort),
		Order:         optZero(p.Order),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		IncludeTotal:  optBool(p.IncludeTotal),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *AmbBusinessAccountsEventsService) ListPage(ctx context.Context, businessAccountId string, params AmbBusinessAccountsEventsListParams, startingAfter string, opts ...option.RequestOption) (*AMBBusinessAccountEventList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListAMBBusinessAccountEvents(ctx, oapi.AMBBusinessID(businessAccountId), params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBBusinessAccountEventList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List Returns account activity with event time, summary and source metadata, newest first by default.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *AmbBusinessAccountsEventsService) List(ctx context.Context, businessAccountId string, params AmbBusinessAccountsEventsListParams, opts ...option.RequestOption) iter.Seq2[*AMBBusinessAccountEvent, error] {
	return paginate(func(cursor string) ([]AMBBusinessAccountEvent, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, businessAccountId, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}
