// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type AMBConversationTypingEvent = oapi.AMBConversationTypingEvent

type ConversationInboxStatus = oapi.ConversationInboxStatus

// AmbConversationsUpdateParams is the request body for update.
type AmbConversationsUpdateParams struct {
	// User to assign this conversation to. Pass a workspace member's user ID, `me` for the signed-in user, or null to unassign it. An API key cannot use `me` and receives a `422` response.
	AssignedTo Nullable[string]
	// Whether the conversation needs attention in the workspace inbox. Set it to `resolved` when the work is finished. A new inbound message reopens the same conversation. Changing inbox status preserves message history and does not change the channel's permission to send messages or mark messages read.
	InboxStatus *ConversationInboxStatus
	// Labels chosen by your workspace. On update, this replaces the full set; pass an empty array to clear every label. Labels do not change read state or inbox status. Each label must contain 1 to 64 characters, with no commas, control characters, or leading or trailing whitespace. Duplicate labels are rejected. The names `all`, `archived`, `assigned`, `closed`, `deleted`, `draft`, `drafts`, `flagged`, `important`, `inbox`, `junk`, `muted`, `none`, `open`, `pinned`, `read`, `snoozed`, `spam`, `starred`, `trash`, and `unread` are reserved in every casing.
	Labels []string
	// Mark received inbound messages with created_at at or before this timestamp as read in the shared workspace inbox. Messages sharing the timestamp are included together. Later arrivals remain unread until another read update. This does not send a read receipt to the customer or change inbox status. Omit to leave read state unchanged.
	Read time.Time
}

func (p AmbConversationsUpdateParams) toWire() oapi.AMBConversationUpdate {
	body := oapi.AMBConversationUpdate{}
	body.AssignedTo = p.AssignedTo
	if p.InboxStatus != nil {
		body.InboxStatus = p.InboxStatus
	}
	if p.Labels != nil {
		v := p.Labels
		body.Labels = &v
	}
	body.Read = optTime(p.Read)
	return body
}

// AmbConversationsListMessagesParams filters the list. Zero-value fields are omitted.
type AmbConversationsListMessagesParams struct {
	// Filter to received (`inbound`) or sent (`outbound`) messages.
	Direction AMBMessageDirection
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p AmbConversationsListMessagesParams) toWire(startingAfter string) *oapi.ListAMBConversationMessagesParams {
	return &oapi.ListAMBConversationMessagesParams{
		Direction:     optZero(p.Direction),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		StartingAfter: optStr(startingAfter),
	}
}

// AmbConversationsTypingParams is the request body for typing.
type AmbConversationsTypingParams struct {
	// The typing signal to send. `typing_start` tells the customer's device that an operator is composing a reply. `typing_end` tells it composition stopped without a message following. Apple expects at most one `typing_start` before the reply it precedes; sending it again before that reply is not meaningful and may be dropped. `typing_end`'s behavior against a live conversation is unproven: the legacy platform's implementation was disabled after it caused issues, so treat it as best-effort.
	Event AMBConversationTypingEvent
}

func (p AmbConversationsTypingParams) toWire() oapi.AMBConversationTypingRequest {
	body := oapi.AMBConversationTypingRequest{}
	body.Event = p.Event
	return body
}

// Get Reads a customer-initiated conversation in your workspace. Its recipient.opaque_user_id supplies the to field for replies; verify the business and open state before sending.
func (s *AmbConversationsService) Get(ctx context.Context, conversationId string, opts ...option.RequestOption) (*AMBConversation, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetAMBConversation(ctx, oapi.AMBConversationID(conversationId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBConversation
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Updates assignment, labels, inbox status and shared workspace read state. Omitted fields stay unchanged; null assigned_to unassigns and empty labels clears labels. Pass read as a date-time to acknowledge received inbound messages through that timestamp. Resolving or reopening inbox work preserves the Apple channel state and sending restrictions.
func (s *AmbConversationsService) Update(ctx context.Context, conversationId string, params AmbConversationsUpdateParams, opts ...option.RequestOption) (*AMBConversation, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UpdateAMBConversationParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateAMBConversation(ctx, oapi.AMBConversationID(conversationId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBConversation
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMessagesPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *AmbConversationsService) ListMessagesPage(ctx context.Context, conversationId string, params AmbConversationsListMessagesParams, startingAfter string, opts ...option.RequestOption) (*AMBMessageList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListAMBConversationMessages(ctx, oapi.AMBConversationID(conversationId), params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBMessageList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMessages Returns the messages in a conversation, newest first, both received and sent. To page through older messages, use `starting_after`. The sort order is fixed, so to render the messages in conversation order, reverse the page yourself.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *AmbConversationsService) ListMessages(ctx context.Context, conversationId string, params AmbConversationsListMessagesParams, opts ...option.RequestOption) iter.Seq2[*AMBMessage, error] {
	return paginate(func(cursor string) ([]AMBMessage, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListMessagesPage(ctx, conversationId, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Typing Sends a typing signal through Apple for an existing conversation. Typing is best effort; typing_end still needs native device verification. It does not enqueue a billable message.
func (s *AmbConversationsService) Typing(ctx context.Context, conversationId string, params AmbConversationsTypingParams, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateAMBConversationTypingParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateAMBConversationTyping(ctx, oapi.AMBConversationID(conversationId), op, params.toWire(), cfg...)
	})
	return err
}
