// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// AmbRoutingRulesListParams filters the list read.
type AmbRoutingRulesListParams struct {
	// Keep only routing rules belonging to this business. Omit to return rules across all businesses in the workspace.
	BusinessAccountID string
}

func (p AmbRoutingRulesListParams) toWire() *oapi.ListAMBRoutingRulesParams {
	return &oapi.ListAMBRoutingRulesParams{
		BusinessAccountId: optZero(p.BusinessAccountID),
	}
}

// Get Returns one routing rule by ID.
func (s *AmbRoutingRulesService) Get(ctx context.Context, routingRuleId string, opts ...option.RequestOption) (*AMBRoutingRule, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetAMBRoutingRule(ctx, oapi.AMBRoutingRuleID(routingRuleId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBRoutingRule
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Deletes a routing rule. A conversation already routed by it keeps its queue; only newly created or reopened conversations stop matching it. Deleting a business's default rule leaves it with none, so unmatched conversations route to an empty queue until you create another.
func (s *AmbRoutingRulesService) Delete(ctx context.Context, routingRuleId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteAMBRoutingRuleParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteAMBRoutingRule(ctx, oapi.AMBRoutingRuleID(routingRuleId), op, cfg...)
	})
	return err
}

// List Returns the workspace's Apple Messages for Business routing rules, highest precedence first. Rules automatically run when a conversation is created or reopened, matching the group and intent from its entry point to a queue. Messages within an open conversation retain its queue. Rule changes affect only conversations that start or reopen afterwards.
func (s *AmbRoutingRulesService) List(ctx context.Context, params AmbRoutingRulesListParams, opts ...option.RequestOption) (*AMBRoutingRuleList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListAMBRoutingRules(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBRoutingRuleList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
