// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// AmbStatsConversationsDailyParams filters the daily read.
type AmbStatsConversationsDailyParams struct {
	// Start date (inclusive), YYYY-MM-DD. Interpreted as a calendar day in `timezone` (a UTC day when `timezone` is omitted). The window may not exceed 365 days. Defaults to 30 days before `to` when omitted.
	From time.Time
	// End date (inclusive), YYYY-MM-DD. Interpreted as a calendar day in `timezone` (a UTC day when `timezone` is omitted). The window may not exceed 365 days. Defaults to today in that timezone when omitted.
	To time.Time
	// IANA timezone identifier used to group statistics, for example `Asia/Kathmandu`. The default is UTC. Day and hour boundaries, including the default window when `from` and `to` are omitted, follow this timezone. When this parameter is set, pass `from` and `to` as calendar days or `Z` instants instead of timestamps with explicit UTC offsets.
	Timezone string
}

func (p AmbStatsConversationsDailyParams) toWire() *oapi.GetAMBConversationStatsDailyParams {
	return &oapi.GetAMBConversationStatsDailyParams{
		From:     optDate(p.From),
		To:       optDate(p.To),
		Timezone: optStr(p.Timezone),
	}
}

// AmbStatsConversationsHourlyParams filters the hourly read.
type AmbStatsConversationsHourlyParams struct {
	// Start of the window (RFC 3339 instant), rounded down to the start of its hour and included. The boundary uses the local hour when `timezone` is set and the UTC hour otherwise. The window may not exceed 30 days (720 hours). Defaults to 168 hours (7 days) before `to` when omitted.
	From time.Time
	// End of the window (RFC 3339 instant), rounded down to the start of its hour and included. The boundary uses the local hour when `timezone` is set and the UTC hour otherwise, so both bounds are inclusive. The window may not exceed 30 days (720 hours). Defaults to the current hour when omitted.
	To time.Time
	// IANA timezone identifier used to group statistics, for example `Asia/Kathmandu`. The default is UTC. Day and hour boundaries, including the default window when `from` and `to` are omitted, follow this timezone. When this parameter is set, pass `from` and `to` as calendar days or `Z` instants instead of timestamps with explicit UTC offsets.
	Timezone string
}

func (p AmbStatsConversationsHourlyParams) toWire() *oapi.GetAMBConversationStatsHourlyParams {
	return &oapi.GetAMBConversationStatsHourlyParams{
		From:     optTime(p.From),
		To:       optTime(p.To),
		Timezone: optStr(p.Timezone),
	}
}

// AmbStatsConversationsSummaryParams filters the summary read.
type AmbStatsConversationsSummaryParams struct {
	// Inclusive start of the window: a calendar day (YYYY-MM-DD) or an RFC 3339 instant rounded down to the hour. The `timezone` parameter makes a calendar day local and rounds an instant down to the local hour. Omit `timezone` to use UTC. When `timezone` is set, a numeric UTC offset such as `+05:45` is rejected; use a calendar day or a `Z` (UTC) instant. This value must use the same form as `to`. When omitted, it defaults to 30 days before `to` for day windows or 168 hours (7 days) before `to` for hour windows.
	From string
	// Inclusive end of the window: a calendar day (YYYY-MM-DD) or an RFC 3339 instant rounded down to the hour. The `timezone` parameter makes a calendar day local and rounds an instant down to the local hour. Omit `timezone` to use UTC. When `timezone` is set, a numeric UTC offset is rejected; use a calendar day or a `Z` (UTC) instant. This value must use the same form as `from`. When omitted, it defaults to today for day windows or the current hour for hour windows in that timezone. Day windows may not exceed 365 days; hour windows may not exceed 720 hours (30 days).
	To string
	// IANA timezone identifier used to group statistics, for example `Asia/Kathmandu`. The default is UTC. Day and hour boundaries, including the default window when `from` and `to` are omitted, follow this timezone. When this parameter is set, pass `from` and `to` as calendar days or `Z` instants instead of timestamps with explicit UTC offsets.
	Timezone string
	// Set to `previous_period` to also include the same statistics for the immediately preceding window of equal length, plus the change between the two, so you can show "+X% vs last period" without a second request.
	Compare StatsComparePeriod
}

func (p AmbStatsConversationsSummaryParams) toWire() *oapi.GetAMBConversationStatsSummaryParams {
	return &oapi.GetAMBConversationStatsSummaryParams{
		From:     optStr(p.From),
		To:       optStr(p.To),
		Timezone: optStr(p.Timezone),
		Compare:  optZero(p.Compare),
	}
}

// Daily Returns one row of Apple Messages for Business conversation lifecycle counts (`started`, `reopened`, `closed`, `conversations`) per calendar day for the workspace, gap-filled so a silent day is a zero row rather than a missing one. Every row is attributed to the day the lifecycle event occurred, not to any earlier outbound message. A conversation can be reopened and closed more than once, so `started`, `reopened`, and `closed` need not sum to `conversations` within a row, and any one of them can exceed it.
func (s *AmbStatsConversationsService) Daily(ctx context.Context, params AmbStatsConversationsDailyParams, opts ...option.RequestOption) (*AMBConversationStatsResponse, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetAMBConversationStatsDaily(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBConversationStatsResponse
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Hourly Returns one row of Apple Messages for Business conversation lifecycle counts (`started`, `reopened`, `closed`, `conversations`) per hour, gap-filled so a silent hour is a zero row rather than a missing one. Every row is attributed to the hour the lifecycle event occurred, not to any earlier outbound message. A conversation can be reopened and closed more than once, so `started`, `reopened`, and `closed` need not sum to `conversations` within a row, and any one of them can exceed it.
func (s *AmbStatsConversationsService) Hourly(ctx context.Context, params AmbStatsConversationsHourlyParams, opts ...option.RequestOption) (*AMBConversationStatsResponse, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetAMBConversationStatsHourly(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBConversationStatsResponse
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Summary Returns one aggregate row of Apple Messages for Business conversation lifecycle counts (`started`, `reopened`, `closed`, `conversations`) for the requested period. Rows are attributed to when the lifecycle event occurred, not to any earlier outbound message. A conversation can be reopened and closed more than once, so `started`, `reopened`, and `closed` need not sum to `conversations`, and any one of them can exceed it. `period.data_as_of` is the freshness boundary the rollups have reached.
func (s *AmbStatsConversationsService) Summary(ctx context.Context, params AmbStatsConversationsSummaryParams, opts ...option.RequestOption) (*AMBConversationStatsSummary, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetAMBConversationStatsSummary(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AMBConversationStatsSummary
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
