// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type AudienceCreateRequestType = oapi.AudienceCreateRequestType

// AudienceListParams filters the list. Zero-value fields are omitted.
type AudienceListParams struct {
	// Case-insensitive substring match against the audience's name.
	Q string
	// Maximum number of items to return per page.
	Limit int
}

func (p AudienceListParams) toWire(startingAfter string) *oapi.ListAudiencesParams {
	return &oapi.ListAudiencesParams{
		Q:             optStr(p.Q),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// AudienceCreateParams is the request body for create.
type AudienceCreateParams struct {
	// Display name for the audience.
	Name string
	// Longer description of who this audience is.
	Description string
	// How the audience's recipients are determined. `static` (the default) is an explicit member list you manage via the API. `dynamic` and `external` are preview values and currently unavailable; creating an audience with either returns a validation error.
	Type *AudienceCreateRequestType
}

func (p AudienceCreateParams) toWire() oapi.AudienceCreateRequest {
	body := oapi.AudienceCreateRequest{}
	body.Name = p.Name
	if p.Description != "" {
		body.Description = Ptr(p.Description)
	}
	if p.Type != nil {
		body.Type = p.Type
	}
	return body
}

// AudienceUpdateParams is the request body for update.
type AudienceUpdateParams struct {
	// New display name for the audience. Omit to keep the current name; the name cannot be cleared, and a whitespace-only value returns a validation error.
	Name string
	// Longer description of who this audience is. Set to null to clear.
	Description Nullable[string]
}

func (p AudienceUpdateParams) toWire() oapi.AudienceUpdateRequest {
	body := oapi.AudienceUpdateRequest{}
	if p.Name != "" {
		body.Name = Ptr(p.Name)
	}
	body.Description = p.Description
	return body
}

// AudienceListContactsParams filters the list. Zero-value fields are omitted.
type AudienceListContactsParams struct {
	// Case-insensitive substring match against the member's email address.
	Q string
	// Maximum number of items to return per page.
	Limit int
}

func (p AudienceListContactsParams) toWire(startingAfter string) *oapi.ListAudienceContactsParams {
	return &oapi.ListAudienceContactsParams{
		Q:             optStr(p.Q),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// AudienceAddContactsParams is the request body for add_contacts.
type AudienceAddContactsParams struct {
	// Contacts to add to the audience. Adding a contact that is already a member has no effect and keeps its original join time; duplicate IDs in the list are collapsed. If any ID does not exist in the workspace, the whole request fails with a validation error and no contacts are added.
	ContactIDs []string
}

func (p AudienceAddContactsParams) toWire() oapi.AudienceContactsAddRequest {
	body := oapi.AudienceContactsAddRequest{}
	contactIds := make([]oapi.ContactID, len(p.ContactIDs))
	for i, v := range p.ContactIDs {
		contactIds[i] = oapi.ContactID(v)
	}
	body.ContactIds = contactIds
	return body
}

// AudienceRemoveContactsParams is the request body for remove_contacts.
type AudienceRemoveContactsParams struct {
	// Contacts to remove from the audience. Removing a contact that is not a member has no effect; duplicate IDs in the list are collapsed. If any ID does not exist in the workspace, the whole request fails with a validation error and no memberships are removed.
	ContactIDs []string
}

func (p AudienceRemoveContactsParams) toWire() oapi.AudienceContactsRemoveRequest {
	body := oapi.AudienceContactsRemoveRequest{}
	contactIds := make([]oapi.ContactID, len(p.ContactIDs))
	for i, v := range p.ContactIDs {
		contactIds[i] = oapi.ContactID(v)
	}
	body.ContactIds = contactIds
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *AudiencesService) ListPage(ctx context.Context, params AudienceListParams, startingAfter string, opts ...option.RequestOption) (*AudienceList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListAudiences(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AudienceList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's audiences as a cursor page, newest first. Filter by name substring with `q`.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *AudiencesService) List(ctx context.Context, params AudienceListParams, opts ...option.RequestOption) iter.Seq2[*Audience, error] {
	return paginate(func(cursor string) ([]Audience, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Get a single audience by ID: name, description, and type. Members are listed separately with `audiences.list_contacts`.
func (s *AudiencesService) Get(ctx context.Context, audienceId string, opts ...option.RequestOption) (*Audience, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetAudience(ctx, oapi.AudienceID(audienceId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Audience
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create Create an audience in the workspace. New audiences start empty; add contacts with `audiences.add_contacts` or `contacts.batch`. Only static audiences can be created today.
func (s *AudiencesService) Create(ctx context.Context, params AudienceCreateParams, opts ...option.RequestOption) (*Audience, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateAudienceParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateAudience(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Audience
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Update an audience's name or description. Omitted fields are unchanged; a null description clears it.
func (s *AudiencesService) Update(ctx context.Context, audienceId string, params AudienceUpdateParams, opts ...option.RequestOption) (*Audience, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UpdateAudienceParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateAudience(ctx, oapi.AudienceID(audienceId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Audience
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Delete an audience and its memberships; contacts themselves are not deleted. Fails while a broadcast targeting the audience is scheduled, accepted, sending, or canceling.
func (s *AudiencesService) Delete(ctx context.Context, audienceId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteAudienceParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteAudience(ctx, oapi.AudienceID(audienceId), op, cfg...)
	})
	return err
}

// ListContactsPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *AudiencesService) ListContactsPage(ctx context.Context, audienceId string, params AudienceListContactsParams, startingAfter string, opts ...option.RequestOption) (*AudienceMemberList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListAudienceContacts(ctx, oapi.AudienceID(audienceId), params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AudienceMemberList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListContacts List the contacts in a static audience by ID, as a cursor page ordered by when each contact joined (most recent first). Each entry pairs the contact with its join time.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *AudiencesService) ListContacts(ctx context.Context, audienceId string, params AudienceListContactsParams, opts ...option.RequestOption) iter.Seq2[*AudienceMember, error] {
	return paginate(func(cursor string) ([]AudienceMember, *string, error) {
		page, err := s.ListContactsPage(ctx, audienceId, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// AddContacts Add up to 1,000 existing contacts to a static audience by ID. Fails entirely if any contact ID does not exist.
func (s *AudiencesService) AddContacts(ctx context.Context, audienceId string, params AudienceAddContactsParams, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.AssignAudienceContactsParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.AssignAudienceContacts(ctx, oapi.AudienceID(audienceId), op, params.toWire(), cfg...)
	})
	return err
}

// RemoveContacts Remove up to 1,000 contacts from a static audience by ID. Fails entirely if any contact ID does not exist; contacts are not deleted.
func (s *AudiencesService) RemoveContacts(ctx context.Context, audienceId string, params AudienceRemoveContactsParams, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UnassignAudienceContactsParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UnassignAudienceContacts(ctx, oapi.AudienceID(audienceId), op, params.toWire(), cfg...)
	})
	return err
}

// RemoveContact Remove one contact's membership from an audience. The contact itself is not deleted and stays a member of any other audiences.
func (s *AudiencesService) RemoveContact(ctx context.Context, audienceId string, contactId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UnassignAudienceContactParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UnassignAudienceContact(ctx, oapi.AudienceID(audienceId), oapi.ContactID(contactId), op, cfg...)
	})
	return err
}
