// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type ContactPropertyType = oapi.ContactPropertyType

// ContactPropertyListParams filters the list. Zero-value fields are omitted.
type ContactPropertyListParams struct {
	// Maximum number of items to return per page.
	Limit int
}

func (p ContactPropertyListParams) toWire(startingAfter string) *oapi.ListContactPropertiesParams {
	return &oapi.ListContactPropertiesParams{
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// ContactPropertyCreateParams is the request body for create.
type ContactPropertyCreateParams struct {
	// The property key, used as the key in contact data and as the template variable name in broadcasts. Lowercase letters, digits, and underscores, starting with a letter. Cannot be changed after creation.
	Key string
	// The value type every contact must use for a property. Cannot be changed after creation. `datetime` values are RFC 3339 timestamps with an explicit offset (for example `2024-01-15T09:30:00Z` or `2024-01-15T11:30:00+02:00`); a bare date or a time with no offset is rejected. The value is normalized to UTC with second precision on write, so `2024-01-15T11:30:00+02:00` is stored and returned as `2024-01-15T09:30:00Z`, and any fractional seconds are dropped.
	Type ContactPropertyType
	// Default used when a contact has no value for this property and the template does not supply an inline fallback. A string, number, boolean, or RFC 3339 datetime matching the declared type (strings up to 500 characters), or null for no fallback; a value of another type returns a validation error.
	FallbackValue any
}

func (p ContactPropertyCreateParams) toWire() oapi.ContactPropertyCreateRequest {
	body := oapi.ContactPropertyCreateRequest{}
	body.Key = p.Key
	body.Type = p.Type
	if p.FallbackValue != nil {
		body.FallbackValue = p.FallbackValue
	}
	return body
}

// ContactPropertyUpdateParams is the request body for update.
type ContactPropertyUpdateParams struct {
	// Default used when a contact has no value for this property and the template does not supply an inline fallback. A string, number, boolean, or RFC 3339 datetime matching the declared type (strings up to 500 characters); a value of another type returns a validation error. Set to null to remove the fallback.
	FallbackValue any
}

func (p ContactPropertyUpdateParams) toWire() oapi.ContactPropertyUpdateRequest {
	body := oapi.ContactPropertyUpdateRequest{}
	if p.FallbackValue != nil {
		body.FallbackValue = p.FallbackValue
	}
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *ContactPropertiesService) ListPage(ctx context.Context, params ContactPropertyListParams, startingAfter string, opts ...option.RequestOption) (*ContactPropertyList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListContactProperties(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out ContactPropertyList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's contact properties as a cursor page, newest first. Archived properties are included, marked by their archived flag.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *ContactPropertiesService) List(ctx context.Context, params ContactPropertyListParams, opts ...option.RequestOption) iter.Seq2[*ContactProperty, error] {
	return paginate(func(cursor string) ([]ContactProperty, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Get a single contact property by ID: key, type, fallback value, and archived state.
func (s *ContactPropertiesService) Get(ctx context.Context, propertyId string, opts ...option.RequestOption) (*ContactProperty, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetContactProperty(ctx, oapi.ContactPropertyID(propertyId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out ContactProperty
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create Define a custom contact property (key + value type) that becomes available in contact data and as a broadcast template variable. The key and type cannot change after creation; a workspace holds at most 200 properties, archived included.
func (s *ContactPropertiesService) Create(ctx context.Context, params ContactPropertyCreateParams, opts ...option.RequestOption) (*ContactProperty, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateContactPropertyParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateContactProperty(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out ContactProperty
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Update a contact property's fallback value. Only the fallback value can change; the key and type are fixed at creation, so a different key or type needs a new property.
func (s *ContactPropertiesService) Update(ctx context.Context, propertyId string, params ContactPropertyUpdateParams, opts ...option.RequestOption) (*ContactProperty, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UpdateContactPropertyParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateContactProperty(ctx, oapi.ContactPropertyID(propertyId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out ContactProperty
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Archive Archive a contact property: the key is rejected in new contact writes and stops rendering in templates, while stored values remain readable. The key stays reserved and counts toward the 200-property limit; reverse with `contact_properties.unarchive`.
func (s *ContactPropertiesService) Archive(ctx context.Context, propertyId string, opts ...option.RequestOption) (*ContactProperty, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.ArchiveContactPropertyParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.ArchiveContactProperty(ctx, oapi.ContactPropertyID(propertyId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out ContactProperty
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Unarchive Reactivate an archived contact property so its key is accepted in contact writes and renders in templates again. Fails with a conflict if the property is not archived.
func (s *ContactPropertiesService) Unarchive(ctx context.Context, propertyId string, opts ...option.RequestOption) (*ContactProperty, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UnarchiveContactPropertyParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UnarchiveContactProperty(ctx, oapi.ContactPropertyID(propertyId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out ContactProperty
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
