// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// ContactsPreferencesListParams filters the list. Zero-value fields are omitted.
type ContactsPreferencesListParams struct {
	// Maximum number of items to return per page.
	Limit int
}

func (p ContactsPreferencesListParams) toWire(startingAfter string) *oapi.ListContactPreferencesParams {
	return &oapi.ListContactPreferencesParams{
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *ContactsPreferencesService) ListPage(ctx context.Context, contactId string, params ContactsPreferencesListParams, startingAfter string, opts ...option.RequestOption) (*PreferenceList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListContactPreferences(ctx, oapi.ContactID(contactId), params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out PreferenceList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the recorded messaging preferences for a contact's own handles (their email address and phone number) across every channel, as a cursor page.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *ContactsPreferencesService) List(ctx context.Context, contactId string, params ContactsPreferencesListParams, opts ...option.RequestOption) iter.Seq2[*Preference, error] {
	return paginate(func(cursor string) ([]Preference, *string, error) {
		page, err := s.ListPage(ctx, contactId, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}
