// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type DomainDKIMConfig = oapi.DomainDKIMConfig

type DomainInboundConfig = oapi.DomainInboundConfig

type DomainReturnPathConfig = oapi.DomainReturnPathConfig

type DomainSettings = oapi.DomainSettings

type DomainTrackingConfig = oapi.DomainTrackingConfig

type DomainDKIMConfigMode = oapi.DomainDKIMConfigMode

const (
	DomainDKIMConfigModeTxt       DomainDKIMConfigMode = "txt"
	DomainDKIMConfigModeDelegated DomainDKIMConfigMode = "delegated"
)

// DomainListParams filters the list. Zero-value fields are omitted.
type DomainListParams struct {
	// Substring match against the domain name (case-insensitive).
	Name string
	// Field to sort by. Defaults to `created_at`.
	Sort string
	// Sort direction. Defaults to `desc`, which sorts from newest to oldest or largest to smallest, depending on the selected sort field.
	Order string
	// Maximum number of items to return per page.
	Limit int
	// When true, the response includes a `total` field with the total number of items matching the request's filters across all pages.
	IncludeTotal bool
}

func (p DomainListParams) toWire(startingAfter string) *oapi.ListDomainsParams {
	return &oapi.ListDomainsParams{
		Name:          optStr(p.Name),
		Sort:          optEnum[oapi.ListDomainsParamsSort](p.Sort),
		Order:         optEnum[oapi.ListDomainsParamsOrder](p.Order),
		Limit:         optInt(p.Limit),
		IncludeTotal:  optBool(p.IncludeTotal),
		StartingAfter: optStr(startingAfter),
	}
}

// DomainCreateParams is the request body for create.
type DomainCreateParams struct {
	// The domain you send from: the domain of your `from` addresses. Use a dedicated subdomain (for example, `mail.acme.com`) rather than your registered domain so sending reputation stays separate from other services on the domain.
	Domain string
	// Return-path (bounce) domain configuration. The return-path domain receives bounce and complaint notifications for mail sent from this domain and is what mailbox providers check for SPF. Provide only the name part; we add the sending domain automatically.
	ReturnPath *DomainReturnPathConfig
	// Tracking domain configuration for branded open and click tracking URLs. Provide only the name part; we add the sending domain automatically. A domain created with no tracking configuration defaults to `links`. Tracked links are served over HTTPS after the tracking record verifies.
	Tracking *DomainTrackingConfig
	// DKIM signing configuration.
	Dkim *DomainDKIMConfig
	// Per-domain behavior toggles. Changes apply immediately to new sends.
	Settings *DomainSettings
}

func (p DomainCreateParams) toWire() oapi.DomainCreate {
	body := oapi.DomainCreate{}
	body.Domain = p.Domain
	if p.ReturnPath != nil {
		body.ReturnPath = p.ReturnPath
	}
	if p.Tracking != nil {
		body.Tracking = p.Tracking
	}
	if p.Dkim != nil {
		body.Dkim = p.Dkim
	}
	if p.Settings != nil {
		body.Settings = p.Settings
	}
	return body
}

// DomainUpdateParams is the request body for update.
type DomainUpdateParams struct {
	// Per-domain behavior toggles. Changes apply immediately to new sends.
	Settings *DomainSettings
	// Change the return-path name part. Cannot be removed: the return-path is required for sending.
	ReturnPath *DomainReturnPathConfig
	// Set or change the tracking name part, or remove tracking by passing `null`. Removal requires `click_tracking` and `open_tracking` to be disabled first, and returns `409` otherwise. After removal, links in previously sent email keep resolving while the tracking records are reported as `deprecated`.
	Tracking Nullable[DomainTrackingConfig]
	// Change how the DKIM key is published. The current key keeps signing until the new configuration verifies, so mail is never sent unsigned during the transition.
	Dkim *DomainDKIMConfig
	// Enable or disable receiving on this domain. Enabling claims the domain for inbound and moves `capabilities.inbound.status` from `not_configured` to `pending`, then `verified` once the MX records resolve to us. The MX records to publish are always present under `dns_records` (`purpose: inbound_mx`) as a regional reference. Their presence does not mean receiving is enabled; enable the domain whenever `capabilities.inbound.status` is `not_configured`. Enabling requires the domain's DKIM to be verified first. A fresh enable on a domain whose DKIM is not verified returns `422` with `E05019` and claims nothing. A domain already receiving inbound for another organization returns `422` with `E05018`.
	Inbound *DomainInboundConfig
}

func (p DomainUpdateParams) toWire() oapi.DomainUpdate {
	body := oapi.DomainUpdate{}
	if p.Settings != nil {
		body.Settings = p.Settings
	}
	if p.ReturnPath != nil {
		body.ReturnPath = p.ReturnPath
	}
	body.Tracking = p.Tracking
	if p.Dkim != nil {
		body.Dkim = p.Dkim
	}
	if p.Inbound != nil {
		body.Inbound = p.Inbound
	}
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *DomainsService) ListPage(ctx context.Context, params DomainListParams, startingAfter string, opts ...option.RequestOption) (*DomainList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListDomains(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out DomainList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's sending domains with their verification status, as a cursor page.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *DomainsService) List(ctx context.Context, params DomainListParams, opts ...option.RequestOption) iter.Seq2[*Domain, error] {
	return paginate(func(cursor string) ([]Domain, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Fetch one sending domain: verification status and the DNS records with their individual verification states.
func (s *DomainsService) Get(ctx context.Context, domainId string, opts ...option.RequestOption) (*Domain, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetDomain(ctx, oapi.DomainID(domainId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Domain
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create Register a new sending domain and get the DNS records to publish. Verification is a second step: the records go live at the DNS provider, then email_domains_verify confirms them. Propagation takes minutes to hours, so the first verify often still reports unverified and a later one succeeds.
func (s *DomainsService) Create(ctx context.Context, params DomainCreateParams, opts ...option.RequestOption) (*Domain, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateDomainParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateDomain(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Domain
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Verify Trigger a DNS verification check for a sending domain and return the refreshed domain with per-record results. Safe to repeat while waiting for DNS propagation.
func (s *DomainsService) Verify(ctx context.Context, domainId string, opts ...option.RequestOption) (*Domain, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.VerifyDomainParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.VerifyDomain(ctx, oapi.DomainID(domainId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Domain
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Update a sending domain's tracking and inbound configuration. Tracking: click_tracking and open_tracking apply immediately to new sends, and the tracking domain can be set, changed, or removed (the name part only, and the sending domain is appended for you). Enabling either toggle with no tracking domain configured returns 409, and removing the tracking domain while either toggle is still on also returns 409. Tracking-domain changes on a verified domain are staged behind DNS verification, so the current config keeps serving until the new records verify. Inbound receiving: inbound.enabled starts or stops receiving mail for the domain. Enabling requires the domain's DKIM to be verified first (a fresh enable on an unverified domain returns 422), and a domain already receiving inbound for another organization returns 422. The MX records to publish are always listed in dns_records regardless, so receiving starts only once inbound.enabled is set, even when those records are already published.
func (s *DomainsService) Update(ctx context.Context, domainId string, params DomainUpdateParams, opts ...option.RequestOption) (*Domain, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UpdateDomainParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateDomain(ctx, oapi.DomainID(domainId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Domain
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Delete a sending domain by ID. Revokes its sender authorization: new sends from the domain are rejected afterward, while historical statistics and events for past sends are preserved. Destructive.
func (s *DomainsService) Delete(ctx context.Context, domainId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteDomainParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteDomain(ctx, oapi.DomainID(domainId), op, cfg...)
	})
	return err
}
