// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EmailCompetitiveBrandsSearchParams filters the search read.
type EmailCompetitiveBrandsSearchParams struct {
	// A brand name, or a sending domain to look up the brand behind it.
	Q string
}

func (p EmailCompetitiveBrandsSearchParams) toWire() *oapi.SearchEmailCompetitiveBrandsParams {
	return &oapi.SearchEmailCompetitiveBrandsParams{
		Q: p.Q,
	}
}

// Search Find a competitor by brand name or sending domain without adding it. For existing competitors, `email.competitive.watchlist.get` already returns names, tracked domains and watchlist IDs. Search returns at most eight matches, each with its highest-volume sending domain, not every domain a brand uses. Resolve ambiguous names against the intended domain before any authorized addition. An empty or limited result describes this search, not exhaustive panel coverage. The returned panel `brand_id` differs from a saved `watchlist_brand_id`. API-key calls require Insights preview access for your organization.
func (s *EmailCompetitiveBrandsService) Search(ctx context.Context, params EmailCompetitiveBrandsSearchParams, opts ...option.RequestOption) (*EmailCompetitiveBrandSearchResults, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.SearchEmailCompetitiveBrands(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailCompetitiveBrandSearchResults
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
