// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"fmt"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EmailInboxInsightsDomainsListParams filters the list. Zero-value fields are omitted.
type EmailInboxInsightsDomainsListParams struct {
	// Exact sending domain to return. Matching is case-insensitive.
	SendingDomain string
	// Substring match against the sending domain (case-insensitive).
	Search string
	// Field to sort by. Defaults to `domain`.
	Sort EmailInboxInsightsDomainSort
	// Sort direction. Defaults to `asc`, which sorts alphabetically or from oldest to newest, depending on the selected sort field.
	Order SortOrder
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p EmailInboxInsightsDomainsListParams) toWire(startingAfter string) *oapi.GetEmailInboxInsightsDomainsParams {
	return &oapi.GetEmailInboxInsightsDomainsParams{
		SendingDomain: optStr(p.SendingDomain),
		Search:        optStr(p.Search),
		Sort:          optZero(p.Sort),
		Order:         optZero(p.Order),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		StartingAfter: optStr(startingAfter),
	}
}

// EmailInboxInsightsDomainsUpdateParams is the request body for update.
type EmailInboxInsightsDomainsUpdateParams struct {
	// Whether the workspace wants this domain monitored. Enabling enrolls it with eDataSource; disabling removes only the workspace preference and preserves vendor enrollment and measurement history. Verified ownership governs report access.
	Monitored *bool
}

func (p EmailInboxInsightsDomainsUpdateParams) toWire() oapi.EmailInboxInsightsDomainUpdate {
	body := oapi.EmailInboxInsightsDomainUpdate{}
	body.Monitored = *p.Monitored
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *EmailInboxInsightsDomainsService) ListPage(ctx context.Context, params EmailInboxInsightsDomainsListParams, startingAfter string, opts ...option.RequestOption) (*EmailInboxInsightsDomains, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailInboxInsightsDomains(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailInboxInsightsDomains
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List verified sending domains owned by the workspace and their monitoring settings. Follow next_cursor with starting_after, keeping filters and ordering. A monitored value records the workspace setting; it does not establish that vendor measurements exist. API-key calls require Insights preview access for your organization.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *EmailInboxInsightsDomainsService) List(ctx context.Context, params EmailInboxInsightsDomainsListParams, opts ...option.RequestOption) iter.Seq2[*EmailInboxInsightsDomain, error] {
	return paginate(func(cursor string) ([]EmailInboxInsightsDomain, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		if page.Data == nil {
			return nil, page.NextCursor, nil
		}
		return *page.Data, page.NextCursor, nil
	})
}

// Update Set monitored explicitly to true or false for a verified domain owned by the workspace. Enabling enrolls the domain with eDataSource and saves the workspace preference. Disabling removes only that preference; vendor enrollment and measurement history remain. Reports still require verified ownership and are not gated by this preference. Repeating the same value is safe. Reuse an idempotency key when retrying the same change. API-key and service-account calls require Insights preview access for your organization.
func (s *EmailInboxInsightsDomainsService) Update(ctx context.Context, sendingDomain string, params EmailInboxInsightsDomainsUpdateParams, opts ...option.RequestOption) (*EmailInboxInsightsDomain, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		if params.Monitored == nil {
			return nil, fmt.Errorf("bird: monitored is required")
		}
		op := &oapi.UpdateEmailInboxInsightsDomainParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateEmailInboxInsightsDomain(ctx, sendingDomain, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailInboxInsightsDomain
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
