// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	openapi_types "github.com/oapi-codegen/runtime/types"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type MailboxCreateReceivePolicy = oapi.MailboxCreateReceivePolicy

type MailboxCreateRetentionTier = oapi.MailboxCreateRetentionTier

type MailboxUpdateReceivePolicy = oapi.MailboxUpdateReceivePolicy

type MailboxUpdateRetentionTier = oapi.MailboxUpdateRetentionTier

// EmailMailboxesListParams filters the list. Zero-value fields are omitted.
type EmailMailboxesListParams struct {
	// Filter to the mailbox with exactly this address.
	Address string
	// Case-insensitive search matching the mailbox's address or display name (substring).
	Q string
	// Filter by lifecycle state.
	State string
	// Filter to mailboxes whose address is on this domain.
	Domain string
	// Include mailboxes deleted within their 30-day restore window. Defaults to false, so only active and suspended mailboxes are returned. A deleted mailbox has a non-null `deleted_at`.
	IncludeDeleted bool
	// Maximum number of items to return per page.
	Limit int
}

func (p EmailMailboxesListParams) toWire(startingAfter string) *oapi.ListMailboxesParams {
	return &oapi.ListMailboxesParams{
		Address:        optEmail(p.Address),
		Q:              optStr(p.Q),
		State:          optEnum[oapi.ListMailboxesParamsState](p.State),
		Domain:         optStr(p.Domain),
		IncludeDeleted: optBool(p.IncludeDeleted),
		Limit:          optInt(p.Limit),
		StartingAfter:  optStr(startingAfter),
	}
}

// EmailMailboxesCreateParams is the request body for create.
type EmailMailboxesCreateParams struct {
	// The local part of the mailbox address (the part before `@`). Letters, digits, dots, underscores, and hyphens. Stored lowercase. On the shared `inbox.ai` domain, separators must sit between letters or digits (no leading, trailing, or repeated separators), reserved names such as `postmaster` or `abuse` are unavailable, and choosing your own local part uses one of your plan's custom-handle allowance slots (generated addresses are always available). Omit it and we generate a random local part.
	LocalPart string
	// The domain the address lives under. Defaults to `inbox.ai`, our shared mailbox domain, where creating the mailbox claims the address for your organization: first come, first served, and permanently reserved to your organization even after the mailbox is deleted. May instead name one of your own domains that is enabled for receiving email.
	Domain string
	// Display name used as the sender name on mail from this mailbox.
	DisplayName string
	// Default Reply-To address stamped on mail sent from this mailbox.
	DefaultReplyTo string
	// Which inbound mail the mailbox accepts: - `open`: Accepts everything not blocked by a rule. - `replies_only`: Accepts only replies to messages this mailbox has sent. A reply must match a message the mailbox sent. Landing in an existing thread by itself does not count. - `allowlist`: Accepts only senders matching an allow rule. - `drop`: Stores nothing.
	ReceivePolicy *MailboxCreateReceivePolicy
	// How long the mailbox remembers message metadata and extracted text. Original rendered source is always available for 30 days regardless of tier.
	RetentionTier *MailboxCreateRetentionTier
	// Your own key/value data to attach to the mailbox. Up to 2 KB. Keys starting with `__bird` are reserved.
	Metadata map[string]any
}

func (p EmailMailboxesCreateParams) toWire() oapi.MailboxCreate {
	body := oapi.MailboxCreate{}
	if p.LocalPart != "" {
		body.LocalPart = Ptr(p.LocalPart)
	}
	if p.Domain != "" {
		body.Domain = Ptr(p.Domain)
	}
	if p.DisplayName != "" {
		body.DisplayName = Ptr(p.DisplayName)
	}
	if p.DefaultReplyTo != "" {
		body.DefaultReplyTo = Ptr(openapi_types.Email(p.DefaultReplyTo))
	}
	if p.ReceivePolicy != nil {
		body.ReceivePolicy = p.ReceivePolicy
	}
	if p.RetentionTier != nil {
		body.RetentionTier = p.RetentionTier
	}
	if len(p.Metadata) > 0 {
		v := p.Metadata
		body.Metadata = &v
	}
	return body
}

// EmailMailboxesUpdateParams is the request body for update.
type EmailMailboxesUpdateParams struct {
	// Display name used as the sender name on mail from this mailbox. Null clears it.
	DisplayName Nullable[string]
	// Default Reply-To address stamped on mail sent from this mailbox. Null clears it.
	DefaultReplyTo Nullable[string]
	// Which inbound mail the mailbox accepts.
	ReceivePolicy *MailboxUpdateReceivePolicy
	// How long the mailbox remembers message metadata and extracted text. Lowering the tier deletes remembered messages older than the new horizon, and requires `confirm=true` when that would happen.
	RetentionTier *MailboxUpdateRetentionTier
	// Replaces the mailbox's key/value data. Up to 2 KB. Keys starting with `__bird` are reserved.
	Metadata map[string]any
	// Set to `true` when lowering `retention_tier` would delete remembered messages older than the new cutoff. The request is rejected without it in that case.
	Confirm bool
}

func (p EmailMailboxesUpdateParams) toWire() oapi.MailboxUpdate {
	body := oapi.MailboxUpdate{}
	body.DisplayName = p.DisplayName
	body.DefaultReplyTo = p.DefaultReplyTo
	if p.ReceivePolicy != nil {
		body.ReceivePolicy = p.ReceivePolicy
	}
	if p.RetentionTier != nil {
		body.RetentionTier = p.RetentionTier
	}
	if len(p.Metadata) > 0 {
		v := p.Metadata
		body.Metadata = &v
	}
	return body
}

func (p EmailMailboxesUpdateParams) toWireParams() *oapi.UpdateMailboxParams {
	return &oapi.UpdateMailboxParams{
		Confirm: optBool(p.Confirm),
	}
}

// EmailMailboxesStatsParams filters the stats read.
type EmailMailboxesStatsParams struct {
	// Inclusive start of the window: a calendar day (YYYY-MM-DD, `day` granularity only) or an RFC 3339 instant rounded down to the hour (`hour` granularity only). Interpreted in `timezone`, or in UTC when `timezone` is omitted. A numeric UTC offset is rejected when `timezone` is set; use a calendar day or a `Z` (UTC) instant. Must use the same form as `to`. Defaults to 30 days before `to` at `day` granularity and 7 days before `to` at `hour`, when omitted.
	From string
	// Inclusive end of the window: a calendar day (YYYY-MM-DD, `day` granularity only) or an RFC 3339 instant rounded down to the hour (`hour` granularity only). Interpreted in `timezone`, or in UTC when `timezone` is omitted. A numeric UTC offset is rejected when `timezone` is set; use a calendar day or a `Z` (UTC) instant. Must use the same form as `from`. Defaults to today (day) or the current hour (hour) in that timezone when omitted. Window may not exceed 365 days at `day` or 30 days at `hour` granularity.
	To string
	// IANA timezone identifier (for example `Asia/Kathmandu`) to report in; defaults to UTC. Day and hour boundaries and the default window when `from` and `to` are omitted both follow it, so a calendar-day `from` or `to` names a local day. A `from` or `to` carrying its own UTC offset is rejected while this is set: pass a calendar day or a `Z` instant.
	Timezone string
	// Granularity of the series: `day` (default) or `hour`. Echoed back as `period.grain`.
	Granularity string
}

func (p EmailMailboxesStatsParams) toWire() *oapi.GetMailboxStatsParams {
	return &oapi.GetMailboxStatsParams{
		From:        optStr(p.From),
		To:          optStr(p.To),
		Timezone:    optStr(p.Timezone),
		Granularity: optEnum[oapi.GetMailboxStatsParamsGranularity](p.Granularity),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *EmailMailboxesService) ListPage(ctx context.Context, params EmailMailboxesListParams, startingAfter string, opts ...option.RequestOption) (*MailboxList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListMailboxes(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out MailboxList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's mailboxes as a cursor page, newest first. Search addresses and display names with q, or filter by exact address, state, or domain.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *EmailMailboxesService) List(ctx context.Context, params EmailMailboxesListParams, opts ...option.RequestOption) iter.Seq2[*Mailbox, error] {
	return paginate(func(cursor string) ([]Mailbox, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Create Create a mailbox: a durable agent identity that owns an email address, groups mail into conversations, and remembers conversations for its retention tier.
func (s *EmailMailboxesService) Create(ctx context.Context, params EmailMailboxesCreateParams, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateMailboxParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateMailbox(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get Read one mailbox by ID. A mailbox deleted within its 30-day restore window is still returned, with a non-null `deleted_at`. Once that window closes it is gone and this returns 404.
func (s *EmailMailboxesService) Get(ctx context.Context, mailboxId string, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetMailbox(ctx, oapi.MailboxID(mailboxId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Update a mailbox's display name, reply-to, receive policy, retention tier, IP pool, or metadata. Lowering the retention tier requires `confirm=true` when it would delete remembered messages older than the new cutoff.
func (s *EmailMailboxesService) Update(ctx context.Context, mailboxId string, params EmailMailboxesUpdateParams, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := params.toWireParams()
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateMailbox(ctx, oapi.MailboxID(mailboxId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Delete a mailbox. The address stops receiving immediately and is quarantined. The mailbox and its remembered messages stay restorable for 30 days through the restore endpoint, then are permanently deleted.
func (s *EmailMailboxesService) Delete(ctx context.Context, mailboxId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteMailboxParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteMailbox(ctx, oapi.MailboxID(mailboxId), op, cfg...)
	})
	return err
}

// Restore Restore a mailbox deleted less than 30 days ago: the address starts receiving again and the remembered messages are back. Past the window the mailbox is permanently deleted and returns 404. A mailbox that is not deleted returns 409.
func (s *EmailMailboxesService) Restore(ctx context.Context, mailboxId string, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.RestoreMailboxParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.RestoreMailbox(ctx, oapi.MailboxID(mailboxId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Resume Resume a suspended mailbox so it can send and receive again and its conversations become visible. Fails if your plan does not have room for another active mailbox (or another custom inbox.ai handle). Delete an active mailbox or upgrade first. A mailbox that is not suspended returns 409.
func (s *EmailMailboxesService) Resume(ctx context.Context, mailboxId string, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.ResumeMailboxParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.ResumeMailbox(ctx, oapi.MailboxID(mailboxId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Stats Read a mailbox's sent and received email statistics over a window: a period summary plus a bucketed series. Rows are bucketed by event time rather than send time, so engagement that arrived during the period for messages sent earlier is counted here. Both window bounds must use the same form, calendar days or RFC 3339 instants, matching the granularity.
func (s *EmailMailboxesService) Stats(ctx context.Context, mailboxId string, params EmailMailboxesStatsParams, opts ...option.RequestOption) (*MailboxStatsResponse, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetMailboxStats(ctx, oapi.MailboxID(mailboxId), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out MailboxStatsResponse
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Labels List the labels available in a mailbox: the built-in system labels (inbox, archive, spam, blocked, sent, trash, unread) plus every custom label in use.
func (s *EmailMailboxesService) Labels(ctx context.Context, mailboxId string, opts ...option.RequestOption) (*EmailMailboxLabelList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListMailboxLabels(ctx, oapi.MailboxID(mailboxId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailMailboxLabelList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
