// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EmailCompetitiveVolumeSeriesParams filters the volume_series read.
type EmailCompetitiveVolumeSeriesParams struct {
	// How many days back the response covers, counting from now. One of three fixed trend windows rather than an open date range, matching how a competitive-intelligence chart is read. Defaults to 30.
	Range int
	// Which watched brands to plot, in the order you want the lines. Omit to get only your own line. An id your workspace does not watch is rejected rather than skipped, so a chart cannot quietly lose a line.
	BrandIDs []CompetitiveWatchlistBrandID
}

func (p EmailCompetitiveVolumeSeriesParams) toWire() *oapi.GetEmailCompetitiveVolumeSeriesParams {
	return &oapi.GetEmailCompetitiveVolumeSeriesParams{
		Range:    optInt(oapi.GetEmailCompetitiveVolumeSeriesParamsRange(p.Range)),
		BrandIds: optSlice(p.BrandIDs),
	}
}

// VolumeSeries Accepts up to 20 distinct watchlist entry IDs from `email.competitive.watchlist.get`. Omitting brand_ids requests the workspace's own line. Competitor lines retain the requested order after the workspace line, when present. Each line's source distinguishes estimated panel volume from the workspace's accepted sends. Returns daily series without pagination. API-key calls require Insights preview access for your organization.
func (s *EmailCompetitiveService) VolumeSeries(ctx context.Context, params EmailCompetitiveVolumeSeriesParams, opts ...option.RequestOption) (*EmailCompetitiveVolumeSeries, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailCompetitiveVolumeSeries(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailCompetitiveVolumeSeries
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
