// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EmailInboxInsightsPlacementParams filters the placement read.
type EmailInboxInsightsPlacementParams struct {
	// The sending domain to report on: one of the workspace's verified sending domains, exactly as it appears there. A domain that is not verified in this workspace answers not-found.
	SendingDomain string
	// First UTC day of the period, inclusive, in YYYY-MM-DD: the same window convention as the email statistics endpoints, so figures from the two sources cover the same days. Defaults to 30 days before `to`. It may be at most 30 days before `to`, which is also the default, so a request naming neither date is already at the limit. Asking for more answers `422`: the page pairs these figures with Bird's own per-provider sending statistics, and those are kept for 30 days, so a longer period could only describe two different spans side by side.
	From time.Time
	// Last UTC day of the period, inclusive, in YYYY-MM-DD. Defaults to today.
	To time.Time
	// Bucket size for the series. Defaults to day.
	GroupBy EmailInboxInsightsGroupBy
	// Include the prior equal-length period, populating `compared_to` and every delta field.
	Compare EmailInboxInsightsCompare
	// Providers to break the series down by, named as the provider table names them. Each named provider adds one series line; without this, the series carries the domain-wide line only. The provider table is never filtered by this parameter.
	SeriesProviders []string
	// Include per-IP placement detail for the domain's sending infrastructure. Off by default; only the sending-infrastructure view needs it.
	IncludeIPDetails bool
}

func (p EmailInboxInsightsPlacementParams) toWire() *oapi.GetEmailInboxInsightsPlacementParams {
	return &oapi.GetEmailInboxInsightsPlacementParams{
		SendingDomain:    p.SendingDomain,
		From:             optDate(p.From),
		To:               optDate(p.To),
		GroupBy:          optZero(p.GroupBy),
		Compare:          optZero(p.Compare),
		SeriesProviders:  optSlice(p.SeriesProviders),
		IncludeIpDetails: optBool(p.IncludeIPDetails),
	}
}

// EmailInboxInsightsAuthenticationParams filters the authentication read.
type EmailInboxInsightsAuthenticationParams struct {
	// The sending domain to report on: one of the workspace's verified sending domains, exactly as it appears there. A domain that is not verified in this workspace answers not-found.
	SendingDomain string
	// First UTC day of the period, inclusive, in YYYY-MM-DD: the same window convention as the email statistics endpoints. Defaults to 30 days before `to`. It may be at most 30 days before `to`, which is also the default, so a request naming neither date is already at the limit. Asking for more answers `422`: the page pairs these figures with Bird's own per-provider sending statistics, and those are kept for 30 days, so a longer period could only describe two different spans side by side.
	From time.Time
	// Last UTC day of the period, inclusive, in YYYY-MM-DD. Defaults to today.
	To time.Time
	// Include the prior equal-length period, populating `compared_to`.
	Compare EmailInboxInsightsCompare
}

func (p EmailInboxInsightsAuthenticationParams) toWire() *oapi.GetEmailInboxInsightsAuthenticationParams {
	return &oapi.GetEmailInboxInsightsAuthenticationParams{
		SendingDomain: p.SendingDomain,
		From:          optDate(p.From),
		To:            optDate(p.To),
		Compare:       optZero(p.Compare),
	}
}

// EmailInboxInsightsComplaintsParams filters the complaints read.
type EmailInboxInsightsComplaintsParams struct {
	// The sending domain to report on: one of the workspace's verified sending domains, exactly as it appears there. A domain that is not verified in this workspace answers not-found.
	SendingDomain string
	// First UTC day of the period, inclusive, in YYYY-MM-DD: the same window convention as the email statistics endpoints. Defaults to 30 days before `to`. It may be at most 30 days before `to`, which is also the default, so a request naming neither date is already at the limit. Asking for more answers `422`: the page pairs these figures with Bird's own per-provider sending statistics, and those are kept for 30 days, so a longer period could only describe two different spans side by side.
	From time.Time
	// Last UTC day of the period, inclusive, in YYYY-MM-DD. Defaults to today.
	To time.Time
	// Bucket size for the series. Defaults to day.
	GroupBy EmailInboxInsightsGroupBy
	// Include the prior equal-length period, populating `compared_to` and the rate's delta.
	Compare EmailInboxInsightsCompare
}

func (p EmailInboxInsightsComplaintsParams) toWire() *oapi.GetEmailInboxInsightsComplaintsParams {
	return &oapi.GetEmailInboxInsightsComplaintsParams{
		SendingDomain: p.SendingDomain,
		From:          optDate(p.From),
		To:            optDate(p.To),
		GroupBy:       optZero(p.GroupBy),
		Compare:       optZero(p.Compare),
	}
}

// EmailInboxInsightsSpamTrapsParams filters the spam_traps read.
type EmailInboxInsightsSpamTrapsParams struct {
	// The sending domain to report on: one of the workspace's verified sending domains, exactly as it appears there. A domain that is not verified in this workspace answers not-found.
	SendingDomain string
	// First UTC day of the period, inclusive, in YYYY-MM-DD: the same window convention as the email statistics endpoints. Defaults to 30 days before `to`. It may be at most 30 days before `to`, which is also the default, so a request naming neither date is already at the limit. Asking for more answers `422`: the page pairs these figures with Bird's own per-provider sending statistics, and those are kept for 30 days, so a longer period could only describe two different spans side by side.
	From time.Time
	// Last UTC day of the period, inclusive, in YYYY-MM-DD. Defaults to today.
	To time.Time
	// Include the prior equal-length period, populating `compared_to` and `delta`.
	Compare EmailInboxInsightsCompare
}

func (p EmailInboxInsightsSpamTrapsParams) toWire() *oapi.GetEmailInboxInsightsSpamTrapsParams {
	return &oapi.GetEmailInboxInsightsSpamTrapsParams{
		SendingDomain: p.SendingDomain,
		From:          optDate(p.From),
		To:            optDate(p.To),
		Compare:       optZero(p.Compare),
	}
}

// EmailInboxInsightsBlocklistsParams filters the blocklists read.
type EmailInboxInsightsBlocklistsParams struct {
	// The sending domain to check: one of the workspace's verified sending domains, exactly as it appears there. Every sending IP behind it is checked. A domain that is not verified in this workspace answers not-found.
	SendingDomain string
}

func (p EmailInboxInsightsBlocklistsParams) toWire() *oapi.GetEmailInboxInsightsBlocklistsParams {
	return &oapi.GetEmailInboxInsightsBlocklistsParams{
		SendingDomain: p.SendingDomain,
	}
}

// Placement Read placement for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Rates are percentages, and section statuses distinguish missing measurements. Provider filters add series lines without filtering the provider table. This read does not enable monitoring. API-key calls require Insights preview access for your organization.
func (s *EmailInboxInsightsService) Placement(ctx context.Context, params EmailInboxInsightsPlacementParams, opts ...option.RequestOption) (*EmailInboxInsightsPlacement, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailInboxInsightsPlacement(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailInboxInsightsPlacement
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Authentication Read SPF, DKIM and DMARC results for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Sections can report not_configured when their data source is not connected. This read does not configure authentication or enable monitoring. API-key calls require Insights preview access for your organization.
func (s *EmailInboxInsightsService) Authentication(ctx context.Context, params EmailInboxInsightsAuthenticationParams, opts ...option.RequestOption) (*EmailInboxInsightsAuthentication, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailInboxInsightsAuthentication(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailInboxInsightsAuthentication
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Complaints Read the Google Postmaster spam rate for a verified domain owned by the workspace. This percentage covers Gmail-received mail, not Bird feedback-loop complaints across providers. Dates are inclusive UTC days with at most 30 days between from and to. Use group_by for the series grain and compare=previous_period for the preceding period. Sections can report not_configured when Google Postmaster setup is incomplete. API-key calls require Insights preview access for your organization.
func (s *EmailInboxInsightsService) Complaints(ctx context.Context, params EmailInboxInsightsComplaintsParams, opts ...option.RequestOption) (*EmailInboxInsightsComplaints, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailInboxInsightsComplaints(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailInboxInsightsComplaints
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// SpamTraps Read spam-trap hits for a verified domain owned by the workspace, with totals, trap kinds, networks and individual hits. Dates are inclusive UTC days with at most 30 days between from and to; compare=previous_period includes the preceding period. A measured zero is a valid result. Use the response status to distinguish measurements from unavailable data. API-key calls require Insights preview access for your organization.
func (s *EmailInboxInsightsService) SpamTraps(ctx context.Context, params EmailInboxInsightsSpamTrapsParams, opts ...option.RequestOption) (*EmailInboxInsightsSpamTraps, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailInboxInsightsSpamTraps(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailInboxInsightsSpamTraps
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Blocklists Check blocklist standing for the sending infrastructure of a verified domain owned by the workspace. This is a current lookup and accepts no date window. Inspect each target status and checked_at; a null active_count means no target could be checked, not that every target is clear. API-key calls require Insights preview access for your organization.
func (s *EmailInboxInsightsService) Blocklists(ctx context.Context, params EmailInboxInsightsBlocklistsParams, opts ...option.RequestOption) (*EmailInboxInsightsBlocklists, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailInboxInsightsBlocklists(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailInboxInsightsBlocklists
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
