// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type Tag = oapi.Tag

// EmailThreadsMessagesListParams filters the list. Zero-value fields are omitted.
type EmailThreadsMessagesListParams struct {
	// Filter to received (`inbound`) or sent (`outbound`) messages.
	Direction MessageDirection
	// Filter to messages that have this label. `trash` lists trashed messages. Any other label, whether that is `archive`, `spam`, `blocked`, `unread` or one of your own, lists the messages that have it and are not in the trash. When omitted, received messages in the inbox and all sent messages are returned.
	Label string
	// Set to `extracted_text` to inline each message's extracted plain text.
	Include string
	// Maximum number of items to return per page.
	Limit int
}

func (p EmailThreadsMessagesListParams) toWire(startingAfter string) *oapi.ListEmailThreadMessagesParams {
	return &oapi.ListEmailThreadMessagesParams{
		Direction:     optZero(p.Direction),
		Label:         optStr(p.Label),
		Include:       optEnum[oapi.ListEmailThreadMessagesParamsInclude](p.Include),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// EmailThreadsMessagesReplyParams is the request body for reply.
type EmailThreadsMessagesReplyParams struct {
	// HTML body of the reply. At least one of html or text must be provided.
	HTML string
	// Plain-text body of the reply. At least one of html or text must be provided.
	Text string
	// Also send the reply to the original To and Cc recipients, minus the mailbox's own address.
	ReplyAll *bool
	// Structured `{name, value}` labels for filtering and analytics on the sent-message log. Cap: 20 tags per send.
	Tags []Tag
	// Arbitrary JSON object stored on the send and echoed in webhook payloads. Cap: 2 KB serialized.
	Metadata map[string]any
	// Content classification, which controls suppression policy: - `marketing`: Blocks on all suppression reasons. - `transactional`: Allows delivery through complaint and unsubscribe suppressions, for receipts, password resets, and similar operational mail.
	Category *EmailMessageCategory
	// File attachments to include with the reply. The send is rejected when the estimated generated message size exceeds 20 MB (bodies plus all attachments after base64 encoding). Keep total raw attachment content at or below 15 MB for reliable headroom. Attachment metadata stays on the message's `attachment_manifest`, and the bytes are downloadable for 30 days.
	Attachments []EmailAttachment
}

func (p EmailThreadsMessagesReplyParams) toWire() oapi.EmailThreadMessageReplyRequest {
	body := oapi.EmailThreadMessageReplyRequest{}
	if p.HTML != "" {
		body.Html = Ptr(p.HTML)
	}
	if p.Text != "" {
		body.Text = Ptr(p.Text)
	}
	body.ReplyAll = p.ReplyAll
	if len(p.Tags) > 0 {
		v := p.Tags
		body.Tags = &v
	}
	if len(p.Metadata) > 0 {
		v := p.Metadata
		body.Metadata = &v
	}
	if p.Category != nil {
		body.Category = p.Category
	}
	if len(p.Attachments) > 0 {
		v := p.Attachments
		body.Attachments = &v
	}
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *EmailThreadsMessagesService) ListPage(ctx context.Context, threadId string, params EmailThreadsMessagesListParams, startingAfter string, opts ...option.RequestOption) (*EmailThreadMessageList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListEmailThreadMessages(ctx, oapi.ThreadID(threadId), params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailThreadMessageList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the messages in a conversation newest first, both directions. Page older messages with starting_after, and pass include=extracted_text to inline each message's extracted plain text.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *EmailThreadsMessagesService) List(ctx context.Context, threadId string, params EmailThreadsMessagesListParams, opts ...option.RequestOption) iter.Seq2[*EmailThreadMessage, error] {
	return paginate(func(cursor string) ([]EmailThreadMessage, *string, error) {
		page, err := s.ListPage(ctx, threadId, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Get one conversation message with its extracted plain text, readable for the mailbox's full retention tier without MIME parsing.
func (s *EmailThreadsMessagesService) Get(ctx context.Context, threadId string, messageId string, opts ...option.RequestOption) (*EmailThreadMessage, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailThreadMessage(ctx, oapi.ThreadID(threadId), messageId, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailThreadMessage
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Body Get the original rendered HTML and plain-text body of a conversation message. Available for 30 days. After that, use the message's extracted_text.
func (s *EmailThreadsMessagesService) Body(ctx context.Context, threadId string, messageId string, opts ...option.RequestOption) (*EmailThreadMessageBody, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailThreadMessageBody(ctx, oapi.ThreadID(threadId), messageId, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailThreadMessageBody
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Reply Reply to a specific conversation message from the mailbox's own address. To reply to a conversation, target its newest received message. Recipients, subject, and threading headers are derived automatically.
func (s *EmailThreadsMessagesService) Reply(ctx context.Context, threadId string, messageId string, params EmailThreadsMessagesReplyParams, opts ...option.RequestOption) (*EmailThreadMessage, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.ReplyEmailThreadMessageParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.ReplyEmailThreadMessage(ctx, oapi.ThreadID(threadId), messageId, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailThreadMessage
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Attachments List the attachments on a conversation message. Bytes are downloadable for 30 days, and the metadata stays readable afterward on the message's attachment_manifest.
func (s *EmailThreadsMessagesService) Attachments(ctx context.Context, threadId string, messageId string, opts ...option.RequestOption) (*EmailThreadMessageAttachmentList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListEmailThreadMessageAttachments(ctx, oapi.ThreadID(threadId), messageId, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailThreadMessageAttachmentList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
