// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EmailTemplatesBroadcastsListParams filters the list. Zero-value fields are omitted.
type EmailTemplatesBroadcastsListParams struct {
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p EmailTemplatesBroadcastsListParams) toWire(startingAfter string) *oapi.ListEmailTemplateBroadcastsParams {
	return &oapi.ListEmailTemplateBroadcastsParams{
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *EmailTemplatesBroadcastsService) ListPage(ctx context.Context, templateRef string, params EmailTemplatesBroadcastsListParams, startingAfter string, opts ...option.RequestOption) (*EmailTemplateBroadcastList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListEmailTemplateBroadcasts(ctx, templateRef, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailTemplateBroadcastList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the broadcasts that block deleting a template, newest first.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *EmailTemplatesBroadcastsService) List(ctx context.Context, templateRef string, params EmailTemplatesBroadcastsListParams, opts ...option.RequestOption) iter.Seq2[*EmailTemplateBroadcastSummary, error] {
	return paginate(func(cursor string) ([]EmailTemplateBroadcastSummary, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, templateRef, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}
