// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EmailCompetitiveBrandsSearchParams filters the search read.
type EmailCompetitiveBrandsSearchParams struct {
	// A brand name, or a sending domain to look up the brand behind it.
	Q string
}

func (p EmailCompetitiveBrandsSearchParams) toWire() *oapi.SearchEmailCompetitiveBrandsParams {
	return &oapi.SearchEmailCompetitiveBrandsParams{
		Q: p.Q,
	}
}

// Search Search by brand name or sending domain. Each match returns the panel's `brand_id`, which is different from the `watchlist_brand_id` returned by `email.competitive.watchlist.get`. API-key calls require Insights preview access for your organization.
func (s *EmailCompetitiveBrandsService) Search(ctx context.Context, params EmailCompetitiveBrandsSearchParams, opts ...option.RequestOption) (*EmailCompetitiveBrandSearchResults, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.SearchEmailCompetitiveBrands(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailCompetitiveBrandSearchResults
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
