// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type ReceiveRuleCreateAction = oapi.ReceiveRuleCreateAction

// EmailMailboxesReceiveRulesListParams filters the list. Zero-value fields are omitted.
type EmailMailboxesReceiveRulesListParams struct {
	// Return only `allow` or `block` rules; omit to return both actions.
	Action string
	// Maximum number of items to return per page.
	Limit int
}

func (p EmailMailboxesReceiveRulesListParams) toWire(startingAfter string) *oapi.ListMailboxReceiveRulesParams {
	return &oapi.ListMailboxReceiveRulesParams{
		Action:        optEnum[oapi.ListMailboxReceiveRulesParamsAction](p.Action),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// EmailMailboxesReceiveRulesCreateParams is the request body for create.
type EmailMailboxesReceiveRulesCreateParams struct {
	// What the rule does when it matches. Block rules always win. To flip an entry's action, delete the existing rule and re-create it.
	Action ReceiveRuleCreateAction
	// The sender address (`alice@example.com`) or domain (`example.com`) to match. Domains also match their subdomains. Stored lowercase.
	Entry string
	// Your own note about why the rule exists.
	Note string
}

func (p EmailMailboxesReceiveRulesCreateParams) toWire() oapi.ReceiveRuleCreate {
	body := oapi.ReceiveRuleCreate{}
	body.Action = p.Action
	body.Entry = p.Entry
	if p.Note != "" {
		body.Note = Ptr(p.Note)
	}
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *EmailMailboxesReceiveRulesService) ListPage(ctx context.Context, mailboxId string, params EmailMailboxesReceiveRulesListParams, startingAfter string, opts ...option.RequestOption) (*ReceiveRuleList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListMailboxReceiveRules(ctx, oapi.MailboxID(mailboxId), params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out ReceiveRuleList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List a mailbox's allow/block receive rules as a cursor page, oldest first. Filter by action.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *EmailMailboxesReceiveRulesService) List(ctx context.Context, mailboxId string, params EmailMailboxesReceiveRulesListParams, opts ...option.RequestOption) iter.Seq2[*ReceiveRule, error] {
	return paginate(func(cursor string) ([]ReceiveRule, *string, error) {
		page, err := s.ListPage(ctx, mailboxId, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Create Add an allow or block rule for a sender address or domain to a mailbox. Block always wins. Up to 200 rules per mailbox.
func (s *EmailMailboxesReceiveRulesService) Create(ctx context.Context, mailboxId string, params EmailMailboxesReceiveRulesCreateParams, opts ...option.RequestOption) (*ReceiveRule, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateMailboxReceiveRuleParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateMailboxReceiveRule(ctx, oapi.MailboxID(mailboxId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out ReceiveRule
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Remove a receive rule from a mailbox. Rules have no update operation, so a rule's allow or block action cannot be changed after it is created.
func (s *EmailMailboxesReceiveRulesService) Delete(ctx context.Context, mailboxId string, ruleId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteMailboxReceiveRuleParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteMailboxReceiveRule(ctx, oapi.MailboxID(mailboxId), oapi.ReceiveRuleID(ruleId), op, cfg...)
	})
	return err
}
