// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EmailCompetitiveWatchlistBrandsCreateParams is the request body for create.
type EmailCompetitiveWatchlistBrandsCreateParams struct {
	// Identifier of the brand in the panel's catalog, used to add it to the watchlist. It is a string for the same reason a campaign id is: the values are wide enough that a client storing every number as a floating point value would round them, and a rounded identifier matches no brand at all.
	BrandID string
}

func (p EmailCompetitiveWatchlistBrandsCreateParams) toWire() oapi.EmailCompetitiveWatchlistBrandCreate {
	body := oapi.EmailCompetitiveWatchlistBrandCreate{}
	body.BrandId = p.BrandID
	return body
}

// EmailCompetitiveWatchlistBrandsGetParams filters the get read.
type EmailCompetitiveWatchlistBrandsGetParams struct {
	// How many days back the response covers, counting from now. One of three fixed trend windows rather than an open date range, matching how a competitive-intelligence chart is read. Defaults to 30.
	Range int
}

func (p EmailCompetitiveWatchlistBrandsGetParams) toWire() *oapi.GetEmailCompetitiveBrandParams {
	return &oapi.GetEmailCompetitiveBrandParams{
		Range: optInt(oapi.GetEmailCompetitiveBrandParamsRange(p.Range)),
	}
}

// EmailCompetitiveWatchlistBrandsSendTimeParams filters the send_time read.
type EmailCompetitiveWatchlistBrandsSendTimeParams struct {
	// IANA timezone identifier to report send times in; defaults to UTC. The grid is folded into this zone before it is summed, so a send lands on the weekday and hour it happened at locally rather than the one it happened at in UTC. A zone this API does not know returns 422 rather than falling back to UTC, so an axis is never labelled with a zone the figures were not folded into.
	Timezone string
}

func (p EmailCompetitiveWatchlistBrandsSendTimeParams) toWire() *oapi.GetEmailCompetitiveBrandSendTimeParams {
	return &oapi.GetEmailCompetitiveBrandSendTimeParams{
		Timezone: optZero(p.Timezone),
	}
}

// Create Add a brand using the panel brand_id returned by brand search. The response id identifies the new workspace watchlist entry for reads and removal. Each entry uses one place in the organization-wide allowance and tracks the brand's highest-volume sending domain. Reuse an idempotency key when retrying the same addition. API-key, OAuth, and service-account calls require Insights preview access for your organization.
func (s *EmailCompetitiveWatchlistBrandsService) Create(ctx context.Context, params EmailCompetitiveWatchlistBrandsCreateParams, opts ...option.RequestOption) (*EmailCompetitiveWatchlistBrand, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateEmailCompetitiveWatchlistBrandParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateEmailCompetitiveWatchlistBrand(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailCompetitiveWatchlistBrand
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Remove the workspace watchlist entry using its cwb_ ID. This frees one place in the organization-wide allowance. Adding the brand again creates a new entry; removal does not delete campaign data from eDataSource. API-key calls require Insights preview access for your organization.
func (s *EmailCompetitiveWatchlistBrandsService) Delete(ctx context.Context, watchlistBrandId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteEmailCompetitiveWatchlistBrandParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteEmailCompetitiveWatchlistBrand(ctx, oapi.CompetitiveWatchlistBrandID(watchlistBrandId), op, cfg...)
	})
	return err
}

// Get Read one watched brand using the `watchlist_brand_id` from `email.competitive.watchlist.get`; the panel `brand_id` returned by `email.competitive.brands.search` is not accepted. The response includes headline figures and a mailbox-provider breakdown. API-key calls require Insights preview access for your organization.
func (s *EmailCompetitiveWatchlistBrandsService) Get(ctx context.Context, watchlistBrandId string, params EmailCompetitiveWatchlistBrandsGetParams, opts ...option.RequestOption) (*EmailCompetitiveBrandProfile, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailCompetitiveBrand(ctx, oapi.CompetitiveWatchlistBrandID(watchlistBrandId), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailCompetitiveBrandProfile
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// SendTime Takes a watchlist_brand_id from `email.competitive.watchlist.get` and an optional IANA timezone. Covers the last 90 days, with no range parameter. Cells describe sending activity by weekday and hour. The returned timezone labels the grid; peak_send_window can be null when no sending was observed. API-key calls require Insights preview access for your organization.
func (s *EmailCompetitiveWatchlistBrandsService) SendTime(ctx context.Context, watchlistBrandId string, params EmailCompetitiveWatchlistBrandsSendTimeParams, opts ...option.RequestOption) (*EmailCompetitiveSendTimeGrid, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailCompetitiveBrandSendTime(ctx, oapi.CompetitiveWatchlistBrandID(watchlistBrandId), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailCompetitiveSendTimeGrid
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
