// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// Create Create a private hosted installation link for one eSIM. The recipient needs no Bird login. Links expire after seven days; earlier links remain valid until expiry or revocation. Requires esim_credentials permission. Returns 501 when new hosted links are unavailable.
func (s *EsimInstallLinksService) Create(ctx context.Context, esimId string, opts ...option.RequestOption) (*EsimInstallLink, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateEsimInstallLinkParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateEsimInstallLink(ctx, oapi.EsimID(esimId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimInstallLink
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Revoke a hosted install link so its url stops installing the eSIM. Use it when a link went to the wrong person. Already-revoked and expired links succeed. Requires the esim_credentials scope.
func (s *EsimInstallLinksService) Delete(ctx context.Context, esimId string, installLinkId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteEsimInstallLinkParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteEsimInstallLink(ctx, oapi.EsimID(esimId), oapi.EsimInstallLinkID(installLinkId), op, cfg...)
	})
	return err
}
