// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type EsimDeliveryChannel = oapi.EsimDeliveryChannel

// EsimCredentialsDeliverParams is the request body for deliver.
type EsimCredentialsDeliverParams struct {
	// Recipient address. An email address for the email channel, an E.164 phone number for the sms channel.
	To string
	// Channel the install credentials are delivered over.
	Channel EsimDeliveryChannel
	// Language for the message. Falls back to the closest available language, then English.
	Locale *string
}

func (p EsimCredentialsDeliverParams) toWire() oapi.EsimDelivery {
	body := oapi.EsimDelivery{}
	body.To = p.To
	body.Channel = p.Channel
	body.Locale = p.Locale
	return body
}

// Get Read private installation credentials and device instructions. Requires esim_credentials permission. iOS links and manual details are supported; Android installation links and hosted QR image URLs return null. Returns a conflict for an uninstallable profile and service unavailable when credentials cannot be retrieved.
func (s *EsimCredentialsService) Get(ctx context.Context, esimId string, opts ...option.RequestOption) (*EsimCredentials, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEsimCredentials(ctx, oapi.EsimID(esimId), &oapi.GetEsimCredentialsParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimCredentials
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Deliver Send an eSIM's install credentials to the traveler by email or SMS, in English. Use after purchase or to resend installation details.
func (s *EsimCredentialsService) Deliver(ctx context.Context, esimId string, params EsimCredentialsDeliverParams, opts ...option.RequestOption) (*EsimCredentialsDelivery, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeliverEsimCredentialsParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeliverEsimCredentials(ctx, oapi.EsimID(esimId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimCredentialsDelivery
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
