// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type EsimOrderRecurrence = oapi.EsimOrderRecurrence

type Money = oapi.Money

// EsimOrdersCreateParams is the request body for create.
type EsimOrdersCreateParams struct {
	// Offer to purchase.
	OfferID string
	// Existing eSIM to add the package to. Omit to provision a new eSIM.
	EsimID *string
	// Person to assign the new eSIM to when delivery completes. Must be a subscriber in this workspace. Omit to leave it unassigned. Supplying it with esim_id returns 422; top-ups retain the existing assignment. An unknown subscriber or one outside this workspace returns 404 before charging. Identification guidance does not gate purchase.
	SubscriberID *string
	// The offer revision you are quoting from. When set and the offer has since moved to a newer revision, the order is refused with a conflict instead of charging a price you did not see. Omitted, the current revision is used.
	OfferRevision *int
	// Buy the first package and enable automatic renewal in one purchase. Requires subscriber_id, offer_revision and Idempotency-Key. Omit esim_id and expected_price.
	Recurrence *EsimOrderRecurrence
	// The price you displayed to the buyer. When set and the workspace's current resolved price differs, the order is refused with a conflict instead of charging a different amount. Catches billing-rate changes, which move independently of the offer revision.
	ExpectedPrice *Money
	// Free-text label for the new eSIM, for your own reference. Ignored when esim_id is set.
	DisplayName *string
	// Tags for the new eSIM, echoed on its lifecycle webhook events. Ignored when esim_id is set.
	Tags []Tag
	// Your own key-value data for the new eSIM, echoed on its lifecycle webhook events. Maximum 2 KB serialized. Ignored when esim_id is set.
	Metadata map[string]any
	// Set to true to accept a validity cut short by the eSIM's service period. Without it, an order whose package would expire early is refused with a conflict that states the effective validity.
	AcknowledgeShortenedValidity *bool
}

func (p EsimOrdersCreateParams) toWire() oapi.EsimOrderCreate {
	body := oapi.EsimOrderCreate{}
	body.OfferId = p.OfferID
	body.EsimId = p.EsimID
	body.SubscriberId = p.SubscriberID
	body.OfferRevision = p.OfferRevision
	if p.Recurrence != nil {
		body.Recurrence = p.Recurrence
	}
	if p.ExpectedPrice != nil {
		body.ExpectedPrice = p.ExpectedPrice
	}
	body.DisplayName = p.DisplayName
	if p.Tags != nil {
		v := p.Tags
		body.Tags = &v
	}
	if p.Metadata != nil {
		v := p.Metadata
		body.Metadata = &v
	}
	body.AcknowledgeShortenedValidity = p.AcknowledgeShortenedValidity
	return body
}

// EsimOrdersListParams filters the list. Zero-value fields are omitted.
type EsimOrdersListParams struct {
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
	// Limits the response to resources created at or after this timestamp. Combine it with `created_before` to select a time window. Use an RFC 3339 timestamp with a timezone offset.
	CreatedAfter time.Time
	// Limits the response to resources created before this timestamp. Combine it with `created_after` to select a time window. Use an RFC 3339 timestamp with a timezone offset.
	CreatedBefore time.Time
	// Keep only orders whose `status` matches; repeat the parameter to match any of several.
	Status []EsimOrderStatus
	// Keep only orders for this eSIM.
	EsimID string
	// Keep only orders created in this mode. Without it, both live and test orders are returned.
	Mode EsimMode
	// Keep only orders completed at or after this timestamp. Combine it with `completed_before` to select a completion window, which is what the analytics spend and completion figures are counted by; `created_after` selects when an order was placed instead. Orders that never completed are excluded. Use an RFC 3339 timestamp with a timezone offset.
	CompletedAfter time.Time
	// Keep only orders completed before this timestamp. Combine it with `completed_after` to select a completion window. Orders that never completed are excluded. Use an RFC 3339 timestamp with a timezone offset.
	CompletedBefore time.Time
}

func (p EsimOrdersListParams) toWire(startingAfter string) *oapi.ListEsimOrdersParams {
	return &oapi.ListEsimOrdersParams{
		Limit:           optInt(p.Limit),
		EndingBefore:    optStr(p.EndingBefore),
		CreatedAfter:    optTime(p.CreatedAfter),
		CreatedBefore:   optTime(p.CreatedBefore),
		Status:          optSlice(p.Status),
		EsimId:          optZero(p.EsimID),
		Mode:            optZero(p.Mode),
		CompletedAfter:  optTime(p.CompletedAfter),
		CompletedBefore: optTime(p.CompletedBefore),
		StartingAfter:   optStr(startingAfter),
	}
}

// Create Purchase an eSIM data package. Without esim_id a new eSIM is provisioned with the package; with esim_id the package is added to that eSIM. The order locks the offer's price at creation. Inspect status even on HTTP 201: the order can be completed or failed. On HTTP 202, poll until completed or failed. Omit delivery; after completion use `esim.credentials.deliver` to send install credentials to the traveler.
func (s *EsimOrdersService) Create(ctx context.Context, params EsimOrdersCreateParams, opts ...option.RequestOption) (*EsimOrder, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateEsimOrderParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateEsimOrder(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimOrder
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *EsimOrdersService) ListPage(ctx context.Context, params EsimOrdersListParams, startingAfter string, opts ...option.RequestOption) (*EsimOrderList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListEsimOrders(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimOrderList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List Returns the workspace's orders as a cursor-paginated list, newest first. Filter by `status` to find in-flight or failed purchases, by `esim_id` for one eSIM's purchase history, or by `mode` to separate test purchases from real ones. Test orders are listed alongside real ones by default, each carrying its own `mode`.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *EsimOrdersService) List(ctx context.Context, params EsimOrdersListParams, opts ...option.RequestOption) iter.Seq2[*EsimOrder, error] {
	return paginate(func(cursor string) ([]EsimOrder, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Returns one order. Poll until `status` is `completed` or `failed`; a completed order names the eSIM and package it produced.
func (s *EsimOrdersService) Get(ctx context.Context, orderId string, opts ...option.RequestOption) (*EsimOrder, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEsimOrder(ctx, oapi.EsimOrderID(orderId), &oapi.GetEsimOrderParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimOrder
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Cancel Cancel an order waiting for funds. Inspect the returned status: an unfunded order fails with failure_code canceled; an initial recurring order whose payment was recovered continues delivery with future renewal stopped. One-time orders already funded return a conflict.
func (s *EsimOrdersService) Cancel(ctx context.Context, orderId string, opts ...option.RequestOption) (*EsimOrder, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CancelEsimOrderParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CancelEsimOrder(ctx, oapi.EsimOrderID(orderId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimOrder
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
