// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EsimOffersListParams filters the list. Zero-value fields are omitted.
type EsimOffersListParams struct {
	// Field to sort by. Possible values: created_at.
	Sort EsimOfferSortField
	// Sort direction. Defaults to `desc`, which sorts from newest to oldest or largest to smallest, depending on the selected sort field.
	Order SortOrder
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
	// When true, the response includes a `total` field with the total number of items matching the request's filters across all pages.
	IncludeTotal bool
	// Keep only offers whose coverage zone includes this country (ISO 3166-1 alpha-2).
	Country string
	// Keep only offers selling this coverage zone.
	ZoneID string
	// Filter by offer availability. Omitted, only active offers are returned.
	Status EsimOfferStatus
}

func (p EsimOffersListParams) toWire(startingAfter string) *oapi.ListEsimOffersParams {
	return &oapi.ListEsimOffersParams{
		Sort:          optZero(p.Sort),
		Order:         optZero(p.Order),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		IncludeTotal:  optBool(p.IncludeTotal),
		Country:       optZero(p.Country),
		ZoneId:        optZero(p.ZoneID),
		Status:        optZero(p.Status),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *EsimOffersService) ListPage(ctx context.Context, params EsimOffersListParams, startingAfter string, opts ...option.RequestOption) (*EsimOfferList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListEsimOffers(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimOfferList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the prepaid travel eSIM offers available to this workspace as a cursor page ({data, next_cursor, ...}). Filter by country (ISO 3166-1 alpha-2) to find offers that cover a destination, or by zone_id for one coverage footprint. Each row carries the offer's pricing (data allowance, validity, and the price billed per provisioned package) and its zone_id; fetch the offer or the zone for the country list.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *EsimOffersService) List(ctx context.Context, params EsimOffersListParams, opts ...option.RequestOption) iter.Seq2[*EsimOfferSummary, error] {
	return paginate(func(cursor string) ([]EsimOfferSummary, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Returns one eSIM offer with its pricing and embedded coverage zone.
func (s *EsimOffersService) Get(ctx context.Context, offerId string, opts ...option.RequestOption) (*EsimOffer, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEsimOffer(ctx, oapi.EsimOfferID(offerId), &oapi.GetEsimOfferParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimOffer
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Requirements Returns a complete JSON Schema for each country in the offer coverage zone. First name, last name, and email are always required, including where no country definition exists. Customers collect and validate information themselves; enable JSON Schema format assertion for email and dates. Bird receives no answers and does not use these schemas to authorize purchase or assignment.
func (s *EsimOffersService) Requirements(ctx context.Context, offerId string, opts ...option.RequestOption) (*EsimOfferRequirements, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEsimOfferRequirements(ctx, oapi.EsimOfferID(offerId), &oapi.GetEsimOfferRequirementsParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimOfferRequirements
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CheckoutOptions Returns published one-time terms and automatic renewal availability for a new eSIM. Automatic renewal includes its own price and cadence when an eligible mobile network is available. Availability is checked again when purchasing; this read does not reserve a package.
func (s *EsimOffersService) CheckoutOptions(ctx context.Context, offerId string, opts ...option.RequestOption) (*EsimCheckoutOptions, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEsimOfferCheckoutOptions(ctx, oapi.EsimOfferID(offerId), &oapi.GetEsimOfferCheckoutOptionsParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimCheckoutOptions
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Recurrence Returns the published whole-package recurring price and calendar-month or fixed-day cadence. Enrollment additionally checks that the assigned eSIM mobile network supports these terms.
func (s *EsimOffersService) Recurrence(ctx context.Context, offerId string, opts ...option.RequestOption) (*EsimRecurringOffer, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEsimOfferRecurrence(ctx, oapi.EsimOfferID(offerId), &oapi.GetEsimOfferRecurrenceParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimRecurringOffer
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
