// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EsimSettingsUpdateParams is the request body for update.
type EsimSettingsUpdateParams struct {
	// Send `false` to stop Bird sending eSIM install credentials to travelers for this workspace, or `true` to allow it again. Credentials stay readable from the API either way.
	CredentialDeliveryEnabled *bool
}

func (p EsimSettingsUpdateParams) toWire() oapi.EsimSettingsUpdate {
	body := oapi.EsimSettingsUpdate{}
	body.CredentialDeliveryEnabled = p.CredentialDeliveryEnabled
	return body
}

// Get Read the workspace's effective eSIM settings, including whether Bird sends install credentials to travelers. Check this before sending credentials: a workspace that has turned delivery off refuses the send.
func (s *EsimSettingsService) Get(ctx context.Context, opts ...option.RequestOption) (*EsimSettings, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEsimSettings(ctx, &oapi.GetEsimSettingsParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimSettings
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Change the workspace's eSIM settings and return the effective result. Turning `credential_delivery_enabled` off stops Bird sending install credentials to travelers over either channel; the credentials stay readable from the API. Omitted fields keep their current value.
func (s *EsimSettingsService) Update(ctx context.Context, params EsimSettingsUpdateParams, opts ...option.RequestOption) (*EsimSettings, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UpdateEsimSettingsParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateEsimSettings(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimSettings
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
