// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// EsimRecurringSubscriptionsCreateParams is the request body for create.
type EsimRecurringSubscriptionsCreateParams struct {
	// Assigned eSIM receiving the recurring package.
	EsimID string
	// Offer whose recurring terms the buyer accepted.
	OfferID string
	// The accepted offer revision.
	OfferRevision int
	// The accepted recurring configuration revision.
	RecurrenceRevision int
	AcceptedPrice      Money
}

func (p EsimRecurringSubscriptionsCreateParams) toWire() oapi.EsimRecurringSubscriptionCreate {
	body := oapi.EsimRecurringSubscriptionCreate{}
	body.EsimId = p.EsimID
	body.OfferId = p.OfferID
	body.OfferRevision = p.OfferRevision
	body.RecurrenceRevision = p.RecurrenceRevision
	body.AcceptedPrice = p.AcceptedPrice
	return body
}

// EsimRecurringSubscriptionsListParams filters the list. Zero-value fields are omitted.
type EsimRecurringSubscriptionsListParams struct {
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
	// Return eSIMs assigned to this subscriber.
	SubscriberID string
	// Filter by esim id.
	EsimID string
}

func (p EsimRecurringSubscriptionsListParams) toWire(startingAfter string) *oapi.ListEsimRecurringSubscriptionsParams {
	return &oapi.ListEsimRecurringSubscriptionsParams{
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		SubscriberId:  optZero(p.SubscriberID),
		EsimId:        optZero(p.EsimID),
		StartingAfter: optStr(startingAfter),
	}
}

// EsimRecurringSubscriptionsPeriodsParams filters the list. Zero-value fields are omitted.
type EsimRecurringSubscriptionsPeriodsParams struct {
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p EsimRecurringSubscriptionsPeriodsParams) toWire(startingAfter string) *oapi.ListEsimRecurringPeriodsParams {
	return &oapi.ListEsimRecurringPeriodsParams{
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		StartingAfter: optStr(startingAfter),
	}
}

// Create Purchase the first recurring period on an assigned eSIM. Reuse the required Idempotency-Key and identical request to recover enrollment. Check subscription and period history for payment and delivery outcomes. Changed prices, unfunded renewal, or confirmed delivery failure stop future renewal.
func (s *EsimRecurringSubscriptionsService) Create(ctx context.Context, params EsimRecurringSubscriptionsCreateParams, opts ...option.RequestOption) (*EsimRecurringSubscription, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateEsimRecurringSubscriptionParams{}
		op.IdempotencyKey = idempotencyKey
		return s.client.oapi.CreateEsimRecurringSubscription(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimRecurringSubscription
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *EsimRecurringSubscriptionsService) ListPage(ctx context.Context, params EsimRecurringSubscriptionsListParams, startingAfter string, opts ...option.RequestOption) (*EsimRecurringSubscriptionList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListEsimRecurringSubscriptions(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimRecurringSubscriptionList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List Returns recurring services for assigned eSIMs in this workspace.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *EsimRecurringSubscriptionsService) List(ctx context.Context, params EsimRecurringSubscriptionsListParams, opts ...option.RequestOption) iter.Seq2[*EsimRecurringSubscription, error] {
	return paginate(func(cursor string) ([]EsimRecurringSubscription, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Returns the current paid period separately from package delivery and cancellation state.
func (s *EsimRecurringSubscriptionsService) Get(ctx context.Context, subscriptionId string, opts ...option.RequestOption) (*EsimRecurringSubscription, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEsimRecurringSubscription(ctx, oapi.EsimRecurringSubscriptionID(subscriptionId), &oapi.GetEsimRecurringSubscriptionParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimRecurringSubscription
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Cancel Stops future package renewal at the current paid boundary. A period already committed remains payable. The installed profile and separately purchased packages are preserved.
func (s *EsimRecurringSubscriptionsService) Cancel(ctx context.Context, subscriptionId string, opts ...option.RequestOption) (*EsimRecurringSubscription, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CancelEsimRecurringSubscriptionParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CancelEsimRecurringSubscription(ctx, oapi.EsimRecurringSubscriptionID(subscriptionId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimRecurringSubscription
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// PeriodsPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *EsimRecurringSubscriptionsService) PeriodsPage(ctx context.Context, subscriptionId string, params EsimRecurringSubscriptionsPeriodsParams, startingAfter string, opts ...option.RequestOption) (*EsimRecurringPeriodList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListEsimRecurringPeriods(ctx, oapi.EsimRecurringSubscriptionID(subscriptionId), params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EsimRecurringPeriodList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Periods Returns funded periods with their original charges, confirmed credits, and delivery orders. Unfunded renewals do not create a paid period.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *EsimRecurringSubscriptionsService) Periods(ctx context.Context, subscriptionId string, params EsimRecurringSubscriptionsPeriodsParams, opts ...option.RequestOption) iter.Seq2[*EsimRecurringPeriod, error] {
	return paginate(func(cursor string) ([]EsimRecurringPeriod, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.PeriodsPage(ctx, subscriptionId, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}
