// Code generated by beak gen:event-consts. DO NOT EDIT.

package bird

import (
	"github.com/messagebird/bird-sdk-go/internal/oapi"
)

// Webhook event types known at this SDK version. WebhookEventType is an open
// string on the wire: a value added by a newer server flows through Unwrap
// unchanged, so switch on these constants with a default branch.
const (
	EventTypeDomainFailed                 = oapi.EventTypeDomainFailed
	EventTypeDomainVerified               = oapi.EventTypeDomainVerified
	EventTypeEmailAccepted                = oapi.EventTypeEmailAccepted
	EventTypeEmailBounced                 = oapi.EventTypeEmailBounced
	EventTypeEmailCanceled                = oapi.EventTypeEmailCanceled
	EventTypeEmailClicked                 = oapi.EventTypeEmailClicked
	EventTypeEmailComplained              = oapi.EventTypeEmailComplained
	EventTypeEmailDeferred                = oapi.EventTypeEmailDeferred
	EventTypeEmailDelivered               = oapi.EventTypeEmailDelivered
	EventTypeEmailListUnsubscribed        = oapi.EventTypeEmailListUnsubscribed
	EventTypeEmailMailboxMessageDelivered = oapi.EventTypeEmailMailboxMessageDelivered
	EventTypeEmailMailboxMessageFailed    = oapi.EventTypeEmailMailboxMessageFailed
	EventTypeEmailMailboxMessageReceived  = oapi.EventTypeEmailMailboxMessageReceived
	EventTypeEmailMailboxMessageSent      = oapi.EventTypeEmailMailboxMessageSent
	EventTypeEmailMailboxSuspended        = oapi.EventTypeEmailMailboxSuspended
	EventTypeEmailMailboxThreadCreated    = oapi.EventTypeEmailMailboxThreadCreated
	EventTypeEmailOpened                  = oapi.EventTypeEmailOpened
	EventTypeEmailOutOfBandBounce         = oapi.EventTypeEmailOutOfBandBounce
	EventTypeEmailProcessed               = oapi.EventTypeEmailProcessed
	EventTypeEmailReceived                = oapi.EventTypeEmailReceived
	EventTypeEmailRejected                = oapi.EventTypeEmailRejected
	EventTypeEmailScheduled               = oapi.EventTypeEmailScheduled
	EventTypeEmailSuppressionCreated      = oapi.EventTypeEmailSuppressionCreated
	EventTypeEmailUnsubscribed            = oapi.EventTypeEmailUnsubscribed
	EventTypeSmsAccepted                  = oapi.EventTypeSmsAccepted
	EventTypeSmsDelivered                 = oapi.EventTypeSmsDelivered
	EventTypeSmsExpired                   = oapi.EventTypeSmsExpired
	EventTypeSmsFailed                    = oapi.EventTypeSmsFailed
	EventTypeSmsRejected                  = oapi.EventTypeSmsRejected
	EventTypeSmsSent                      = oapi.EventTypeSmsSent
	EventTypeSmsUndelivered               = oapi.EventTypeSmsUndelivered
	EventTypeVerifyAttemptDelivered       = oapi.EventTypeVerifyAttemptDelivered
	EventTypeVerifyAttemptSent            = oapi.EventTypeVerifyAttemptSent
	EventTypeVerifyAttemptUndelivered     = oapi.EventTypeVerifyAttemptUndelivered
	EventTypeVerifyVerificationCreated    = oapi.EventTypeVerifyVerificationCreated
	EventTypeVerifyVerificationVerified   = oapi.EventTypeVerifyVerificationVerified
	EventTypeVoiceCallAnswered            = oapi.EventTypeVoiceCallAnswered
	EventTypeVoiceCallEnded               = oapi.EventTypeVoiceCallEnded
	EventTypeVoiceCallInitiated           = oapi.EventTypeVoiceCallInitiated
	EventTypeWhatsappAccepted             = oapi.EventTypeWhatsappAccepted
	EventTypeWhatsappDelivered            = oapi.EventTypeWhatsappDelivered
	EventTypeWhatsappFailed               = oapi.EventTypeWhatsappFailed
	EventTypeWhatsappRead                 = oapi.EventTypeWhatsappRead
	EventTypeWhatsappRejected             = oapi.EventTypeWhatsappRejected
	EventTypeWhatsappSent                 = oapi.EventTypeWhatsappSent
)
