// Code generated by openapi/scripts/eventconst-gen.go. DO NOT EDIT.

package bird

// Webhook event types known at this SDK version. WebhookEventType is an open
// string on the wire: a value added by a newer server flows through Unwrap
// unchanged, so switch on these constants with a default branch.
const (
	EventTypeDomainFailed                 WebhookEventType = "domain.failed"
	EventTypeDomainVerified               WebhookEventType = "domain.verified"
	EventTypeEmailAccepted                WebhookEventType = "email.accepted"
	EventTypeEmailBounced                 WebhookEventType = "email.bounced"
	EventTypeEmailCanceled                WebhookEventType = "email.canceled"
	EventTypeEmailClicked                 WebhookEventType = "email.clicked"
	EventTypeEmailComplained              WebhookEventType = "email.complained"
	EventTypeEmailDeferred                WebhookEventType = "email.deferred"
	EventTypeEmailDelivered               WebhookEventType = "email.delivered"
	EventTypeEmailListUnsubscribed        WebhookEventType = "email.list_unsubscribed"
	EventTypeEmailMailboxMessageDelivered WebhookEventType = "email_mailbox.message_delivered"
	EventTypeEmailMailboxMessageFailed    WebhookEventType = "email_mailbox.message_failed"
	EventTypeEmailMailboxMessageReceived  WebhookEventType = "email_mailbox.message_received"
	EventTypeEmailMailboxMessageSent      WebhookEventType = "email_mailbox.message_sent"
	EventTypeEmailMailboxSuspended        WebhookEventType = "email_mailbox.suspended"
	EventTypeEmailMailboxThreadCreated    WebhookEventType = "email_mailbox.thread_created"
	EventTypeEmailOpened                  WebhookEventType = "email.opened"
	EventTypeEmailOutOfBandBounce         WebhookEventType = "email.out_of_band_bounce"
	EventTypeEmailProcessed               WebhookEventType = "email.processed"
	EventTypeEmailReceived                WebhookEventType = "email.received"
	EventTypeEmailRejected                WebhookEventType = "email.rejected"
	EventTypeEmailScheduled               WebhookEventType = "email.scheduled"
	EventTypeEmailSuppressionCreated      WebhookEventType = "email_suppression.created"
	EventTypeEmailUnsubscribed            WebhookEventType = "email.unsubscribed"
	EventTypeRealtimeCacheChannels        WebhookEventType = "realtime.cache_channels"
	EventTypeRealtimeChannelExistence     WebhookEventType = "realtime.channel_existence"
	EventTypeRealtimeClientEvents         WebhookEventType = "realtime.client_events"
	EventTypeRealtimePresence             WebhookEventType = "realtime.presence"
	EventTypeRealtimeSubscriptionCount    WebhookEventType = "realtime.subscription_count"
	EventTypeSmsAccepted                  WebhookEventType = "sms.accepted"
	EventTypeSmsDelivered                 WebhookEventType = "sms.delivered"
	EventTypeSmsExpired                   WebhookEventType = "sms.expired"
	EventTypeSmsFailed                    WebhookEventType = "sms.failed"
	EventTypeSmsRejected                  WebhookEventType = "sms.rejected"
	EventTypeSmsSent                      WebhookEventType = "sms.sent"
	EventTypeSmsUndelivered               WebhookEventType = "sms.undelivered"
)
