// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	openapi_types "github.com/oapi-codegen/runtime/types"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type MailboxCreateReceivePolicy = oapi.MailboxCreateReceivePolicy

type MailboxCreateRetentionTier = oapi.MailboxCreateRetentionTier

type MailboxUpdateReceivePolicy = oapi.MailboxUpdateReceivePolicy

type MailboxUpdateRetentionTier = oapi.MailboxUpdateRetentionTier

// MailboxListParams filters the list. Zero-value fields are omitted.
type MailboxListParams struct {
	// Filter to the mailbox with exactly this address.
	Address string
	// Case-insensitive search matching the mailbox's address or display name (substring).
	Q string
	// Filter by lifecycle state.
	State string
	// Filter to mailboxes whose address is on this domain.
	Domain string
	// Include mailboxes deleted within their 30-day restore window. Defaults to false, so only active and suspended mailboxes are returned. Deleted mailboxes carry a non-null `deleted_at`.
	IncludeDeleted bool
	// Maximum number of items to return per page.
	Limit int
}

func (p MailboxListParams) toWire(startingAfter string) *oapi.ListMailboxesParams {
	return &oapi.ListMailboxesParams{
		Address:        optEmail(p.Address),
		Q:              optStr(p.Q),
		State:          optEnum[oapi.ListMailboxesParamsState](p.State),
		Domain:         optStr(p.Domain),
		IncludeDeleted: optBool(p.IncludeDeleted),
		Limit:          optInt(p.Limit),
		StartingAfter:  optStr(startingAfter),
	}
}

// MailboxCreateParams is the request body for create.
type MailboxCreateParams struct {
	// The local part of the mailbox address (the part before `@`). Letters, digits, dots, underscores, and hyphens; stored lowercase. On the shared `inbox.ai` domain, separators must sit between letters or digits (no leading, trailing, or repeated separators), reserved names such as `postmaster` or `abuse` are unavailable, and choosing your own local part uses one of your plan's custom-handle allowance slots (generated addresses are always available). Omit to have Bird generate a random local part.
	LocalPart string
	// The domain the address lives under. Defaults to `inbox.ai`, Bird's shared mailbox domain, where creating the mailbox claims the address for your organization: first come, first served, and permanently reserved to your organization even after the mailbox is deleted. May instead name one of your own domains that is enabled for receiving email.
	Domain string
	// Display name used as the sender name on mail from this mailbox.
	DisplayName string
	// Default Reply-To address stamped on mail sent from this mailbox.
	DefaultReplyTo string
	// Which inbound mail the mailbox accepts. `open` accepts everything not blocked by a rule; `replies_only` accepts only replies to messages this mailbox has sent (a reply must match a message the mailbox sent, not merely land in an existing thread); `allowlist` accepts only senders matching an allow rule; `drop` stores nothing.
	ReceivePolicy *MailboxCreateReceivePolicy
	// How long the mailbox remembers message metadata and extracted text. Original rendered source is always available for 30 days regardless of tier. Only `30d` is available today; longer tiers (`90d`, `1y`, and beyond) are coming soon.
	RetentionTier *MailboxCreateRetentionTier
	// Your own key/value data to attach to the mailbox. Up to 2 KB; keys starting with `__bird` are reserved.
	Metadata map[string]any
}

func (p MailboxCreateParams) toWire() oapi.MailboxCreate {
	body := oapi.MailboxCreate{}
	if p.LocalPart != "" {
		body.LocalPart = Ptr(p.LocalPart)
	}
	if p.Domain != "" {
		body.Domain = Ptr(p.Domain)
	}
	if p.DisplayName != "" {
		body.DisplayName = Ptr(p.DisplayName)
	}
	if p.DefaultReplyTo != "" {
		body.DefaultReplyTo = Ptr(openapi_types.Email(p.DefaultReplyTo))
	}
	if p.ReceivePolicy != nil {
		body.ReceivePolicy = p.ReceivePolicy
	}
	if p.RetentionTier != nil {
		body.RetentionTier = p.RetentionTier
	}
	if len(p.Metadata) > 0 {
		v := p.Metadata
		body.Metadata = &v
	}
	return body
}

// MailboxUpdateParams is the request body for update.
type MailboxUpdateParams struct {
	// Display name used as the sender name on mail from this mailbox. Null clears it.
	DisplayName Nullable[string]
	// Default Reply-To address stamped on mail sent from this mailbox. Null clears it.
	DefaultReplyTo Nullable[string]
	// Which inbound mail the mailbox accepts.
	ReceivePolicy *MailboxUpdateReceivePolicy
	// How long the mailbox remembers message metadata and extracted text. Lowering the tier deletes memory older than the new horizon and requires `confirm=true` when messages older than the new horizon would be deleted. Only `30d` is available today; longer tiers (`90d`, `1y`, and beyond) are coming soon.
	RetentionTier *MailboxUpdateRetentionTier
	// Replaces the mailbox's key/value data. Up to 2 KB; keys starting with `__bird` are reserved.
	Metadata map[string]any
	// Required as `true` when lowering `retention_tier`, acknowledging that remembered messages older than the new horizon are deleted.
	Confirm bool
}

func (p MailboxUpdateParams) toWire() oapi.MailboxUpdate {
	body := oapi.MailboxUpdate{}
	body.DisplayName = p.DisplayName
	body.DefaultReplyTo = p.DefaultReplyTo
	if p.ReceivePolicy != nil {
		body.ReceivePolicy = p.ReceivePolicy
	}
	if p.RetentionTier != nil {
		body.RetentionTier = p.RetentionTier
	}
	if len(p.Metadata) > 0 {
		v := p.Metadata
		body.Metadata = &v
	}
	return body
}

func (p MailboxUpdateParams) toWireParams() *oapi.UpdateMailboxParams {
	return &oapi.UpdateMailboxParams{
		Confirm: optBool(p.Confirm),
	}
}

// MailboxStatsParams filters the stats read.
type MailboxStatsParams struct {
	// Inclusive start of the window: a calendar day (YYYY-MM-DD, `day` granularity only) or an RFC 3339 instant rounded down to the hour (`hour` granularity only). Interpreted in `timezone`, or in UTC when `timezone` is omitted. A numeric UTC offset is rejected when `timezone` is set; use a calendar day or a `Z` (UTC) instant. Must use the same form as `to`. Defaults to 30 days before `to` at `day` granularity and 7 days before `to` at `hour`, when omitted.
	From string
	// Inclusive end of the window: a calendar day (YYYY-MM-DD, `day` granularity only) or an RFC 3339 instant rounded down to the hour (`hour` granularity only). Interpreted in `timezone`, or in UTC when `timezone` is omitted. A numeric UTC offset is rejected when `timezone` is set; use a calendar day or a `Z` (UTC) instant. Must use the same form as `from`. Defaults to today (day) or the current hour (hour) in that timezone when omitted. Window may not exceed 365 days at `day` or 30 days at `hour` granularity.
	To string
	// IANA timezone identifier (for example `Asia/Kathmandu` or `America/New_York`) to report the statistics in. It is the single source of timezone: day and hour boundaries, and the relative window defaults used when `from` and `to` are omitted, are computed in this timezone instead of UTC, so a timezone with a sub-hour offset (such as India at +05:30 or Nepal at +05:45) still gets correct local-day and local-hour totals. When it is set, a `from` or `to` given as a calendar day names a local day in this timezone, and one given as an instant stays an absolute point in time but is rounded down to its hour and bucketed in this timezone (so the hour boundaries are local, not UTC). To avoid specifying the zone twice, a `from` or `to` that carries its own numeric UTC offset (for example `+05:45`) is rejected when `timezone` is set; use a calendar day or a `Z` (UTC) instant instead. Defaults to UTC.
	Timezone string
	// Bucket grain of the series: `day` (default) or `hour`. Echoed back as `period.grain`.
	Granularity string
}

func (p MailboxStatsParams) toWire() *oapi.GetMailboxStatsParams {
	return &oapi.GetMailboxStatsParams{
		From:        optStr(p.From),
		To:          optStr(p.To),
		Timezone:    optStr(p.Timezone),
		Granularity: optEnum[oapi.GetMailboxStatsParamsGranularity](p.Granularity),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *MailboxService) ListPage(ctx context.Context, params MailboxListParams, startingAfter string, opts ...option.RequestOption) (*MailboxList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListMailboxes(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out MailboxList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's mailboxes as a cursor page, newest first. Search addresses and display names with q, or filter by exact address, state, or domain.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *MailboxService) List(ctx context.Context, params MailboxListParams, opts ...option.RequestOption) iter.Seq2[*Mailbox, error] {
	return paginate(func(cursor string) ([]Mailbox, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Create Create a mailbox — a durable agent identity that owns an email address, groups mail into threads, and remembers conversations for its retention tier.
func (s *MailboxService) Create(ctx context.Context, params MailboxCreateParams, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateMailboxParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateMailbox(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *MailboxService) Get(ctx context.Context, mailboxId string, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetMailbox(ctx, oapi.MailboxID(mailboxId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Update a mailbox's display name, reply-to, receive policy, retention tier, contact, or metadata. Lowering the retention tier onto remembered messages older than the new horizon requires confirm=true.
func (s *MailboxService) Update(ctx context.Context, mailboxId string, params MailboxUpdateParams, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := params.toWireParams()
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateMailbox(ctx, oapi.MailboxID(mailboxId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Delete a mailbox. The address stops receiving immediately and is quarantined; the mailbox and its remembered messages stay restorable for 30 days via the restore endpoint, then are permanently deleted.
func (s *MailboxService) Delete(ctx context.Context, mailboxId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteMailboxParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteMailbox(ctx, oapi.MailboxID(mailboxId), op, cfg...)
	})
	return err
}

// Restore Restore a mailbox deleted less than 30 days ago: the address starts receiving again and the remembered messages are back. Past the window the mailbox is permanently deleted and returns 404; a mailbox that is not deleted returns 409.
func (s *MailboxService) Restore(ctx context.Context, mailboxId string, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.RestoreMailboxParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.RestoreMailbox(ctx, oapi.MailboxID(mailboxId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Resume Reactivate a suspended mailbox so it can send and receive again and its threads become visible. Fails if your plan does not have room for another active mailbox (or another custom inbox.ai handle); delete an active mailbox or upgrade first. A mailbox that is not suspended returns 409.
func (s *MailboxService) Resume(ctx context.Context, mailboxId string, opts ...option.RequestOption) (*Mailbox, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.ResumeMailboxParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.ResumeMailbox(ctx, oapi.MailboxID(mailboxId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Mailbox
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *MailboxService) Stats(ctx context.Context, mailboxId string, params MailboxStatsParams, opts ...option.RequestOption) (*MailboxStatsResponse, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetMailboxStats(ctx, oapi.MailboxID(mailboxId), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out MailboxStatsResponse
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Labels List the labels available in a mailbox: the built-in system labels (inbox, archive, spam, blocked, sent, trash, unread) plus every custom label in use.
func (s *MailboxService) Labels(ctx context.Context, mailboxId string, opts ...option.RequestOption) (*EmailMailboxLabelList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListMailboxLabels(ctx, oapi.MailboxID(mailboxId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailMailboxLabelList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
