// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type EmailLabelsUpdate = oapi.EmailLabelsUpdate

// MailboxThreadListParams filters the list. Zero-value fields are omitted.
type MailboxThreadListParams struct {
	// Filter to conversations in a specific mailbox.
	MailboxID string
	// Filter to conversations linked to a specific contact.
	ContactID string
	// Filter to conversations carrying this label. Repeat the parameter to require several — only conversations carrying every listed label match. A placement label selects a folder (`inbox`, `archive`, `spam`, `blocked`); a custom label matches conversations in any folder. Defaults to `inbox` when omitted.
	Label []string
	// When `true`, only conversations with unread messages are returned. This filters on the conversation's unread state, so it combines with `label` — for example, unread conversations in the archive. (The `unread` label itself lives on messages, not conversations.)
	HasUnread bool
	// Conversations involving this address — matches the sender or any recipient, as a case-insensitive contains-match, so a full address or any fragment of one works.
	Participant string
	// Conversations whose subject contains this text (case-insensitive).
	Subject string
	// Filter to conversations whose most recent message is at or after this time. This is a time filter, not a cursor.
	After time.Time
	// Filter to conversations whose most recent message is at or before this time. This is a time filter, not a cursor.
	Before time.Time
	// Maximum number of items to return per page.
	Limit int
}

func (p MailboxThreadListParams) toWire(startingAfter string) *oapi.ListEmailThreadsParams {
	return &oapi.ListEmailThreadsParams{
		MailboxId:     optZero(p.MailboxID),
		ContactId:     optZero(p.ContactID),
		Label:         optSlice(p.Label),
		HasUnread:     optBool(p.HasUnread),
		Participant:   optStr(p.Participant),
		Subject:       optStr(p.Subject),
		After:         optTime(p.After),
		Before:        optTime(p.Before),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// MailboxThreadUpdateParams is the request body for update.
type MailboxThreadUpdateParams struct {
	Labels *EmailLabelsUpdate
	// Contact to link this conversation to, or null to unlink the current contact.
	ContactID Nullable[string]
}

func (p MailboxThreadUpdateParams) toWire() oapi.EmailThreadUpdateRequest {
	body := oapi.EmailThreadUpdateRequest{}
	if p.Labels != nil {
		body.Labels = p.Labels
	}
	body.ContactId = p.ContactID
	return body
}

// MailboxThreadDeleteParams holds the delete's query filters.
type MailboxThreadDeleteParams struct {
	// Permanently delete the conversation and its messages immediately instead of moving them to the trash.
	Permanent bool
}

func (p MailboxThreadDeleteParams) toWire() *oapi.DeleteEmailThreadParams {
	return &oapi.DeleteEmailThreadParams{
		Permanent: optBool(p.Permanent),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *MailboxThreadService) ListPage(ctx context.Context, params MailboxThreadListParams, startingAfter string, opts ...option.RequestOption) (*EmailThreadList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListEmailThreads(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailThreadList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List mailbox conversations as a cursor page, most recently active first. `label` selects the view — inbox (default), archive, spam, blocked, or a custom label. Filter by mailbox, contact, participant address, or subject substring.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *MailboxThreadService) List(ctx context.Context, params MailboxThreadListParams, opts ...option.RequestOption) iter.Seq2[*EmailThread, error] {
	return paginate(func(cursor string) ([]EmailThread, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Get one conversation: participants, counts, labels, read state. Fetch its messages with the thread messages endpoint.
func (s *MailboxThreadService) Get(ctx context.Context, threadId string, opts ...option.RequestOption) (*EmailThread, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetEmailThread(ctx, oapi.ThreadID(threadId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailThread
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Add or remove labels on a conversation — adding `spam` files it as spam, adding `archive` clears it out of the inbox, adding `inbox` brings it back — or link/unlink a contact.
func (s *MailboxThreadService) Update(ctx context.Context, threadId string, params MailboxThreadUpdateParams, opts ...option.RequestOption) (*EmailThread, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UpdateEmailThreadParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateEmailThread(ctx, oapi.ThreadID(threadId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out EmailThread
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Move a conversation and all its messages to trash (purged after 30 days), or delete permanently with ?permanent=true.
func (s *MailboxThreadService) Delete(ctx context.Context, threadId string, params MailboxThreadDeleteParams, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := params.toWire()
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteEmailThread(ctx, oapi.ThreadID(threadId), op, cfg...)
	})
	return err
}
