// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// NumbersAvailableListParams filters the list. Zero-value fields are omitted.
type NumbersAvailableListParams struct {
	// ISO 3166-1 alpha-2 country code to search in.
	CountryCode string
	// Return only numbers of this physical type after applying the country and prefix filters.
	NumberType NumberType
	// Return only numbers that start with these digits, matched right after the country dial code: with `country_code=US`, `prefix=212` matches +1 212 area-code numbers and `prefix=833` matches 833 toll-free numbers. Digits only. Leave out the country dial code and any national dialing prefix such as a leading 0. Short codes never match a prefix search.
	Prefix string
	// Filter by capability. Repeat the parameter to require several at once: `capabilities=sms&capabilities=voice` returns only numbers that support both.
	Capabilities []string
	// Maximum number of items to return per page.
	Limit int
}

func (p NumbersAvailableListParams) toWire(startingAfter string) *oapi.ListAvailableNumbersParams {
	return &oapi.ListAvailableNumbersParams{
		CountryCode:   p.CountryCode,
		NumberType:    optZero(p.NumberType),
		Prefix:        optStr(p.Prefix),
		Capabilities:  optSlice(p.Capabilities),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *NumbersAvailableService) ListPage(ctx context.Context, params NumbersAvailableListParams, startingAfter string, opts ...option.RequestOption) (*AvailableNumberList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListAvailableNumbers(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AvailableNumberList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List Searches one country's numbers on sale. Our own inventory answers first and pages; the last page can carry a live carrier snapshot, so a number seen here may be gone by the time it is ordered.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *NumbersAvailableService) List(ctx context.Context, params NumbersAvailableListParams, opts ...option.RequestOption) iter.Seq2[*AvailableNumber, error] {
	return paginate(func(cursor string) ([]AvailableNumber, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Re-checks one number from `numbers.available.list` against the carrier, so a stale search result is caught before it is ordered.
func (s *NumbersAvailableService) Get(ctx context.Context, number string, opts ...option.RequestOption) (*AvailableNumber, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetAvailableNumber(ctx, number, &oapi.GetAvailableNumberParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out AvailableNumber
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
