// Code generated by beak gen:event-consts. DO NOT EDIT.

package bird

import (
	"github.com/messagebird/bird-sdk-go/internal/oapi"
)

// ContactChannel is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the ContactChannel* constants with a
// default branch rather than treating the set as closed.
type ContactChannel = oapi.ContactChannel

const (
	ContactChannelEmail ContactChannel = "email"
)

// EmailEventType is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the EmailEventType* constants with a
// default branch rather than treating the set as closed.
type EmailEventType = oapi.EmailEventType

const (
	EmailEventTypeEmailAccepted         EmailEventType = "email.accepted"
	EmailEventTypeEmailBounced          EmailEventType = "email.bounced"
	EmailEventTypeEmailCanceled         EmailEventType = "email.canceled"
	EmailEventTypeEmailClicked          EmailEventType = "email.clicked"
	EmailEventTypeEmailComplained       EmailEventType = "email.complained"
	EmailEventTypeEmailDeferred         EmailEventType = "email.deferred"
	EmailEventTypeEmailDelivered        EmailEventType = "email.delivered"
	EmailEventTypeEmailListUnsubscribed EmailEventType = "email.list_unsubscribed"
	EmailEventTypeEmailOpened           EmailEventType = "email.opened"
	EmailEventTypeEmailOutOfBandBounce  EmailEventType = "email.out_of_band_bounce"
	EmailEventTypeEmailProcessed        EmailEventType = "email.processed"
	EmailEventTypeEmailRejected         EmailEventType = "email.rejected"
	EmailEventTypeEmailScheduled        EmailEventType = "email.scheduled"
	EmailEventTypeEmailUnsubscribed     EmailEventType = "email.unsubscribed"
)

// VerificationAttemptFailureReason is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the VerificationAttemptFailureReason* constants with a
// default branch rather than treating the set as closed.
type VerificationAttemptFailureReason = oapi.VerificationAttemptFailureReason

const (
	VerificationAttemptFailureReasonCarrierRejected    VerificationAttemptFailureReason = "carrier_rejected"
	VerificationAttemptFailureReasonChannelDisabled    VerificationAttemptFailureReason = "channel_disabled"
	VerificationAttemptFailureReasonChannelUnavailable VerificationAttemptFailureReason = "channel_unavailable"
	VerificationAttemptFailureReasonHardBounce         VerificationAttemptFailureReason = "hard_bounce"
	VerificationAttemptFailureReasonSoftBounce         VerificationAttemptFailureReason = "soft_bounce"
	VerificationAttemptFailureReasonUndelivered        VerificationAttemptFailureReason = "undelivered"
)

// VerificationChannel is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the VerificationChannel* constants with a
// default branch rather than treating the set as closed.
type VerificationChannel = oapi.VerificationChannel

const (
	VerificationChannelEmail    VerificationChannel = "email"
	VerificationChannelSms      VerificationChannel = "sms"
	VerificationChannelWhatsapp VerificationChannel = "whatsapp"
)

// VerificationTerminalReason is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the VerificationTerminalReason* constants with a
// default branch rather than treating the set as closed.
type VerificationTerminalReason = oapi.VerificationTerminalReason

const (
	VerificationTerminalReasonAttemptsExhausted VerificationTerminalReason = "attempts_exhausted"
	VerificationTerminalReasonTtlElapsed        VerificationTerminalReason = "ttl_elapsed"
)

// WhatsAppErrorCode is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the WhatsAppErrorCode* constants with a
// default branch rather than treating the set as closed.
type WhatsAppErrorCode = oapi.WhatsAppErrorCode

const (
	WhatsAppErrorCodeInsufficientBalance  WhatsAppErrorCode = "insufficient_balance"
	WhatsAppErrorCodeInternalError        WhatsAppErrorCode = "internal_error"
	WhatsAppErrorCodePriceNotFound        WhatsAppErrorCode = "price_not_found"
	WhatsAppErrorCodeRateLimited          WhatsAppErrorCode = "rate_limited"
	WhatsAppErrorCodeRecipientSuppressed  WhatsAppErrorCode = "recipient_suppressed"
	WhatsAppErrorCodeServiceWindowExpired WhatsAppErrorCode = "service_window_expired"
	WhatsAppErrorCodeUndeliverable        WhatsAppErrorCode = "undeliverable"
)

// WhatsAppTemplateCategory is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the WhatsAppTemplateCategory* constants with a
// default branch rather than treating the set as closed.
type WhatsAppTemplateCategory = oapi.WhatsAppTemplateCategory

const (
	WhatsAppTemplateCategoryAuthentication WhatsAppTemplateCategory = "authentication"
	WhatsAppTemplateCategoryMarketing      WhatsAppTemplateCategory = "marketing"
	WhatsAppTemplateCategoryUtility        WhatsAppTemplateCategory = "utility"
)

// WhatsAppTemplateParameterType is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the WhatsAppTemplateParameterType* constants with a
// default branch rather than treating the set as closed.
type WhatsAppTemplateParameterType = oapi.WhatsAppTemplateParameterType

const (
	WhatsAppTemplateParameterTypeText WhatsAppTemplateParameterType = "text"
)
