// Code generated by beak gen:event-consts. DO NOT EDIT.

package bird

import (
	"github.com/messagebird/bird-sdk-go/internal/oapi"
)

// EmailEventType is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the EmailEventType* constants with a
// default branch rather than treating the set as closed.
type EmailEventType = oapi.EmailEventType

const (
	EmailEventTypeEmailAccepted         = oapi.EmailEventTypeEmailAccepted
	EmailEventTypeEmailBounced          = oapi.EmailEventTypeEmailBounced
	EmailEventTypeEmailCanceled         = oapi.EmailEventTypeEmailCanceled
	EmailEventTypeEmailClicked          = oapi.EmailEventTypeEmailClicked
	EmailEventTypeEmailComplained       = oapi.EmailEventTypeEmailComplained
	EmailEventTypeEmailDeferred         = oapi.EmailEventTypeEmailDeferred
	EmailEventTypeEmailDelivered        = oapi.EmailEventTypeEmailDelivered
	EmailEventTypeEmailListUnsubscribed = oapi.EmailEventTypeEmailListUnsubscribed
	EmailEventTypeEmailOpened           = oapi.EmailEventTypeEmailOpened
	EmailEventTypeEmailOutOfBandBounce  = oapi.EmailEventTypeEmailOutOfBandBounce
	EmailEventTypeEmailProcessed        = oapi.EmailEventTypeEmailProcessed
	EmailEventTypeEmailRejected         = oapi.EmailEventTypeEmailRejected
	EmailEventTypeEmailScheduled        = oapi.EmailEventTypeEmailScheduled
	EmailEventTypeEmailUnsubscribed     = oapi.EmailEventTypeEmailUnsubscribed
)

// SMSErrorCode is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the SMSErrorCode* constants with a
// default branch rather than treating the set as closed.
type SMSErrorCode = oapi.SMSErrorCode

const (
	SMSErrorCodeBlockedByCarrier    = oapi.SMSErrorCodeBlockedByCarrier
	SMSErrorCodeBlockedByRecipient  = oapi.SMSErrorCodeBlockedByRecipient
	SMSErrorCodeContentRejected     = oapi.SMSErrorCodeContentRejected
	SMSErrorCodeInsufficientBalance = oapi.SMSErrorCodeInsufficientBalance
	SMSErrorCodeInvalidDestination  = oapi.SMSErrorCodeInvalidDestination
	SMSErrorCodeLandlineUnreachable = oapi.SMSErrorCodeLandlineUnreachable
	SMSErrorCodeProviderUnavailable = oapi.SMSErrorCodeProviderUnavailable
	SMSErrorCodeRecipientOptedOut   = oapi.SMSErrorCodeRecipientOptedOut
	SMSErrorCodeSenderUnregistered  = oapi.SMSErrorCodeSenderUnregistered
	SMSErrorCodeUnknown             = oapi.SMSErrorCodeUnknown
	SMSErrorCodeUnreachable         = oapi.SMSErrorCodeUnreachable
)

// VerificationAttemptFailureReason is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the VerificationAttemptFailureReason* constants with a
// default branch rather than treating the set as closed.
type VerificationAttemptFailureReason = oapi.VerificationAttemptFailureReason

const (
	VerificationAttemptFailureReasonCarrierRejected    = oapi.VerificationAttemptFailureReasonCarrierRejected
	VerificationAttemptFailureReasonChannelDisabled    = oapi.VerificationAttemptFailureReasonChannelDisabled
	VerificationAttemptFailureReasonChannelUnavailable = oapi.VerificationAttemptFailureReasonChannelUnavailable
	VerificationAttemptFailureReasonDeliveryTimeout    = oapi.VerificationAttemptFailureReasonDeliveryTimeout
	VerificationAttemptFailureReasonHardBounce         = oapi.VerificationAttemptFailureReasonHardBounce
	VerificationAttemptFailureReasonSoftBounce         = oapi.VerificationAttemptFailureReasonSoftBounce
	VerificationAttemptFailureReasonUndelivered        = oapi.VerificationAttemptFailureReasonUndelivered
)

// VerificationChannel is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the VerificationChannel* constants with a
// default branch rather than treating the set as closed.
type VerificationChannel = oapi.VerificationChannel

const (
	VerificationChannelEmail    = oapi.VerificationChannelEmail
	VerificationChannelSms      = oapi.VerificationChannelSms
	VerificationChannelWhatsapp = oapi.VerificationChannelWhatsapp
)

// VerificationTerminalReason is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the VerificationTerminalReason* constants with a
// default branch rather than treating the set as closed.
type VerificationTerminalReason = oapi.VerificationTerminalReason

const (
	VerificationTerminalReasonAttemptsExhausted = oapi.VerificationTerminalReasonAttemptsExhausted
	VerificationTerminalReasonTtlElapsed        = oapi.VerificationTerminalReasonTtlElapsed
)

// WhatsAppErrorCode is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the WhatsAppErrorCode* constants with a
// default branch rather than treating the set as closed.
type WhatsAppErrorCode = oapi.WhatsAppErrorCode

const (
	WhatsAppErrorCodeInsufficientBalance  = oapi.WhatsAppErrorCodeInsufficientBalance
	WhatsAppErrorCodeInternalError        = oapi.WhatsAppErrorCodeInternalError
	WhatsAppErrorCodePriceNotFound        = oapi.WhatsAppErrorCodePriceNotFound
	WhatsAppErrorCodeRateLimited          = oapi.WhatsAppErrorCodeRateLimited
	WhatsAppErrorCodeRecipientSuppressed  = oapi.WhatsAppErrorCodeRecipientSuppressed
	WhatsAppErrorCodeServiceWindowExpired = oapi.WhatsAppErrorCodeServiceWindowExpired
	WhatsAppErrorCodeUndeliverable        = oapi.WhatsAppErrorCodeUndeliverable
)

// WhatsAppTemplateCategory is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the WhatsAppTemplateCategory* constants with a
// default branch rather than treating the set as closed.
type WhatsAppTemplateCategory = oapi.WhatsAppTemplateCategory

const (
	WhatsAppTemplateCategoryAuthentication = oapi.WhatsAppTemplateCategoryAuthentication
	WhatsAppTemplateCategoryMarketing      = oapi.WhatsAppTemplateCategoryMarketing
	WhatsAppTemplateCategoryUtility        = oapi.WhatsAppTemplateCategoryUtility
)

// WhatsAppTemplateParameterType is an open string on the wire: a value added by a newer server
// deserializes unchanged, so compare against the WhatsAppTemplateParameterType* constants with a
// default branch rather than treating the set as closed.
type WhatsAppTemplateParameterType = oapi.WhatsAppTemplateParameterType

const (
	WhatsAppTemplateParameterTypeDocument = oapi.WhatsAppTemplateParameterTypeDocument
	WhatsAppTemplateParameterTypeGif      = oapi.WhatsAppTemplateParameterTypeGif
	WhatsAppTemplateParameterTypeImage    = oapi.WhatsAppTemplateParameterTypeImage
	WhatsAppTemplateParameterTypeLocation = oapi.WhatsAppTemplateParameterTypeLocation
	WhatsAppTemplateParameterTypeText     = oapi.WhatsAppTemplateParameterTypeText
	WhatsAppTemplateParameterTypeVideo    = oapi.WhatsAppTemplateParameterTypeVideo
)
