// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// PreferencesListParams filters the list. Zero-value fields are omitted.
type PreferencesListParams struct {
	// Return only preferences on this channel.
	Channel PreferenceChannel
	// Return only preferences for this exact handle: an email address or an E.164 phone number. Requires `channel`, since a handle only means something on its channel.
	Handle string
	// Maximum number of items to return per page.
	Limit int
}

func (p PreferencesListParams) toWire(startingAfter string) *oapi.ListPreferencesParams {
	return &oapi.ListPreferencesParams{
		Channel:       optZero(p.Channel),
		Handle:        optStr(p.Handle),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *PreferencesService) ListPage(ctx context.Context, params PreferencesListParams, startingAfter string, opts ...option.RequestOption) (*PreferenceList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListPreferences(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out PreferenceList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's stated messaging preferences (consent grants and opt-outs) as a cursor page. Filter by channel, and by handle within a channel, to look up one person before messaging them.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *PreferencesService) List(ctx context.Context, params PreferencesListParams, opts ...option.RequestOption) iter.Seq2[*Preference, error] {
	return paginate(func(cursor string) ([]Preference, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Read one recorded preference by ID: the channel and handle it is about, whether it grants or revokes, how much traffic it covers, and where the statement came from.
func (s *PreferencesService) Get(ctx context.Context, preferenceId string, opts ...option.RequestOption) (*Preference, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetPreference(ctx, oapi.PreferenceID(preferenceId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Preference
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
