// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// RealtimeChannelListParams filters the list read.
type RealtimeChannelListParams struct {
	// Only channels whose name starts with this prefix (for example, `presence-`).
	Prefix string
	// Per-channel attributes to include. Repeatable. Requesting `member_count` without a presence-channel `prefix`, or `connection_count` when the app's connection-counting flag is off, returns a validation error (400).
	Include []RealtimeChannelInclude
}

func (p RealtimeChannelListParams) toWire() *oapi.ListRealtimeAppChannelsParams {
	return &oapi.ListRealtimeAppChannelsParams{
		Prefix:  optStr(p.Prefix),
		Include: optSlice(p.Include),
	}
}

// RealtimeChannelGetParams filters the get read.
type RealtimeChannelGetParams struct {
	// Attributes to include. Repeatable. Requesting `member_count` for a non-presence channel, or `connection_count` when the app's connection-counting flag is off, returns a validation error (400).
	Include []RealtimeChannelInclude
}

func (p RealtimeChannelGetParams) toWire() *oapi.GetRealtimeAppChannelParams {
	return &oapi.GetRealtimeAppChannelParams{
		Include: optSlice(p.Include),
	}
}

func (s *RealtimeChannelsService) List(ctx context.Context, realtimeAppId string, params RealtimeChannelListParams, opts ...option.RequestOption) (*RealtimeChannelsList, error) {
	body, err := s.getAuth(ctx, opts, []string{"RealtimeKey", "RealtimeSecret"}, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListRealtimeAppChannels(ctx, oapi.RealtimeAppID(realtimeAppId), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out RealtimeChannelsList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *RealtimeChannelsService) Get(ctx context.Context, realtimeAppId string, channelName string, params RealtimeChannelGetParams, opts ...option.RequestOption) (*RealtimeChannelInfo, error) {
	body, err := s.getAuth(ctx, opts, []string{"RealtimeKey", "RealtimeSecret"}, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetRealtimeAppChannel(ctx, oapi.RealtimeAppID(realtimeAppId), oapi.RealtimeChannelName(channelName), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out RealtimeChannelInfo
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *RealtimeChannelsService) Members(ctx context.Context, realtimeAppId string, channelName string, opts ...option.RequestOption) (*RealtimeChannelMembers, error) {
	body, err := s.getAuth(ctx, opts, []string{"RealtimeKey", "RealtimeSecret"}, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListRealtimeAppChannelMembers(ctx, oapi.RealtimeAppID(realtimeAppId), oapi.RealtimeChannelName(channelName), &oapi.ListRealtimeAppChannelMembersParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out RealtimeChannelMembers
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
