// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// SmsListParams filters the list. Zero-value fields are omitted.
type SmsListParams struct {
	// Maximum number of items to return per page.
	Limit int
	// Limits the response to resources created at or after this timestamp. Combine it with `created_before` to select a time window. Use an RFC 3339 timestamp with a timezone offset.
	CreatedAfter time.Time
	// Limits the response to resources created before this timestamp. Combine it with `created_after` to select a time window. Use an RFC 3339 timestamp with a timezone offset.
	CreatedBefore time.Time
	// Filter by direction. Omit for both.
	Direction MessageDirection
	// Keep only messages whose current `status` matches; repeat the parameter to match any of several. One of `scheduled`, `accepted`, `sent`, `delivered`, `undelivered`, `failed`, `rejected`, `canceled`, `expired`, or `received`.
	Status []string
	// Keep only messages whose failure reason (`last_error.code`) matches; repeat the parameter to match any of several. One of `invalid_destination`, `unreachable`, `blocked_by_carrier`, `blocked_by_recipient`, `landline_unreachable`, `content_rejected`, `sender_unregistered`, `recipient_opted_out`, `provider_unavailable`, `insufficient_balance`, or `unknown`.
	ErrorCode []string
	// Filter by category.
	Category SMSMessageCategory
	// Filter by recipient phone number (E.164 exact match).
	To string
	// Filter by sender (E.164, alphanumeric, or short code; exact match).
	From string
	// Filter by tag. Accepts `name` to match any message carrying that tag name, or `name:value` to match a specific tag pair (for example `category:welcome`). Repeat the parameter to add more tags. A message must match every tag listed to be returned.
	Tag []string
}

func (p SmsListParams) toWire(startingAfter string) *oapi.ListSMSMessagesParams {
	return &oapi.ListSMSMessagesParams{
		Limit:         optInt(p.Limit),
		CreatedAfter:  optTime(p.CreatedAfter),
		CreatedBefore: optTime(p.CreatedBefore),
		Direction:     optZero(p.Direction),
		Status:        optSlice(p.Status),
		ErrorCode:     optSlice(p.ErrorCode),
		Category:      optZero(p.Category),
		To:            optStr(p.To),
		From:          optStr(p.From),
		Tag:           optSlice(p.Tag),
		StartingAfter: optStr(startingAfter),
	}
}

// SmsListEventsParams filters the list_events read.
type SmsListEventsParams struct {
	// Filter by event type, such as `sms.delivered` or `sms.failed`.
	Type string
}

func (p SmsListEventsParams) toWire() *oapi.ListSMSMessageEventsParams {
	return &oapi.ListSMSMessageEventsParams{
		Type: optStr(p.Type),
	}
}

// Get Get one SMS message by ID: its current delivery status, segment breakdown, cost, and failure detail if it failed.
func (s *SmsService) Get(ctx context.Context, messageId string, opts ...option.RequestOption) (*SMSMessage, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetSMSMessage(ctx, oapi.SMSMessageID(messageId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out SMSMessage
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *SmsService) ListPage(ctx context.Context, params SmsListParams, startingAfter string, opts ...option.RequestOption) (*SMSMessageList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListSMSMessages(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out SMSMessageList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List SMS messages, newest first, as a cursor page (`data`, `next_cursor`). Pass `next_cursor` back as `starting_after` to fetch the next page. Filter by direction, status, category, recipient, sender, or tag.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *SmsService) List(ctx context.Context, params SmsListParams, opts ...option.RequestOption) iter.Seq2[*SMSMessage, error] {
	return paginate(func(cursor string) ([]SMSMessage, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// ListEvents The lifecycle event timeline for one SMS, oldest first: what happened to it and when. Filter with `type` (for example `sms.delivered`) to keep one kind of event. Use `sms.get` for the message's current state and `sms.list` to find its ID.
func (s *SmsService) ListEvents(ctx context.Context, messageId string, params SmsListEventsParams, opts ...option.RequestOption) (*SMSEventList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListSMSMessageEvents(ctx, oapi.SMSMessageID(messageId), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out SMSEventList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
