// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// SmsSuppressionsListParams filters the list. Zero-value fields are omitted.
type SmsSuppressionsListParams struct {
	// Return only suppressions for this exact subscriber number in E.164 form. Prefix matching is unsupported.
	Destination string
	// Return only suppressions covering this sender.
	Originator string
	// Return only suppressions with this reason: - `keyword_stop`: The subscriber texted a stop keyword to the sender. - `carrier_opted_out`: Their carrier reported the opt-out. - `manual`: Added through the API or dashboard.
	Reason SMSSuppressionReasonFilter
	// Maximum number of items to return per page.
	Limit int
}

func (p SmsSuppressionsListParams) toWire(startingAfter string) *oapi.ListSMSSuppressionsParams {
	return &oapi.ListSMSSuppressionsParams{
		Destination:   optStr(p.Destination),
		Originator:    optStr(p.Originator),
		Reason:        optZero(p.Reason),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// SmsSuppressionsAddParams is the request body for add.
type SmsSuppressionsAddParams struct {
	// The subscriber to stop messaging, in E.164 format.
	Destination string
	// The sender to stop. Your other senders keep reaching this subscriber, so stopping every one of them means one call per sender.
	Originator string
}

func (p SmsSuppressionsAddParams) toWire() oapi.SMSSuppressionCreate {
	body := oapi.SMSSuppressionCreate{}
	body.Destination = p.Destination
	body.Originator = p.Originator
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *SmsSuppressionsService) ListPage(ctx context.Context, params SmsSuppressionsListParams, startingAfter string, opts ...option.RequestOption) (*SMSSuppressionList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListSMSSuppressions(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out SMSSuppressionList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's SMS suppressions (sender-and-subscriber pairs blocked from delivery) as a cursor page.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *SmsSuppressionsService) List(ctx context.Context, params SmsSuppressionsListParams, opts ...option.RequestOption) iter.Seq2[*SMSSuppression, error] {
	return paginate(func(cursor string) ([]SMSSuppression, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Read one SMS suppression: the sender and subscriber it covers, why messages are stopped, what it blocks, and whether it is still in force. To check whether you may message someone, filter `sms_suppressions.list` by their number instead.
func (s *SmsSuppressionsService) Get(ctx context.Context, suppressionId string, opts ...option.RequestOption) (*SMSSuppression, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetSMSSuppression(ctx, oapi.SMSSuppressionID(suppressionId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out SMSSuppression
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Add Stop one of your senders from messaging one subscriber. Covers that sender only; your other senders keep reaching them.
func (s *SmsSuppressionsService) Add(ctx context.Context, params SmsSuppressionsAddParams, opts ...option.RequestOption) (*SMSSuppression, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateSMSSuppressionParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateSMSSuppression(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out SMSSuppression
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Remove End a manual SMS suppression, letting that sender message that subscriber again. Only reason `manual` can be ended this way: a subscriber's own stop keyword and a carrier's opt-out are refused.
func (s *SmsSuppressionsService) Remove(ctx context.Context, suppressionId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteSMSSuppressionParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteSMSSuppression(ctx, oapi.SMSSuppressionID(suppressionId), op, cfg...)
	})
	return err
}
