// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// SMSTemplateListParams filters the list read.
type SMSTemplateListParams struct {
	// Keep only templates of this scope. Every SMS template is `system`, so `workspace` matches none. Omit for all.
	Scope TemplateScope
	// Keep only templates whose `category` matches. Omit for all categories.
	Category SMSMessageCategory
	// Keep only templates available in this language, as a BCP-47 tag. Matches the template's `available_languages` entries exactly, with no fallback.
	Language string
}

func (p SMSTemplateListParams) toWire() *oapi.ListSMSTemplatesParams {
	return &oapi.ListSMSTemplatesParams{
		Scope:    optZero(p.Scope),
		Category: optZero(p.Category),
		Language: optZero(p.Language),
	}
}

// List List the SMS templates available to your workspace, including our built-in templates. Filter by scope, category, or language. The catalog is small and returned in full; this list is not paginated. Use `sms_templates.get` to read one template's variables before sending with it.
func (s *SmsTemplatesService) List(ctx context.Context, params SMSTemplateListParams, opts ...option.RequestOption) (*SMSTemplateList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListSMSTemplates(ctx, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out SMSTemplateList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get Get one SMS template by its slug or ID, including its body and the variables it expects. Fetch it before `sms.send` to see which parameter keys a template send requires.
func (s *SmsTemplatesService) Get(ctx context.Context, templateRef string, opts ...option.RequestOption) (*SMSTemplate, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetSMSTemplate(ctx, templateRef, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out SMSTemplate
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
