// Code generated by surface-gen; DO NOT EDIT.

package bird_test

import (
	"testing"

	"github.com/messagebird/bird-sdk-go"
	"github.com/messagebird/bird-sdk-go/option"
)

// TestSurfaceConformance asserts every method the surface catalog assigns to
// the sdk surface exists on the Go client; a missing or renamed method fails to
// compile. Generated from backend/openapi/surfaces.ir.json.
func TestSurfaceConformance(t *testing.T) {
	c, err := bird.NewClient(option.WithAPIKey("bk_eu1_surfaceconformance"))
	if err != nil {
		t.Fatalf("construct client: %v", err)
	}
	_ = c.Email.Send
	_ = c.Email.SendBatch
	_ = c.Email.Get
	_ = c.Email.List
	_ = c.Webhooks.Unwrap
}
