// Code generated by surface-gen; DO NOT EDIT.

package bird_test

import (
	"testing"

	"github.com/messagebird/bird-sdk-go"
	"github.com/messagebird/bird-sdk-go/option"
)

// TestSurfaceConformance asserts every method the surface catalog assigns to
// the sdk surface exists on the Go client; a missing or renamed method fails to
// compile. Generated from backend/openapi/surfaces.ir.json.
func TestSurfaceConformance(t *testing.T) {
	c, err := bird.NewClient(option.WithAPIKey("bk_eu1_surfaceconformance"))
	if err != nil {
		t.Fatalf("construct client: %v", err)
	}
	_ = c.Email.Send
	_ = c.Email.SendBatch
	_ = c.Email.Get
	_ = c.Email.List
	_ = c.Email.Cancel
	_ = c.Email.Stats.Summary
	_ = c.Email.Stats.Daily
	_ = c.Email.Stats.Hourly
	_ = c.Email.Stats.ByTag
	_ = c.Email.Stats.ByCategory
	_ = c.Email.Stats.BySendingIP
	_ = c.Email.Stats.BySendingDomain
	_ = c.Email.Stats.ByRecipientDomain
	_ = c.Email.Stats.ByMailboxProvider
	_ = c.Email.Stats.ByMailboxProviderRegion
	_ = c.Email.Stats.ByTemplate
	_ = c.Email.Stats.ByLocation
	_ = c.Email.Stats.ByClient
	_ = c.Email.Stats.ByBounceCode
	_ = c.Email.Stats.ByComplaintType
	_ = c.Email.Stats.ByBroadcast
	_ = c.Sms.Send
	_ = c.Sms.SendBatch
	_ = c.Sms.Get
	_ = c.Sms.List
	_ = c.SmsTemplates.List
	_ = c.SmsTemplates.Get
	_ = c.Sms.ListEvents
	_ = c.Sms.Stats.Summary
	_ = c.Sms.Stats.Daily
	_ = c.Sms.Stats.Hourly
	_ = c.Sms.Stats.ByCountry
	_ = c.Sms.Stats.ByCarrier
	_ = c.Sms.Stats.ByCategory
	_ = c.Sms.Stats.ByOriginator
	_ = c.Sms.Stats.ByStatus
	_ = c.Sms.Stats.ByErrorCode
	_ = c.Sms.Stats.ByTag
	_ = c.Sms.Stats.Inbound.Summary
	_ = c.Sms.Stats.Inbound.Daily
	_ = c.Sms.Stats.Inbound.Hourly
	_ = c.Sms.Stats.Inbound.ByCountry
	_ = c.Sms.Stats.Inbound.ByOperator
	_ = c.Sms.Stats.Inbound.ByNumber
	_ = c.SmsSuppressions.List
	_ = c.SmsSuppressions.Get
	_ = c.SmsSuppressions.Add
	_ = c.SmsSuppressions.Remove
	_ = c.SmsKeywordRules.List
	_ = c.SmsKeywordRules.Get
	_ = c.SmsKeywordRules.Create
	_ = c.SmsKeywordRules.Update
	_ = c.SmsKeywordRules.Delete
	_ = c.Whatsapp.Send
	_ = c.Whatsapp.Get
	_ = c.Whatsapp.List
	_ = c.Whatsapp.ListEvents
	_ = c.Voice.List
	_ = c.Voice.Get
	_ = c.Verify.Verifications.Create
	_ = c.Verify.Verifications.Check
	_ = c.Verify.Verifications.NextChannel
	_ = c.Lookup.PhoneNumber
	_ = c.Lookup.Email
	_ = c.Numbers.List
	_ = c.Numbers.Get
	_ = c.Numbers.Release
	_ = c.Numbers.Available.List
	_ = c.Numbers.Available.Get
	_ = c.Numbers.Orders.Create
	_ = c.Numbers.Orders.List
	_ = c.Numbers.Orders.Get
	_ = c.Domains.List
	_ = c.Domains.Get
	_ = c.Domains.Create
	_ = c.Domains.Verify
	_ = c.Domains.Update
	_ = c.Domains.Delete
	_ = c.Workspace.Get
	_ = c.Webhooks.Unwrap
	_ = c.Preferences.List
	_ = c.Preferences.Get
	_ = c.Preferences.Create
	_ = c.Preferences.Delete
	_ = c.Contacts.List
	_ = c.Contacts.Get
	_ = c.Contacts.Create
	_ = c.Contacts.Update
	_ = c.Contacts.Delete
	_ = c.Contacts.Batch
	_ = c.Contacts.Preferences.List
	_ = c.ContactProperties.List
	_ = c.ContactProperties.Get
	_ = c.ContactProperties.Create
	_ = c.ContactProperties.Update
	_ = c.ContactProperties.Archive
	_ = c.ContactProperties.Unarchive
	_ = c.Audiences.List
	_ = c.Audiences.Get
	_ = c.Audiences.Create
	_ = c.Audiences.Update
	_ = c.Audiences.Delete
	_ = c.Audiences.ListContacts
	_ = c.Audiences.AddContacts
	_ = c.Audiences.RemoveContacts
	_ = c.Audiences.RemoveContact
	_ = c.Email.Mailboxes.List
	_ = c.Email.Mailboxes.Create
	_ = c.Email.Mailboxes.Get
	_ = c.Email.Mailboxes.Update
	_ = c.Email.Mailboxes.Delete
	_ = c.Email.Mailboxes.Restore
	_ = c.Email.Mailboxes.Resume
	_ = c.Email.Mailboxes.Stats
	_ = c.Email.Mailboxes.Messages.Create
	_ = c.Email.Mailboxes.Labels
	_ = c.Email.Mailboxes.ReceiveRules.List
	_ = c.Email.Mailboxes.ReceiveRules.Create
	_ = c.Email.Mailboxes.ReceiveRules.Delete
	_ = c.Email.Threads.List
	_ = c.Email.Threads.Get
	_ = c.Email.Threads.Update
	_ = c.Email.Threads.Delete
	_ = c.Email.Threads.Messages.List
	_ = c.Email.Threads.Messages.Get
	_ = c.Email.Threads.Messages.Body
	_ = c.Email.Threads.Messages.Reply
	_ = c.Email.Threads.Messages.Attachments
	_ = c.Realtime.Publish
	_ = c.Realtime.PublishBatch
	_ = c.Realtime.Channels.List
	_ = c.Realtime.Channels.Get
	_ = c.Realtime.Channels.Members
	_ = c.Realtime.Members.Send
	_ = c.Realtime.Members.Disconnect
}
