// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type VerificationOptions = oapi.VerificationOptions

type VerificationTo = oapi.VerificationTo

// VerifyVerificationsCreateParams is the request body for create.
type VerifyVerificationsCreateParams struct {
	// The recipient to verify. Provide an `email`, a `phone_number`, or both; at least one is required. The addresses also identify the verification: a check must supply exactly the set used on the create call, so a verification created with both addresses is not found by either one alone.
	To VerificationTo
	// Per-request overrides applied to this verification only.
	Options *VerificationOptions
	// Optional key/value pairs to attach to the verification, for example a correlation id. Returned on the verification.
	Metadata map[string]any
}

func (p VerifyVerificationsCreateParams) toWire() oapi.VerificationCreateRequest {
	body := oapi.VerificationCreateRequest{}
	body.To = p.To
	if p.Options != nil {
		body.Options = p.Options
	}
	if len(p.Metadata) > 0 {
		v := p.Metadata
		body.Metadata = &v
	}
	return body
}

// VerifyVerificationsCheckParams is the request body for check.
type VerifyVerificationsCheckParams struct {
	// The recipient to verify. Provide an `email`, a `phone_number`, or both; at least one is required. The addresses also identify the verification: a check must supply exactly the set used on the create call, so a verification created with both addresses is not found by either one alone.
	To VerificationTo
	// The passcode the recipient received. Passcodes are numeric; submit the digits exactly as delivered. An incorrect value is a normal `200` outcome with `success: false`. It does not return an error.
	Code string
}

func (p VerifyVerificationsCheckParams) toWire() oapi.VerificationCheckRequest {
	body := oapi.VerificationCheckRequest{}
	body.To = p.To
	body.Code = p.Code
	return body
}

// VerifyVerificationsNextChannelParams is the request body for next_channel.
type VerifyVerificationsNextChannelParams struct {
	// The recipient to verify. Provide an `email`, a `phone_number`, or both; at least one is required. The addresses also identify the verification: a check must supply exactly the set used on the create call, so a verification created with both addresses is not found by either one alone.
	To VerificationTo
}

func (p VerifyVerificationsNextChannelParams) toWire() oapi.VerificationNextChannelRequest {
	body := oapi.VerificationNextChannelRequest{}
	body.To = p.To
	return body
}

// Create Start a verification and send a one-time passcode to the email address, phone number, or both in `to`. Delivery uses one planned channel at a time and fails over when necessary. Calling again for the same recipient reuses the verification in progress and sends after the resend cooldown; each send past the cooldown spends one of the recipient's hourly send slots, so repeated resends can hit the cap and return 429. The passcode is never returned; submit the recipient's code with `verify.verifications.check`. SMS, WhatsApp, and Telegram delivery draw on the workspace's balance.
func (s *VerifyVerificationsService) Create(ctx context.Context, params VerifyVerificationsCreateParams, opts ...option.RequestOption) (*Verification, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateVerificationParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateVerification(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Verification
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Check Check a passcode a recipient submitted. Identify the verification by the same `to` recipient used to start it; no verification ID is needed. A wrong or expired code returns HTTP 200 with `success: false` and a `reason` (for example `incorrect_code` or `expired`). A verification that has already reached a final state is no longer checkable and returns 404 `E13000`, as does a missing verification, so a 404 does not tell you the recipient failed: treat an earlier `success: true` as the outcome rather than re-checking. Malformed input or rate limiting is also an error status.
func (s *VerifyVerificationsService) Check(ctx context.Context, params VerifyVerificationsCheckParams, opts ...option.RequestOption) (*VerificationCheckResult, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateVerificationCheckParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateVerificationCheck(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VerificationCheckResult
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// NextChannel Advance an in-progress verification to its next channel and send a fresh passcode. Identify it with the same `to` recipient used to create it; no verification ID is required. This bypasses the resend cooldown, and earlier passcodes remain valid. `last_channel` identifies the most recent completed send. `422 NoNextChannel` means the plan is exhausted; create the verification again to resend on the current channel.
func (s *VerifyVerificationsService) NextChannel(ctx context.Context, params VerifyVerificationsNextChannelParams, opts ...option.RequestOption) (*Verification, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateVerificationNextChannelParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateVerificationNextChannel(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out Verification
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
