// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// VoiceLegsListParams filters the list. Zero-value fields are omitted.
type VoiceLegsListParams struct {
	// Return only legs in this direction.
	Direction VoiceCallDirection
	// Return only legs with one of these statuses, comma-separated. In-flight and final statuses may be combined freely.
	Status []VoiceCallStatus
	// Return only legs belonging to this call, which is how the legs of one multi-party or transferred call are correlated.
	CallID string
	// Return only legs carried by this SIP trunk.
	SipTrunkID string
	// Return only legs placed from this calling party number, matched as a whole number rather than as a fragment. Give it in international form: `+14155551234`, `14155551234`, and `0014155551234` all select the same legs. A number given without a country code is read as an international one, so give the country code to be sure of what you are matching. Use `number` instead to match part of a number, or either side of the leg.
	From string
	// Return only legs placed to this called party number, matched as a whole number rather than as a fragment. Give it in international form: `+16505559876`, `16505559876`, and `0016505559876` all select the same legs. A number given without a country code is read as an international one, so give the country code to be sure of what you are matching. Use `number` instead to match part of a number, or either side of the leg.
	To string
	// Return only legs where the calling or called number contains this value. Matches a partial number, so a country or area-code prefix returns every leg to or from it. Combines with `from`/`to`, which match one side exactly.
	Number string
	// Filter by tag. Accepts `name` to match any record carrying that tag name, or `name:value` to match a specific tag pair (for example `category:welcome`). Repeat the parameter to add more tags. A record must match every tag listed to be returned.
	Tag []string
	// Return only legs that started at or after this instant, inclusive. RFC 3339 timestamp.
	StartedAfter time.Time
	// Return only legs that started at or before this instant, inclusive. RFC 3339 timestamp.
	StartedBefore time.Time
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p VoiceLegsListParams) toWire(startingAfter string) *oapi.ListVoiceLegsParams {
	return &oapi.ListVoiceLegsParams{
		Direction:     optZero(p.Direction),
		Status:        optSlice(p.Status),
		CallId:        optZero(p.CallID),
		SipTrunkId:    optZero(p.SipTrunkID),
		From:          optStr(p.From),
		To:            optStr(p.To),
		Number:        optStr(p.Number),
		Tag:           optSlice(p.Tag),
		StartedAfter:  optTime(p.StartedAfter),
		StartedBefore: optTime(p.StartedBefore),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *VoiceLegsService) ListPage(ctx context.Context, params VoiceLegsListParams, startingAfter string, opts ...option.RequestOption) (*VoiceLegList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListVoiceLegs(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceLegList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's legs, newest first. Filter to `ringing`/`in_progress` for the legs in progress right now, to final statuses for completed records, or to any mix of the two. Use `from`/`to` for one known party number in international form, and `number` to search either side by fragment. These are per-leg records and do not include aggregate rates or totals. Use `voice.legs.get` to follow one leg to settlement.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *VoiceLegsService) List(ctx context.Context, params VoiceLegsListParams, opts ...option.RequestOption) iter.Seq2[*VoiceLeg, error] {
	return paginate(func(cursor string) ([]VoiceLeg, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Fetch one leg by ID, at any point in its lifecycle. A leg still ringing or connected carries no economics yet: `duration_ms`, `billable_ms`, `ended_at`, and `cost` are null until it ends, and the same ID then returns the settled record. Poll here to watch one known leg; use `voice.legs.list` to find legs in the first place. When a leg was refused, `rejection_reason` names the gate that turned it away.
func (s *VoiceLegsService) Get(ctx context.Context, legId string, opts ...option.RequestOption) (*VoiceLeg, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetVoiceLeg(ctx, oapi.VoiceCallID(legId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceLeg
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
