// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type VoiceSIPDigestAlgorithm = oapi.VoiceSIPDigestAlgorithm

type VoiceTrunkIPACLCreate = oapi.VoiceTrunkIPACLCreate

// VoiceTrunksListParams filters the list. Zero-value fields are omitted.
type VoiceTrunksListParams struct {
	// Field to sort by.
	Sort VoiceTrunkSortField
	// Sort direction. Defaults to `desc`, which sorts from newest to oldest or largest to smallest, depending on the selected sort field.
	Order SortOrder
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p VoiceTrunksListParams) toWire(startingAfter string) *oapi.ListVoiceTrunksParams {
	return &oapi.ListVoiceTrunksParams{
		Sort:          optZero(p.Sort),
		Order:         optZero(p.Order),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		StartingAfter: optStr(startingAfter),
	}
}

// VoiceTrunksCreateParams is the request body for create.
type VoiceTrunksCreateParams struct {
	// A human-readable label for this SIP trunk. Mutable, and distinct from the generated wire domain.
	Name string
	// Whether the new trunk may place calls. Omit it to create a trunk that does neither direction yet, and enable the ones you want once you know what the trunk is for. The settings below configure outbound, so send this as `true` alongside them.
	OutboundEnabled *bool
	// Whether the new trunk may receive calls. Omit it to create a trunk that does neither direction yet. A trunk receives no calls until it also has at least one gateway and at least one number, both added after create.
	InboundEnabled *bool
	// Whether we take ourselves out of the audio path for calls we forward to this trunk. Omit it to create the trunk with this off, which is what suits equipment behind NAT and any account that wants call recording. It is an inbound setting, so `true` is accepted only alongside `inbound_enabled: true`; `false` is always accepted. It can be changed later.
	MediaBypass *bool
	// The Digest hash algorithms to offer, in the order they should be offered. Omit this to use the default of `["SHA-256", "MD5"]`, which suits most equipment. Send `["MD5"]` for a PBX that only implements MD5 and rejects or ignores a challenge offering SHA-256 first. This can be changed later without re-issuing credentials.
	DigestAlgorithms []VoiceSIPDigestAlgorithm
	// Whether a session credential may be used to connect to this trunk from a web browser, the CLI or MCP. Omit it to create the trunk with this off, which is what a trunk reached only by a PBX wants. It can be changed later.
	SessionCredentialsEnabled *bool
}

func (p VoiceTrunksCreateParams) toWire() oapi.VoiceTrunkCreate {
	body := oapi.VoiceTrunkCreate{}
	body.Name = p.Name
	body.OutboundEnabled = p.OutboundEnabled
	body.InboundEnabled = p.InboundEnabled
	body.MediaBypass = p.MediaBypass
	digestAlgorithms := make([]oapi.VoiceSIPDigestAlgorithm, len(p.DigestAlgorithms))
	for i, v := range p.DigestAlgorithms {
		digestAlgorithms[i] = oapi.VoiceSIPDigestAlgorithm(v)
	}
	if p.DigestAlgorithms != nil {
		body.DigestAlgorithms = &digestAlgorithms
	}
	body.SessionCredentialsEnabled = p.SessionCredentialsEnabled
	return body
}

// VoiceTrunksUpdateParams is the request body for update.
type VoiceTrunksUpdateParams struct {
	// A human-readable label for this SIP trunk. Mutable, and distinct from the generated wire domain.
	Name *string
	// Whether this trunk may place calls. Turning it off stops the trunk admitting call attempts at the next call setup and leaves its connection and authentication settings stored, so turning it back on restores a working trunk. Omit the field to leave it unchanged.
	OutboundEnabled *bool
	// Whether this trunk may receive calls. Turning it off resets number routes that use this trunk to reject incoming calls. Turning it back on does not restore those routes. The gateways remain configured. Omit the field to leave it unchanged.
	InboundEnabled *bool
	// Whether we take ourselves out of the audio path for calls we forward to this trunk. Turning it on takes effect at the next call setup and leaves calls already up untouched. It is an inbound setting, so the trunk must have `inbound_enabled` on; one update can do both. While it is on we cannot record those calls, report their audio quality, or end one because its audio stopped, and your equipment must be reachable for audio from the public internet. Turning it off puts us back in the path at the next call setup. Omit the field to leave it unchanged.
	MediaBypass *bool
	// Replaces the trunk's entire IP allow list. When present, the allow list is set to exactly these CIDR blocks: ranges not listed are removed and new ones are added. Send an empty array to clear the list, turning IP filtering off. Omit the field to leave the allow list unchanged.
	IPACLs []VoiceTrunkIPACLCreate
	// Replaces the trunk's entire set of allowed API keys. When present, exactly these keys may authenticate the trunk over SIP Digest. Each key you ADD must belong to this workspace and hold `voice` at write level; a key that does not is refused and the whole update is rolled back. A key already on the list that has since lost the permission or expired does not block the update, so you can keep editing the trunk while you put its permission back. A non-empty list turns API-key authentication on; send an empty array to turn it off. Omit the field to leave the allowed keys unchanged.
	AllowedAPIKeyIDs []string
	// Replaces the Digest hash algorithms this trunk offers, in the order they should be offered. Send `["MD5"]` for a PBX that only implements MD5 and rejects or ignores a challenge offering SHA-256 first. Send an empty array to return to the default of `["SHA-256", "MD5"]`. The offer is never empty, because a trunk that offered nothing could not be authenticated at all. Narrowing the list also narrows what the trunk accepts: an answer using an algorithm no longer offered is rejected. Takes effect on the next call setup; no credential is re-issued. Omit the field to leave the offer unchanged.
	DigestAlgorithms []VoiceSIPDigestAlgorithm
	// Whether a session credential may be used to connect to this trunk from a web browser, the CLI or MCP. Off by default; turning it on does not change what the allow lists admit, and turning it off stops those connections at the next call setup without re-issuing anything. Omit the field to leave it unchanged.
	SessionCredentialsEnabled *bool
}

func (p VoiceTrunksUpdateParams) toWire() oapi.VoiceTrunkUpdate {
	body := oapi.VoiceTrunkUpdate{}
	body.Name = p.Name
	body.OutboundEnabled = p.OutboundEnabled
	body.InboundEnabled = p.InboundEnabled
	body.MediaBypass = p.MediaBypass
	if p.IPACLs != nil {
		v := p.IPACLs
		body.IpAcls = &v
	}
	allowedApiKeyIds := make([]oapi.APIKeyID, len(p.AllowedAPIKeyIDs))
	for i, v := range p.AllowedAPIKeyIDs {
		allowedApiKeyIds[i] = oapi.APIKeyID(v)
	}
	if p.AllowedAPIKeyIDs != nil {
		body.AllowedApiKeyIds = &allowedApiKeyIds
	}
	digestAlgorithms := make([]oapi.VoiceSIPDigestAlgorithm, len(p.DigestAlgorithms))
	for i, v := range p.DigestAlgorithms {
		digestAlgorithms[i] = oapi.VoiceSIPDigestAlgorithm(v)
	}
	if p.DigestAlgorithms != nil {
		body.DigestAlgorithms = &digestAlgorithms
	}
	body.SessionCredentialsEnabled = p.SessionCredentialsEnabled
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *VoiceTrunksService) ListPage(ctx context.Context, params VoiceTrunksListParams, startingAfter string, opts ...option.RequestOption) (*VoiceTrunkList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListVoiceTrunks(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceTrunkList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's SIP trunks as a cursor page. Each carries the Bird-assigned `domain` the customer's equipment sends calls to. The `ip_acls` and `allowed_api_key_ids` fields control which calls are admitted; a trunk with both empty admits nothing when `session_credentials_enabled` is false. Keys listed in `ineligible_api_key_ids` cannot authenticate even though they remain bound to the trunk.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *VoiceTrunksService) List(ctx context.Context, params VoiceTrunksListParams, opts ...option.RequestOption) iter.Seq2[*VoiceTrunk, error] {
	return paginate(func(cursor string) ([]VoiceTrunk, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Fetch one SIP trunk by ID: its `domain`, `ip_acls`, and `allowed_api_key_ids`. Use `voice.trunks.list` to find the ID.
func (s *VoiceTrunksService) Get(ctx context.Context, trunkId string, opts ...option.RequestOption) (*VoiceTrunk, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetVoiceTrunk(ctx, oapi.SIPTrunkID(trunkId), &oapi.GetVoiceTrunkParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceTrunk
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create Create a new SIP trunk for the workspace. Returns the Bird-assigned domain to configure in the customer's PBX or SIP client.
func (s *VoiceTrunksService) Create(ctx context.Context, params VoiceTrunksCreateParams, opts ...option.RequestOption) (*VoiceTrunk, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateVoiceTrunkParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateVoiceTrunk(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceTrunk
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Change a SIP trunk's directions, name, access control and Digest offer. A direction has to be enabled before its settings can be set, and one update can do both, so this is the operation that clears `VoiceTrunkOutboundNotEnabled` and `VoiceTrunkInboundNotEnabled`. The `ip_acls`, `allowed_api_key_ids` and `digest_algorithms` fields each REPLACE their whole list, so read `voice.trunks.get` first and send the list you want to end up with. An empty array clears an allow list; an empty `digest_algorithms` array restores the default offer. Turning `inbound_enabled` off resets number routes that use this trunk to reject incoming calls. Turning it back on does not restore those routes, so confirm that change with the user first.
func (s *VoiceTrunksService) Update(ctx context.Context, trunkId string, params VoiceTrunksUpdateParams, opts ...option.RequestOption) (*VoiceTrunk, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UpdateVoiceTrunkParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateVoiceTrunk(ctx, oapi.SIPTrunkID(trunkId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceTrunk
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Delete a SIP trunk by ID. Calls in progress are not affected; new calls cannot use the trunk. Its generated domain is not reused.
func (s *VoiceTrunksService) Delete(ctx context.Context, trunkId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteVoiceTrunkParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteVoiceTrunk(ctx, oapi.SIPTrunkID(trunkId), op, cfg...)
	})
	return err
}
