// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// VoiceCallerIDsListParams filters the list. Zero-value fields are omitted.
type VoiceCallerIDsListParams struct {
	// Field to sort by.
	Sort VoiceCallerIDSortField
	// Sort direction. Defaults to `desc`, which sorts from newest to oldest or largest to smallest, depending on the selected sort field.
	Order SortOrder
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p VoiceCallerIDsListParams) toWire(startingAfter string) *oapi.ListVoiceCallerIDsParams {
	return &oapi.ListVoiceCallerIDsParams{
		Sort:          optZero(p.Sort),
		Order:         optZero(p.Order),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		StartingAfter: optStr(startingAfter),
	}
}

// VoiceCallerIDsVerifyParams is the request body for verify.
type VoiceCallerIDsVerifyParams struct {
	// The 6-digit verification code read out by the verification call.
	Code string
}

func (p VoiceCallerIDsVerifyParams) toWire() oapi.VoiceCallerIDVerifyRequest {
	body := oapi.VoiceCallerIDVerifyRequest{}
	body.Code = p.Code
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *VoiceCallerIDsService) ListPage(ctx context.Context, params VoiceCallerIDsListParams, startingAfter string, opts ...option.RequestOption) (*VoiceCallerIDList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListVoiceCallerIDs(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceCallerIDList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's caller IDs and their verification status, as a cursor page. Only a verified caller ID may be presented on an outbound call, so an unverified or missing entry here is a common reason a call is refused.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *VoiceCallerIDsService) List(ctx context.Context, params VoiceCallerIDsListParams, opts ...option.RequestOption) iter.Seq2[*VoiceCallerID, error] {
	return paginate(func(cursor string) ([]VoiceCallerID, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Fetch one caller ID by ID, with its verification status. Use `voice.caller_ids.list` to find the ID.
func (s *VoiceCallerIDsService) Get(ctx context.Context, callerId string, opts ...option.RequestOption) (*VoiceCallerID, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetVoiceCallerID(ctx, oapi.VoiceCallerIDID(callerId), &oapi.GetVoiceCallerIDParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceCallerID
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Verify Complete a caller-ID verification challenge started in the dashboard. Recovery can place another verification call to the same number and requires the organization to remain eligible to register caller IDs. For expired or exhausted challenges, ask the user to select Get a new code in the dashboard. List caller IDs again to obtain the replacement registration ID before submitting its code. Read Voice destinations separately to confirm whether the number's country is enabled.
func (s *VoiceCallerIDsService) Verify(ctx context.Context, callerId string, params VoiceCallerIDsVerifyParams, opts ...option.RequestOption) (*VoiceCallerID, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.VerifyVoiceCallerIDParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.VerifyVoiceCallerID(ctx, oapi.VoiceCallerIDID(callerId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceCallerID
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
