// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type CreateVoiceCallSequenceRequest = oapi.CreateVoiceCallSequenceRequest

// VoiceCallsCreateParams is the request body for create.
type VoiceCallsCreateParams struct {
	// Calling number that this workspace is permitted to present.
	From string
	// Recipient number in canonical E.164 form.
	To string
	// Maximum ringing time for the original dialing attempt, shared across routing candidates.
	RingingTimeoutSeconds *int
	Sequence              CreateVoiceCallSequenceRequest
}

func (p VoiceCallsCreateParams) toWire() oapi.CreateVoiceCallRequest {
	body := oapi.CreateVoiceCallRequest{}
	body.From = p.From
	body.To = p.To
	body.RingingTimeoutSeconds = p.RingingTimeoutSeconds
	body.Sequence = p.Sequence
	return body
}

// Create Places a real outbound call and starts the active published sequence after the recipient answers. Requires both voice management write and voice calling write permissions. Normal calling charges apply. Retain the acceptance IDs to inspect the run and initial leg.
func (s *VoiceCallsService) Create(ctx context.Context, params VoiceCallsCreateParams, opts ...option.RequestOption) (*VoiceCall, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateVoiceCallParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateVoiceCall(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceCall
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
