// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// Create Mint a short-lived SIP digest credential a calling client authenticates with. The password is returned once and cannot be retrieved again.
func (s *VoiceSessionCredentialsService) Create(ctx context.Context, opts ...option.RequestOption) (*VoiceSessionCredential, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateVoiceSessionCredentialParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateVoiceSessionCredential(ctx, op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceSessionCredential
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
