// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// VoiceListParams filters the list. Zero-value fields are omitted.
type VoiceListParams struct {
	// Return only calls in this direction.
	Direction VoiceCallDirection
	// Return only calls with one of these statuses, comma-separated. In-flight and final statuses may be combined freely.
	Status []VoiceCallStatus
	// Return only calls belonging to this session, which is how the legs of one multi-party or transferred call are correlated.
	SessionID string
	// Return only calls carried by this SIP trunk.
	SipTrunkID string
	// Return only calls placed from this calling party number, matched as a whole number rather than as a fragment. Give it in international form: `+14155551234`, `14155551234`, and `0014155551234` all select the same calls. A number given without a country code is read as an international one, so give the country code to be sure of what you are matching. Use `number` instead to match part of a number, or either side of the call.
	From string
	// Return only calls placed to this called party number, matched as a whole number rather than as a fragment. Give it in international form: `+16505559876`, `16505559876`, and `0016505559876` all select the same calls. A number given without a country code is read as an international one, so give the country code to be sure of what you are matching. Use `number` instead to match part of a number, or either side of the call.
	To string
	// Return only calls where the calling or called number contains this value. Matches a partial number, so a country or area-code prefix returns every call to or from it. Combines with `from`/`to`, which match one side exactly.
	Number string
	// Return only calls that started at or after this instant, inclusive. RFC 3339 timestamp.
	StartedAfter time.Time
	// Return only calls that started at or before this instant, inclusive. RFC 3339 timestamp.
	StartedBefore time.Time
	// Maximum number of items to return per page.
	Limit int
}

func (p VoiceListParams) toWire(startingAfter string) *oapi.ListVoiceCallsParams {
	return &oapi.ListVoiceCallsParams{
		Direction:     optZero(p.Direction),
		Status:        optSlice(p.Status),
		SessionId:     optZero(p.SessionID),
		SipTrunkId:    optZero(p.SipTrunkID),
		From:          optStr(p.From),
		To:            optStr(p.To),
		Number:        optStr(p.Number),
		StartedAfter:  optTime(p.StartedAfter),
		StartedBefore: optTime(p.StartedBefore),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *VoiceService) ListPage(ctx context.Context, params VoiceListParams, startingAfter string, opts ...option.RequestOption) (*VoiceCallList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListVoiceCalls(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceCallList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's calls, newest first. Filter to `ringing`/`in_progress` for the calls in progress right now, to final statuses for completed records, or to any mix of the two. Use `from`/`to` for one known party number in international form, and `number` to search either side by fragment. These are per-call records and do not include aggregate rates or totals. Use `voice.get` to follow one call to settlement.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *VoiceService) List(ctx context.Context, params VoiceListParams, opts ...option.RequestOption) iter.Seq2[*VoiceCall, error] {
	return paginate(func(cursor string) ([]VoiceCall, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Fetch one call by ID, at any point in its lifecycle. A call still ringing or connected carries no economics yet: `duration_ms`, `billable_ms`, `ended_at`, and `cost` are null until it ends, and the same ID then returns the settled record. Poll here to watch one known call; use `voice.list` to find calls in the first place. When a call was refused, `rejection_reason` names the gate that turned it away.
func (s *VoiceService) Get(ctx context.Context, callId string, opts ...option.RequestOption) (*VoiceCall, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetVoiceCall(ctx, oapi.VoiceCallID(callId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceCall
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
