// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// VoiceTrunksGatewaysCreateParams is the request body for create.
type VoiceTrunksGatewaysCreateParams struct {
	// SIP URI an inbound call to this trunk should be forwarded to. Give the host only, with an optional port: which number is dialed there comes from `destination_format`, so a URI carrying a user part is rejected.
	SipURI string
	// The order gateways are tried in, lowest first. Give two gateways the same priority to share calls between them evenly.
	Priority int
	// How this gateway wants the calling number spelled. Write a template whose `{number}` stands for the number without its leading `+`; the result is stated in the `P-Asserted-Identity` header of the delivered call. Omit it for E.164, which is `+{number}`. The template may add digits, letters and the characters `-_.!~*'()&=+$,;?/%#` around `{number}`, which may appear at most once, and anything else in braces is rejected so a misspelled placeholder cannot reach a call. A format with no `{number}` at all states the same identity on every call, which is what a peer that only accepts one authorized number wants. The call then carries nothing about who really called.
	OriginationFormat *string
	// How this gateway formats the dialed number. In the template, `{number}` represents the number without its leading `+`. The result is placed before the `sip_uri` host. For example, `1234#{number}` formats `+31201234567` as `sip:1234#31201234567@pbx.example.com:5060`. Omit it for E.164, which is `+{number}`. A format with no `{number}` at all sends every number this trunk answers to one fixed number, so `777000447973` reaches `sip:777000447973@pbx.example.com:5060` whatever was dialed. The same rules as `origination_format` apply to what the template may contain.
	DestinationFormat *string
}

func (p VoiceTrunksGatewaysCreateParams) toWire() oapi.VoiceTrunkGatewayCreate {
	body := oapi.VoiceTrunkGatewayCreate{}
	body.SipUri = p.SipURI
	body.Priority = p.Priority
	body.OriginationFormat = p.OriginationFormat
	body.DestinationFormat = p.DestinationFormat
	return body
}

// VoiceTrunksGatewaysUpdateParams is the request body for update.
type VoiceTrunksGatewaysUpdateParams struct {
	// SIP URI an inbound call to this trunk should be forwarded to. Give the host only, with an optional port: which number is dialed there comes from `destination_format`, so a URI carrying a user part is rejected.
	SipURI *string
	// The order gateways are tried in, lowest first. Give two gateways the same priority to share calls between them evenly.
	Priority *int
	// How this gateway wants the calling number spelled, as a template whose `{number}` stands for the number without its leading `+`. The result is stated in the `P-Asserted-Identity` header of the delivered call. Send an empty string to go back to E.164, which is `+{number}`. The template may add digits, letters and the characters `-_.!~*'()&=+$,;?/%#` around `{number}`, which may appear at most once, and anything else in braces is rejected so a misspelled placeholder cannot reach a call. A format with no `{number}` at all states the same identity on every call, which is what a peer that only accepts one authorized number wants. The call then carries nothing about who really called.
	OriginationFormat *string
	// How this gateway formats the dialed number. In the template, `{number}` represents the number without its leading `+`. The result is placed before the `sip_uri` host. For example, `1234#{number}` formats `+31201234567` as `sip:1234#31201234567@pbx.example.com:5060`. Send an empty string to go back to E.164, which is `+{number}`. A format with no `{number}` at all sends every number this trunk answers to one fixed number, so `777000447973` reaches `sip:777000447973@pbx.example.com:5060` whatever was dialed. The same rules as `origination_format` apply to what the template may contain.
	DestinationFormat *string
}

func (p VoiceTrunksGatewaysUpdateParams) toWire() oapi.VoiceTrunkGatewayUpdate {
	body := oapi.VoiceTrunkGatewayUpdate{}
	body.SipUri = p.SipURI
	body.Priority = p.Priority
	body.OriginationFormat = p.OriginationFormat
	body.DestinationFormat = p.DestinationFormat
	return body
}

// List Read the complete inbound gateway list for a trunk, ordered by priority. Available even when inbound calling is disabled.
func (s *VoiceTrunksGatewaysService) List(ctx context.Context, trunkId string, opts ...option.RequestOption) (*VoiceTrunkGatewayList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListVoiceTrunkGateways(ctx, oapi.SIPTrunkID(trunkId), &oapi.ListVoiceTrunkGatewaysParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceTrunkGatewayList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get Read one inbound gateway and its SIP address, priority, and number formats. The gateway must belong to the specified trunk in this workspace.
func (s *VoiceTrunksGatewaysService) Get(ctx context.Context, trunkId string, gatewayId string, opts ...option.RequestOption) (*VoiceTrunkGateway, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetVoiceTrunkGateway(ctx, oapi.SIPTrunkID(trunkId), oapi.VoiceTrunkGatewayID(gatewayId), &oapi.GetVoiceTrunkGatewayParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceTrunkGateway
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create Add an address for inbound call delivery. Enable inbound calling on the trunk first; a trunk supports up to 20 gateways.
func (s *VoiceTrunksGatewaysService) Create(ctx context.Context, trunkId string, params VoiceTrunksGatewaysCreateParams, opts ...option.RequestOption) (*VoiceTrunkGateway, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateVoiceTrunkGatewayParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateVoiceTrunkGateway(ctx, oapi.SIPTrunkID(trunkId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceTrunkGateway
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Change an inbound gateway address, priority, or number formats. Omitted fields stay unchanged; an empty format restores E.164. Requires inbound calling enabled.
func (s *VoiceTrunksGatewaysService) Update(ctx context.Context, trunkId string, gatewayId string, params VoiceTrunksGatewaysUpdateParams, opts ...option.RequestOption) (*VoiceTrunkGateway, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UpdateVoiceTrunkGatewayParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateVoiceTrunkGateway(ctx, oapi.SIPTrunkID(trunkId), oapi.VoiceTrunkGatewayID(gatewayId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out VoiceTrunkGateway
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Remove an inbound gateway. Removing the last gateway stops new inbound delivery through the trunk. Requires inbound calling enabled.
func (s *VoiceTrunksGatewaysService) Delete(ctx context.Context, trunkId string, gatewayId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteVoiceTrunkGatewayParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteVoiceTrunkGateway(ctx, oapi.SIPTrunkID(trunkId), oapi.VoiceTrunkGatewayID(gatewayId), op, cfg...)
	})
	return err
}
