// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

type WebhookEndpointUpdateStatus = oapi.WebhookEndpointUpdateStatus

type WebhookEventType = oapi.WebhookEventType

// WebhooksListParams filters the list. Zero-value fields are omitted.
type WebhooksListParams struct {
	Sort WebhookSortField
	// Sort direction. Defaults to `desc`, which sorts from newest to oldest or largest to smallest, depending on the selected sort field.
	Order string
	// Maximum number of items to return per page.
	Limit int
	// When true, the response includes a `total` field with the total number of items matching the request's filters across all pages.
	IncludeTotal bool
}

func (p WebhooksListParams) toWire(startingAfter string) *oapi.ListWebhooksParams {
	return &oapi.ListWebhooksParams{
		Sort:          optZero(p.Sort),
		Order:         optEnum[oapi.ListWebhooksParamsOrder](p.Order),
		Limit:         optInt(p.Limit),
		IncludeTotal:  optBool(p.IncludeTotal),
		StartingAfter: optStr(startingAfter),
	}
}

// WebhooksCreateParams is the request body for create.
type WebhooksCreateParams struct {
	// HTTPS URL to deliver events to, at most 2048 characters. The host must be publicly reachable: URLs on private, loopback, or link-local addresses are rejected with a `422`.
	URL string
	// Event types to subscribe to; the endpoint receives only matching events. Types outside the event catalog return a `422`, and an endpoint holds at most 100 entries.
	Events []WebhookEventType
	// Human-readable label for this endpoint, up to 256 characters.
	Description string
}

func (p WebhooksCreateParams) toWire() oapi.WebhookEndpointCreate {
	body := oapi.WebhookEndpointCreate{}
	body.Url = p.URL
	events := make([]oapi.WebhookEventType, len(p.Events))
	for i, v := range p.Events {
		events[i] = oapi.WebhookEventType(v)
	}
	body.Events = events
	if p.Description != "" {
		body.Description = Ptr(p.Description)
	}
	return body
}

// WebhooksTestParams is the request body for test.
type WebhooksTestParams struct {
	// Event type to simulate. Any type from the event catalog is accepted, whether or not the endpoint subscribes to it; an unknown type returns a `422`. When omitted, the endpoint's first subscribed event type is used.
	EventType string
}

func (p WebhooksTestParams) toWire() oapi.WebhookTestRequest {
	body := oapi.WebhookTestRequest{}
	if p.EventType != "" {
		body.EventType = Ptr(p.EventType)
	}
	return body
}

// WebhooksAttemptsParams filters the attempts read.
type WebhooksAttemptsParams struct {
	// Maximum number of attempts to return. Defaults to 50, capped at 100.
	Limit int
	// Only return attempts strictly before this timestamp.
	Before time.Time
	// Only return attempts strictly after this timestamp.
	After time.Time
}

func (p WebhooksAttemptsParams) toWire() *oapi.ListWebhookAttemptsParams {
	return &oapi.ListWebhookAttemptsParams{
		Limit:  optInt(p.Limit),
		Before: optTime(p.Before),
		After:  optTime(p.After),
	}
}

// WebhooksUpdateParams is the request body for update.
type WebhooksUpdateParams struct {
	// Replacement delivery URL. Same rules as at creation: HTTPS, at most 2048 characters, and the host must be publicly reachable (private, loopback, and link-local addresses return a `422`). Omit to keep the current URL.
	URL string
	// Human-readable label for this endpoint, up to 256 characters.
	Description string
	// Replaces all event subscriptions with this list. Omit to keep the current set. Types outside the event catalog return a `422`.
	Events []WebhookEventType
	// `paused` stops all deliveries; `active` re-enables a paused endpoint. Omit to leave the status unchanged. Events that fire while paused are not delivered; after re-enabling, recover them with [Replay missed events](/docs/api/reference/create-webhook-replay). A `degraded` endpoint cannot be reset through this field: it returns to `active` automatically once deliveries succeed again.
	Status *WebhookEndpointUpdateStatus
}

func (p WebhooksUpdateParams) toWire() oapi.WebhookEndpointUpdate {
	body := oapi.WebhookEndpointUpdate{}
	if p.URL != "" {
		body.Url = Ptr(p.URL)
	}
	if p.Description != "" {
		body.Description = Ptr(p.Description)
	}
	events := make([]oapi.WebhookEventType, len(p.Events))
	for i, v := range p.Events {
		events[i] = oapi.WebhookEventType(v)
	}
	if len(events) > 0 {
		body.Events = &events
	}
	if p.Status != nil {
		body.Status = p.Status
	}
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *WebhooksService) ListPage(ctx context.Context, params WebhooksListParams, startingAfter string, opts ...option.RequestOption) (*WebhookEndpointList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListWebhooks(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WebhookEndpointList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's webhook endpoints (URL, subscribed events, status) as a cursor page.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *WebhooksService) List(ctx context.Context, params WebhooksListParams, opts ...option.RequestOption) iter.Seq2[*WebhookEndpoint, error] {
	return paginate(func(cursor string) ([]WebhookEndpoint, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Read one endpoint's URL, subscribed event types, and current delivery status. The signing secret is never included, and can only be rotated rather than retrieved.
func (s *WebhooksService) Get(ctx context.Context, webhookId string, opts ...option.RequestOption) (*WebhookEndpoint, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetWebhook(ctx, oapi.WebhookEndpointID(webhookId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WebhookEndpoint
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create Register an HTTPS endpoint to receive this workspace's events, subscribed to the event types in `events` and active immediately. The response is the only place the signing secret appears, and it can never be read back afterward, only rotated.
func (s *WebhooksService) Create(ctx context.Context, params WebhooksCreateParams, opts ...option.RequestOption) (*WebhookEndpointCreated, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateWebhookParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateWebhook(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WebhookEndpointCreated
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Test Send a signed synthetic event and get the outcome synchronously: whether the endpoint accepted, the HTTP status it returned, and the round-trip latency. An unreachable endpoint comes back as a failed status in the body rather than a request error. The receiver has 10 seconds, the body is a minimal stub carrying only the event type, and a test reaches even a paused endpoint without being recorded in the delivery attempts.
func (s *WebhooksService) Test(ctx context.Context, webhookId string, params WebhooksTestParams, opts ...option.RequestOption) (*WebhookTestResponse, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.TestWebhookParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.TestWebhook(ctx, oapi.WebhookEndpointID(webhookId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WebhookTestResponse
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Permanently remove an endpoint and stop every delivery to it, including retries of earlier failures. Recreating it later mints a new ID and signing secret; to stop deliveries temporarily instead, set its status to `paused`.
func (s *WebhooksService) Delete(ctx context.Context, webhookId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteWebhookParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteWebhook(ctx, oapi.WebhookEndpointID(webhookId), op, cfg...)
	})
	return err
}

// Attempts List an endpoint's recent delivery attempts, newest first. Each entry is one HTTP request, so a retried event appears once per try. Pagination uses the `before`/`after` timestamps; page further back by passing the oldest `attempted_at` you received as `before`.
func (s *WebhooksService) Attempts(ctx context.Context, webhookId string, params WebhooksAttemptsParams, opts ...option.RequestOption) (*WebhookAttemptList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListWebhookAttempts(ctx, oapi.WebhookEndpointID(webhookId), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WebhookAttemptList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// RotateSecret Mint a new signing secret and return it exactly once; it cannot be retrieved afterward. Both the old and new secrets sign every delivery for 24 hours, after which the old one stops signing. An endpoint holds at most 5 valid secrets, so rotating repeatedly inside that window fails.
func (s *WebhooksService) RotateSecret(ctx context.Context, webhookId string, opts ...option.RequestOption) (*WebhookRotateSecretResponse, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.RotateWebhookSecretParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.RotateWebhookSecret(ctx, oapi.WebhookEndpointID(webhookId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WebhookRotateSecretResponse
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Change an endpoint's URL, description, subscribed event types, or delivery status. Only the fields sent change: `events` replaces the whole subscription set, and `status` pauses or re-enables delivery. Events fired while paused are not delivered.
func (s *WebhooksService) Update(ctx context.Context, webhookId string, params WebhooksUpdateParams, opts ...option.RequestOption) (*WebhookEndpoint, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.UpdateWebhookParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.UpdateWebhook(ctx, oapi.WebhookEndpointID(webhookId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WebhookEndpoint
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
