// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// Get Read the business profile WhatsApp shows to people a connected number messages.
func (s *WhatsappNumbersProfileService) Get(ctx context.Context, numberId string, opts ...option.RequestOption) (*WhatsAppNumberProfile, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetWhatsAppNumberProfile(ctx, oapi.WhatsAppNumberID(numberId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppNumberProfile
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
