// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// WhatsappSuppressionsListParams filters the list. Zero-value fields are omitted.
type WhatsappSuppressionsListParams struct {
	// Address prefix filter (case-insensitive). A complete address returns only that address; a partial value returns all matches.
	Address string
	// Return only suppressions with this reason: - `manual`: Added through the API or dashboard.
	Reason WhatsAppSuppressionReasonFilter
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p WhatsappSuppressionsListParams) toWire(startingAfter string) *oapi.ListWhatsAppSuppressionsParams {
	return &oapi.ListWhatsAppSuppressionsParams{
		Address:       optStr(p.Address),
		Reason:        optZero(p.Reason),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		StartingAfter: optStr(startingAfter),
	}
}

// WhatsappSuppressionsAddParams is the request body for add.
type WhatsappSuppressionsAddParams struct {
	// WhatsApp address to suppress. For a phone number, supply canonical E.164 with a leading plus sign, such as `+5511977670804`. A value that is not a valid phone number returns a `422`.
	Address string
	// Limit the suppression to messages sent from this WhatsApp Business Account, identified by its WhatsApp-issued account ID. Omit it to block the address for the whole workspace, whichever account sends.
	Waba *string
}

func (p WhatsappSuppressionsAddParams) toWire() oapi.WhatsAppSuppressionCreate {
	body := oapi.WhatsAppSuppressionCreate{}
	body.Address = p.Address
	body.Waba = p.Waba
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *WhatsappSuppressionsService) ListPage(ctx context.Context, params WhatsappSuppressionsListParams, startingAfter string, opts ...option.RequestOption) (*WhatsAppSuppressionList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListWhatsAppSuppressions(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppSuppressionList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's recorded WhatsApp suppression addresses as a cursor page.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *WhatsappSuppressionsService) List(ctx context.Context, params WhatsappSuppressionsListParams, opts ...option.RequestOption) iter.Seq2[*WhatsAppSuppression, error] {
	return paginate(func(cursor string) ([]WhatsAppSuppression, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Read one WhatsApp suppression by ID, including one that has already ended. An ended record reports when it ended and what ended it. To find a suppression by address rather than by ID, use `whatsapp.suppressions.list` with its address filter.
func (s *WhatsappSuppressionsService) Get(ctx context.Context, suppressionId string, opts ...option.RequestOption) (*WhatsAppSuppression, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetWhatsAppSuppression(ctx, oapi.WhatsAppSuppressionID(suppressionId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppSuppression
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Add Record a WhatsApp address on the workspace suppression list.
func (s *WhatsappSuppressionsService) Add(ctx context.Context, params WhatsappSuppressionsAddParams, opts ...option.RequestOption) (*WhatsAppSuppression, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateWhatsAppSuppressionParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateWhatsAppSuppression(ctx, op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppSuppression
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Remove End one WhatsApp suppression by ID. The record is kept and stays readable. Only suppressions with reason `manual` can be ended; a recipient's own opt-out is refused.
func (s *WhatsappSuppressionsService) Remove(ctx context.Context, suppressionId string, opts ...option.RequestOption) error {
	_, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.DeleteWhatsAppSuppressionParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.DeleteWhatsAppSuppression(ctx, oapi.WhatsAppSuppressionID(suppressionId), op, cfg...)
	})
	return err
}
