// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// WhatsappTemplatesVersionsListParams filters the list. Zero-value fields are omitted.
type WhatsappTemplatesVersionsListParams struct {
	// Maximum number of items to return per page.
	Limit int
}

func (p WhatsappTemplatesVersionsListParams) toWire(startingAfter string) *oapi.ListWhatsAppTemplateVersionsParams {
	return &oapi.ListWhatsAppTemplateVersionsParams{
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *WhatsappTemplatesVersionsService) ListPage(ctx context.Context, templateRef string, params WhatsappTemplatesVersionsListParams, startingAfter string, opts ...option.RequestOption) (*WhatsAppTemplateVersionList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListWhatsAppTemplateVersions(ctx, templateRef, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppTemplateVersionList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List a WhatsApp template's versions, newest first. Each version is one immutable submission; an open draft, if one exists, appears alongside them. Use this to find the version a send resolves to, or the draft still being edited.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *WhatsappTemplatesVersionsService) List(ctx context.Context, templateRef string, params WhatsappTemplatesVersionsListParams, opts ...option.RequestOption) iter.Seq2[*WhatsAppTemplateVersionSummary, error] {
	return paginate(func(cursor string) ([]WhatsAppTemplateVersionSummary, *string, error) {
		page, err := s.ListPage(ctx, templateRef, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Get one version of a WhatsApp template: its submission state and the languages it carries. This is the level at which content exists.
func (s *WhatsappTemplatesVersionsService) Get(ctx context.Context, templateRef string, versionId string, opts ...option.RequestOption) (*WhatsAppTemplateVersion, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetWhatsAppTemplateVersion(ctx, templateRef, oapi.WhatsAppTemplateVersionID(versionId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppTemplateVersion
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
