// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// Rotate Issue a new invite link for the group and invalidate every link issued before. Anyone holding an old link can no longer join. The group's current link is on the group itself, so read it rather than rotating to fetch it. Answers 200: the new link comes back on the call itself.
func (s *WhatsappGroupsInviteLinkService) Rotate(ctx context.Context, groupId string, opts ...option.RequestOption) (*WhatsAppGroupInviteLink, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.RotateWhatsAppGroupInviteLinkParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.RotateWhatsAppGroupInviteLink(ctx, oapi.WhatsAppGroupID(groupId), op, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppGroupInviteLink
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
