// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"
	"time"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// WhatsappListParams filters the list. Zero-value fields are omitted.
type WhatsappListParams struct {
	// Maximum number of items to return per page.
	Limit int
	// Limits the response to resources created at or after this timestamp. Combine it with `created_before` to select a time window. Use an RFC 3339 timestamp with a timezone offset.
	CreatedAfter time.Time
	// Limits the response to resources created before this timestamp. Combine it with `created_after` to select a time window. Use an RFC 3339 timestamp with a timezone offset.
	CreatedBefore time.Time
	// Filter by status. Repeat the parameter to match any of several statuses.
	Status []WhatsAppMessageStatus
	// Filter by whether the business sent the message (`outbound`) or received it from the contact (`inbound`).
	Direction MessageDirection
	// Filter by recipient, exact match. The recipient is the contact on an outbound message and your business number on an inbound one, matching the `to` each message returns. Accepts an E.164 phone number, or a business-scoped user ID to name the contact. Only a contact is ever identified by a business-scoped user ID, so `to=<business-scoped user ID>` matches outbound messages only.
	To string
	// Filter by sender, exact match. The sender is your business number on an outbound message and the contact on an inbound one, matching the `from` each message returns. Accepts an E.164 phone number, or a business-scoped user ID to name the contact. Only a contact is ever identified by a business-scoped user ID, so `from=<business-scoped user ID>` matches inbound messages only.
	From string
	// Deprecated: use `to` or `from` instead, which also match a business-scoped user ID. Filters by contact phone number (E.164 exact match), in either direction.
	PhoneNumber string
	// Filter by business-scoped user ID (Meta identifier), matching the contact in either direction. `to` and `from` also accept one, but each matches a single end of the message.
	Bsuid string
	// Filter by category.
	Category WhatsAppTemplateCategory
	// Filter by tag. Accepts `name` to match any record carrying that tag name, or `name:value` to match a specific tag pair (for example `category:welcome`). Repeat the parameter to add more tags. A record must match every tag listed to be returned.
	Tag []string
}

func (p WhatsappListParams) toWire(startingAfter string) *oapi.ListWhatsAppMessagesParams {
	return &oapi.ListWhatsAppMessagesParams{
		Limit:         optInt(p.Limit),
		CreatedAfter:  optTime(p.CreatedAfter),
		CreatedBefore: optTime(p.CreatedBefore),
		Status:        optSlice(p.Status),
		Direction:     optZero(p.Direction),
		To:            optStr(p.To),
		From:          optStr(p.From),
		PhoneNumber:   optStr(p.PhoneNumber),
		Bsuid:         optStr(p.Bsuid),
		Category:      optZero(p.Category),
		Tag:           optSlice(p.Tag),
		StartingAfter: optStr(startingAfter),
	}
}

// WhatsappListEventsParams filters the list_events read.
type WhatsappListEventsParams struct {
	// Keep only events of this exact type (for example `whatsapp.delivered` or `whatsapp.failed`). Omit for the full timeline.
	Type WhatsAppEventType
}

func (p WhatsappListEventsParams) toWire() *oapi.ListWhatsAppMessageEventsParams {
	return &oapi.ListWhatsAppMessageEventsParams{
		Type: optZero(p.Type),
	}
}

// Get Get one WhatsApp message by id: current delivery status, sent/delivered/read timestamps, the one content it was built from (a template, or free-form text, image, video, audio, sticker, document, location, interactive or contact_cards, or interactive_reply on an inbound tap), and failure detail if it failed. For the per-event timeline use whatsapp_list_events.
func (s *WhatsappService) Get(ctx context.Context, messageId string, opts ...option.RequestOption) (*WhatsAppMessage, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetWhatsAppMessage(ctx, oapi.WhatsAppMessageID(messageId), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppMessage
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *WhatsappService) ListPage(ctx context.Context, params WhatsappListParams, startingAfter string, opts ...option.RequestOption) (*WhatsAppMessageList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListWhatsAppMessages(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppMessageList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List WhatsApp messages, newest first, as a cursor page ({data, next_cursor, …}). Each message carries the one content it was built from: a template, or free-form text, image, video, audio, sticker, document, location, interactive or contact_cards. An inbound tap on a reply button or list row carries interactive_reply instead. Pass next_cursor back as starting_after to fetch the next page. Filter by direction, status, recipient (to), sender (from), business-scoped user ID (bsuid), template category, or tag. to and from each accept a phone number or a business-scoped user ID; pair either with direction to search a single side of the message. Use whatsapp_get for one message's current state.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *WhatsappService) List(ctx context.Context, params WhatsappListParams, opts ...option.RequestOption) iter.Seq2[*WhatsAppMessage, error] {
	return paginate(func(cursor string) ([]WhatsAppMessage, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// ListEvents Get one WhatsApp message's delivery timeline, oldest first: whatsapp.accepted, whatsapp.sent, whatsapp.delivered, whatsapp.read, and whatsapp.failed events, with failure detail on failed events. Not paginated; an unknown message ID returns `404`. Use `whatsapp.get` for the condensed current status.
func (s *WhatsappService) ListEvents(ctx context.Context, messageId string, params WhatsappListEventsParams, opts ...option.RequestOption) (*WhatsAppEventList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListWhatsAppMessageEvents(ctx, oapi.WhatsAppMessageID(messageId), params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppEventList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
