// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// WhatsappTemplatesListParams filters the list. Zero-value fields are omitted.
type WhatsappTemplatesListParams struct {
	// Filter to a single WhatsApp Business Account by its Meta WABA ID: the same value each template reports in its own `waba` field. Our built-in templates belong to no account and are never returned when this is set, and an account your workspace does not hold returns an empty page.
	Waba string
	// Filter by lifecycle status. Repeat the parameter to match any of several. Our built-in templates are always `active`.
	Status []TemplateStatus
	// Filter by ownership tier: `system` for the built-in, Meta-approved template catalog, or `workspace` for the workspace's own templates. Omit to return both.
	Scope TemplateScope
	// Filter by template category.
	Category WhatsAppTemplateCategory
	// A case-insensitive substring search across the template's slug, name, and description.
	Q string
	// Maximum number of items to return per page.
	Limit int
}

func (p WhatsappTemplatesListParams) toWire(startingAfter string) *oapi.ListWhatsAppTemplatesParams {
	return &oapi.ListWhatsAppTemplatesParams{
		Waba:          optStr(p.Waba),
		Status:        optSlice(p.Status),
		Scope:         optZero(p.Scope),
		Category:      optZero(p.Category),
		Q:             optStr(p.Q),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *WhatsappTemplatesService) ListPage(ctx context.Context, params WhatsappTemplatesListParams, startingAfter string, opts ...option.RequestOption) (*WhatsAppTemplateList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListWhatsAppTemplates(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppTemplateList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the workspace's WhatsApp templates: each template's handle, its lifecycle, and where each of its languages stands. Content is not included; use `whatsapp.templates.versions.get` for that.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *WhatsappTemplatesService) List(ctx context.Context, params WhatsappTemplatesListParams, opts ...option.RequestOption) iter.Seq2[*WhatsAppTemplate, error] {
	return paginate(func(cursor string) ([]WhatsAppTemplate, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Get one WhatsApp template by slug or ID: its handle, its lifecycle, and where each of its languages stands. Content is not included; use `whatsapp.templates.versions.get` for that.
func (s *WhatsappTemplatesService) Get(ctx context.Context, templateRef string, opts ...option.RequestOption) (*WhatsAppTemplate, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetWhatsAppTemplate(ctx, templateRef, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppTemplate
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
