// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// WhatsappAgentsNotificationsListParams filters the list. Zero-value fields are omitted.
type WhatsappAgentsNotificationsListParams struct {
	// Return only notifications in this state.
	Status WhatsAppAgentNotificationStatus
	// Return only notifications about this contact, a phone number in E.164 format or a business-scoped user ID. A phone number is normalized before matching, so spacing does not matter.
	To string
	// Maximum number of items to return per page.
	Limit int
	// Cursor from the `prev_cursor` or `refresh_cursor` field of a previous list response. Returns items immediately before the cursor position in the current sort order. `prev_cursor` returns the preceding page. `refresh_cursor` anchors at the first row of that response, which on a newest-first sort is how to fetch the items that have appeared since.
	EndingBefore string
}

func (p WhatsappAgentsNotificationsListParams) toWire(startingAfter string) *oapi.ListWhatsAppAgentNotificationsParams {
	return &oapi.ListWhatsAppAgentNotificationsParams{
		Status:        optZero(p.Status),
		To:            optStr(p.To),
		Limit:         optInt(p.Limit),
		EndingBefore:  optStr(p.EndingBefore),
		StartingAfter: optStr(startingAfter),
	}
}

// WhatsappAgentsNotificationsCreateParams is the request body for create.
type WhatsappAgentsNotificationsCreateParams struct {
	// The contact the notification is about: a phone number in E.164 format (for example `+14155551234`), or the contact's business-scoped user ID (for example `US.13491208655302741918`), the same forms a message's `to` accepts. A phone number is normalized before the call reaches WhatsApp, so spacing does not matter. WhatsApp documents a phone number for this call; a business-scoped user ID is passed through as given.
	To string
	// Your own name for what happened, such as `payment_received` or `order_shipped`. The agent reads it as the kind of thing that happened, so keep one name per kind. WhatsApp calls this the event type.
	Name string
	// What happened, in a sentence the agent can tell the contact.
	Description string
	// Details the agent may draw on when it writes to the contact, as one JSON string. WhatsApp passes it to the agent unchanged and does not read it itself.
	Payload string
}

func (p WhatsappAgentsNotificationsCreateParams) toWire() oapi.WhatsAppAgentNotificationCreate {
	body := oapi.WhatsAppAgentNotificationCreate{}
	body.To = p.To
	body.Name = p.Name
	body.Description = p.Description
	body.Payload = p.Payload
	return body
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *WhatsappAgentsNotificationsService) ListPage(ctx context.Context, numberId string, params WhatsappAgentsNotificationsListParams, startingAfter string, opts ...option.RequestOption) (*WhatsAppAgentNotificationList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListWhatsAppAgentNotifications(ctx, oapi.WhatsAppNumberID(numberId), params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppAgentNotificationList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the notifications sent to the agent on this WhatsApp number, newest first, each with what came of it, as a cursor page.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *WhatsappAgentsNotificationsService) List(ctx context.Context, numberId string, params WhatsappAgentsNotificationsListParams, opts ...option.RequestOption) iter.Seq2[*WhatsAppAgentNotification, error] {
	return paginate(func(cursor string) ([]WhatsAppAgentNotification, *string, error) {
		pageParams := params
		if cursor != "" {
			pageParams.EndingBefore = ""
		}
		page, err := s.ListPage(ctx, numberId, pageParams, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Create Tell the agent on this WhatsApp number that something happened in your systems for one contact, such as a payment landing or an order shipping, so it can write to them about it. The notification is handed to WhatsApp in the background; read it back with `whatsapp.agents.notifications.get` to see whether the agent acted on it.
func (s *WhatsappAgentsNotificationsService) Create(ctx context.Context, numberId string, params WhatsappAgentsNotificationsCreateParams, opts ...option.RequestOption) (*WhatsAppAgentNotification, error) {
	body, err := s.post(ctx, opts, func(ctx context.Context, idempotencyKey string, cfg requestConfig) (*http.Response, error) {
		op := &oapi.CreateWhatsAppAgentNotificationParams{}
		if idempotencyKey != "" {
			op.IdempotencyKey = &idempotencyKey
		}
		return s.client.oapi.CreateWhatsAppAgentNotification(ctx, oapi.WhatsAppNumberID(numberId), op, params.toWire(), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppAgentNotification
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get Read one notification sent to the agent on this WhatsApp number, with what came of it.
func (s *WhatsappAgentsNotificationsService) Get(ctx context.Context, numberId string, notificationId string, opts ...option.RequestOption) (*WhatsAppAgentNotification, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetWhatsAppAgentNotification(ctx, oapi.WhatsAppNumberID(numberId), oapi.WhatsAppAgentNotificationID(notificationId), &oapi.GetWhatsAppAgentNotificationParams{}, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppAgentNotification
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
