// Code generated by surface-gen; DO NOT EDIT.
package bird

import (
	"context"
	"iter"
	"net/http"

	"github.com/messagebird/bird-sdk-go/internal/oapi"
	"github.com/messagebird/bird-sdk-go/option"
)

// WhatsappBusinessAccountsListParams filters the list. Zero-value fields are omitted.
type WhatsappBusinessAccountsListParams struct {
	// Field to sort by.
	Sort WhatsAppBusinessAccountSortField
	// Sort direction. Defaults to `desc`, which sorts from newest to oldest or largest to smallest, depending on the selected sort field.
	Order string
	// Maximum number of items to return per page.
	Limit int
}

func (p WhatsappBusinessAccountsListParams) toWire(startingAfter string) *oapi.ListWhatsAppBusinessAccountsParams {
	return &oapi.ListWhatsAppBusinessAccountsParams{
		Sort:          optZero(p.Sort),
		Order:         optEnum[oapi.ListWhatsAppBusinessAccountsParamsOrder](p.Order),
		Limit:         optInt(p.Limit),
		StartingAfter: optStr(startingAfter),
	}
}

// ListPage fetches one page of results. Pass the previous page's NextCursor as
// startingAfter to advance; "" starts from the first page.
func (s *WhatsappBusinessAccountsService) ListPage(ctx context.Context, params WhatsappBusinessAccountsListParams, startingAfter string, opts ...option.RequestOption) (*WhatsAppBusinessAccountList, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.ListWhatsAppBusinessAccounts(ctx, params.toWire(startingAfter), cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppBusinessAccountList
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List List the WhatsApp Business Accounts the workspace has connected, as a cursor page, with the state WhatsApp reports for each. The `waba` a returned account carries is the same value that ties a number to its account, and the one `whatsapp.numbers.list`'s `waba` filter takes.
// Range over it; the second value is non-nil only on the iteration where a
// fetch failed.
func (s *WhatsappBusinessAccountsService) List(ctx context.Context, params WhatsappBusinessAccountsListParams, opts ...option.RequestOption) iter.Seq2[*WhatsAppBusinessAccount, error] {
	return paginate(func(cursor string) ([]WhatsAppBusinessAccount, *string, error) {
		page, err := s.ListPage(ctx, params, cursor, opts...)
		if err != nil {
			return nil, nil, err
		}
		return page.Data, page.NextCursor, nil
	})
}

// Get Read one connected WhatsApp Business Account by its `id` (`waa_` prefix) or the ID WhatsApp reports in `waba`, with the state WhatsApp reports for the account.
func (s *WhatsappBusinessAccountsService) Get(ctx context.Context, businessAccountRef string, opts ...option.RequestOption) (*WhatsAppBusinessAccount, error) {
	body, err := s.get(ctx, opts, func(ctx context.Context, cfg requestConfig) (*http.Response, error) {
		return s.client.oapi.GetWhatsAppBusinessAccount(ctx, businessAccountRef, cfg...)
	})
	if err != nil {
		return nil, err
	}
	var out WhatsAppBusinessAccount
	if err := decodeBody(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
